// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DNSInitParameters struct {

	// Specifies whether custom DNS servers are enabled for VPN clients. Defaults to `true` when `servers` is non-empty.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// DNS servers to push to VPN clients.
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`
}

type DNSObservation struct {

	// Specifies whether custom DNS servers are enabled for VPN clients. Defaults to `true` when `servers` is non-empty.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// DNS servers to push to VPN clients.
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`
}

type DNSParameters struct {

	// Specifies whether custom DNS servers are enabled for VPN clients. Defaults to `true` when `servers` is non-empty.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// DNS servers to push to VPN clients.
	// +kubebuilder:validation:Optional
	Servers []*string `json:"servers,omitempty" tf:"servers,omitempty"`
}

type L2TpInitParameters struct {

	// Allow weak ciphers for L2TP connections.
	AllowWeakCiphers *bool `json:"allowWeakCiphers,omitempty" tf:"allow_weak_ciphers,omitempty"`

	// IPsec pre-shared key for L2TP. Required by the UniFi controller.
	PreSharedKeySecretRef v1.LocalSecretKeySelector `json:"preSharedKeySecretRef" tf:"-"`
}

type L2TpObservation struct {

	// Allow weak ciphers for L2TP connections.
	AllowWeakCiphers *bool `json:"allowWeakCiphers,omitempty" tf:"allow_weak_ciphers,omitempty"`
}

type L2TpParameters struct {

	// Allow weak ciphers for L2TP connections.
	// +kubebuilder:validation:Optional
	AllowWeakCiphers *bool `json:"allowWeakCiphers,omitempty" tf:"allow_weak_ciphers,omitempty"`

	// IPsec pre-shared key for L2TP. Required by the UniFi controller.
	// +kubebuilder:validation:Optional
	PreSharedKeySecretRef v1.LocalSecretKeySelector `json:"preSharedKeySecretRef" tf:"-"`
}

type OpenvpnInitParameters struct {

	// Encryption cipher for OpenVPN.
	EncryptionCipher *string `json:"encryptionCipher,omitempty" tf:"encryption_cipher,omitempty"`

	// OpenVPN mode.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Port for the OpenVPN server to listen on.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type OpenvpnObservation struct {

	// Encryption cipher for OpenVPN.
	EncryptionCipher *string `json:"encryptionCipher,omitempty" tf:"encryption_cipher,omitempty"`

	// OpenVPN mode.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Port for the OpenVPN server to listen on.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type OpenvpnParameters struct {

	// Encryption cipher for OpenVPN.
	// +kubebuilder:validation:Optional
	EncryptionCipher *string `json:"encryptionCipher,omitempty" tf:"encryption_cipher,omitempty"`

	// OpenVPN mode.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// Port for the OpenVPN server to listen on.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type ServerInitParameters struct {
	DNS *DNSInitParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	// Specifies whether the VPN server is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	L2Tp *L2TpInitParameters `json:"l2tp,omitempty" tf:"l2tp,omitempty"`

	// The name of the VPN server.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Openvpn *OpenvpnInitParameters `json:"openvpn,omitempty" tf:"openvpn,omitempty"`

	// The ID of the RADIUS profile to use for authentication. Applicable to L2TP and OpenVPN server types.
	RadiusprofileID *string `json:"radiusprofileId,omitempty" tf:"radiusprofile_id,omitempty"`

	// The name of the site to associate the VPN server with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// The VPN server subnet in CIDR notation (e.g., `10.100.0.1/24`). The first address is the server's tunnel IP, so use the gateway form (`10.100.0.1/24`) — the network address (`10.100.0.0/24`) is rejected with `api.err.IncorrectIPSubnetSpec`.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	Timeouts *ServerTimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	Wan *WanInitParameters `json:"wan,omitempty" tf:"wan,omitempty"`

	Wireguard *ServerWireguardInitParameters `json:"wireguard,omitempty" tf:"wireguard,omitempty"`
}

type ServerObservation struct {
	DNS *DNSObservation `json:"dns,omitempty" tf:"dns,omitempty"`

	// Specifies whether the VPN server is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	L2Tp *L2TpObservation `json:"l2tp,omitempty" tf:"l2tp,omitempty"`

	// The name of the VPN server.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Openvpn *OpenvpnObservation `json:"openvpn,omitempty" tf:"openvpn,omitempty"`

	// The ID of the RADIUS profile to use for authentication. Applicable to L2TP and OpenVPN server types.
	RadiusprofileID *string `json:"radiusprofileId,omitempty" tf:"radiusprofile_id,omitempty"`

	// The name of the site to associate the VPN server with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// The VPN server subnet in CIDR notation (e.g., `10.100.0.1/24`). The first address is the server's tunnel IP, so use the gateway form (`10.100.0.1/24`) — the network address (`10.100.0.0/24`) is rejected with `api.err.IncorrectIPSubnetSpec`.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	Timeouts *ServerTimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	Wan *WanObservation `json:"wan,omitempty" tf:"wan,omitempty"`

	Wireguard *ServerWireguardObservation `json:"wireguard,omitempty" tf:"wireguard,omitempty"`
}

type ServerParameters struct {

	// +kubebuilder:validation:Optional
	DNS *DNSParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	// Specifies whether the VPN server is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	L2Tp *L2TpParameters `json:"l2tp,omitempty" tf:"l2tp,omitempty"`

	// The name of the VPN server.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Openvpn *OpenvpnParameters `json:"openvpn,omitempty" tf:"openvpn,omitempty"`

	// The ID of the RADIUS profile to use for authentication. Applicable to L2TP and OpenVPN server types.
	// +kubebuilder:validation:Optional
	RadiusprofileID *string `json:"radiusprofileId,omitempty" tf:"radiusprofile_id,omitempty"`

	// The name of the site to associate the VPN server with.
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// The VPN server subnet in CIDR notation (e.g., `10.100.0.1/24`). The first address is the server's tunnel IP, so use the gateway form (`10.100.0.1/24`) — the network address (`10.100.0.0/24`) is rejected with `api.err.IncorrectIPSubnetSpec`.
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *ServerTimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// +kubebuilder:validation:Optional
	Wan *WanParameters `json:"wan,omitempty" tf:"wan,omitempty"`

	// +kubebuilder:validation:Optional
	Wireguard *ServerWireguardParameters `json:"wireguard,omitempty" tf:"wireguard,omitempty"`
}

type ServerTimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ServerTimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ServerTimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ServerWireguardInitParameters struct {

	// UDP port for the WireGuard server to listen on.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// WireGuard private key for this server (base64). If not specified, the provider generates one at create time (the controller does not generate it and rejects a server without a key).
	PrivateKeySecretRef *v1.LocalSecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`
}

type ServerWireguardObservation struct {

	// UDP port for the WireGuard server to listen on.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// WireGuard public key for this server. Computed from the private key.
	PublicKey *string `json:"publicKey,omitempty" tf:"public_key,omitempty"`
}

type ServerWireguardParameters struct {

	// UDP port for the WireGuard server to listen on.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// WireGuard private key for this server (base64). If not specified, the provider generates one at create time (the controller does not generate it and rejects a server without a key).
	// +kubebuilder:validation:Optional
	PrivateKeySecretRef *v1.LocalSecretKeySelector `json:"privateKeySecretRef,omitempty" tf:"-"`
}

type WanInitParameters struct {

	// Local WAN IP to bind the VPN server to. Use `any` to listen on all addresses.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// WAN interface to use for the VPN server (e.g., `wan`, `wan2`).
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type WanObservation struct {

	// Local WAN IP to bind the VPN server to. Use `any` to listen on all addresses.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// WAN interface to use for the VPN server (e.g., `wan`, `wan2`).
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type WanParameters struct {

	// Local WAN IP to bind the VPN server to. Use `any` to listen on all addresses.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// WAN interface to use for the VPN server (e.g., `wan`, `wan2`).
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

// ServerSpec defines the desired state of Server
type ServerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ServerInitParameters `json:"initProvider,omitempty"`
}

// ServerStatus defines the observed state of Server.
type ServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Server is the Schema for the Servers API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,unifi}
type Server struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subnet) || (has(self.initProvider) && has(self.initProvider.subnet))",message="spec.forProvider.subnet is a required parameter"
	Spec   ServerSpec   `json:"spec"`
	Status ServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ServerList contains a list of Servers
type ServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Server `json:"items"`
}

// Repository type metadata.
var (
	Server_Kind             = "Server"
	Server_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Server_Kind}.String()
	Server_KindAPIVersion   = Server_Kind + "." + CRDGroupVersion.String()
	Server_GroupVersionKind = CRDGroupVersion.WithKind(Server_Kind)
)

func init() {
	SchemeBuilder.Register(&Server{}, &ServerList{})
}
