// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ClientInitParameters struct {

	// Specifies whether to use the VPN as the default route.
	DefaultRoute *bool `json:"defaultRoute,omitempty" tf:"default_route,omitempty"`

	// Specifies whether the VPN client is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The name of the VPN client.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies whether to pull DNS servers from the VPN.
	PullDNS *bool `json:"pullDns,omitempty" tf:"pull_dns,omitempty"`

	// The name of the site to associate the VPN client with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// The local IP address for the WireGuard tunnel in CIDR notation (e.g., `10.0.0.2/24`).
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	Timeouts *ClientTimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	Wireguard *WireguardInitParameters `json:"wireguard,omitempty" tf:"wireguard,omitempty"`
}

type ClientObservation struct {

	// Specifies whether to use the VPN as the default route.
	DefaultRoute *bool `json:"defaultRoute,omitempty" tf:"default_route,omitempty"`

	// Specifies whether the VPN client is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the VPN client.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies whether to pull DNS servers from the VPN.
	PullDNS *bool `json:"pullDns,omitempty" tf:"pull_dns,omitempty"`

	// The name of the site to associate the VPN client with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// The local IP address for the WireGuard tunnel in CIDR notation (e.g., `10.0.0.2/24`).
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	Timeouts *ClientTimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	Wireguard *WireguardObservation `json:"wireguard,omitempty" tf:"wireguard,omitempty"`
}

type ClientParameters struct {

	// Specifies whether to use the VPN as the default route.
	// +kubebuilder:validation:Optional
	DefaultRoute *bool `json:"defaultRoute,omitempty" tf:"default_route,omitempty"`

	// Specifies whether the VPN client is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The name of the VPN client.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Specifies whether to pull DNS servers from the VPN.
	// +kubebuilder:validation:Optional
	PullDNS *bool `json:"pullDns,omitempty" tf:"pull_dns,omitempty"`

	// The name of the site to associate the VPN client with.
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// The local IP address for the WireGuard tunnel in CIDR notation (e.g., `10.0.0.2/24`).
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *ClientTimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// +kubebuilder:validation:Optional
	Wireguard *WireguardParameters `json:"wireguard,omitempty" tf:"wireguard,omitempty"`
}

type ClientTimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ClientTimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ClientTimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ConfigurationInitParameters struct {

	// Base64-encoded WireGuard configuration file content.
	ContentSecretRef v1.SecretKeySelector `json:"contentSecretRef" tf:"-"`

	// Filename of the WireGuard configuration file.
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`
}

type ConfigurationObservation struct {

	// Filename of the WireGuard configuration file.
	Filename *string `json:"filename,omitempty" tf:"filename,omitempty"`
}

type ConfigurationParameters struct {

	// Base64-encoded WireGuard configuration file content.
	// +kubebuilder:validation:Optional
	ContentSecretRef v1.SecretKeySelector `json:"contentSecretRef" tf:"-"`

	// Filename of the WireGuard configuration file.
	// +kubebuilder:validation:Optional
	Filename *string `json:"filename" tf:"filename,omitempty"`
}

type PeerInitParameters struct {

	// WireGuard peer endpoint IP address.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// WireGuard peer endpoint port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// WireGuard peer public key.
	PublicKeySecretRef v1.SecretKeySelector `json:"publicKeySecretRef" tf:"-"`
}

type PeerObservation struct {

	// WireGuard peer endpoint IP address.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// WireGuard peer endpoint port.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type PeerParameters struct {

	// WireGuard peer endpoint IP address.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip" tf:"ip,omitempty"`

	// WireGuard peer endpoint port.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port" tf:"port,omitempty"`

	// WireGuard peer public key.
	// +kubebuilder:validation:Optional
	PublicKeySecretRef v1.SecretKeySelector `json:"publicKeySecretRef" tf:"-"`
}

type WireguardInitParameters struct {
	Configuration *ConfigurationInitParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// DNS servers for the WireGuard interface. Required for manual mode. Must specify 1-2 DNS server addresses.
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// WAN interface to use for the VPN connection (e.g., `wan`, `wan2`).
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	Peer *PeerInitParameters `json:"peer,omitempty" tf:"peer,omitempty"`

	// Specifies whether to use a preshared key for additional security.
	PresharedKeyEnabled *bool `json:"presharedKeyEnabled,omitempty" tf:"preshared_key_enabled,omitempty"`

	// WireGuard preshared key. Required when preshared_key_enabled is true.
	PresharedKeySecretRef *v1.SecretKeySelector `json:"presharedKeySecretRef,omitempty" tf:"-"`

	// WireGuard private key for this client.
	PrivateKeySecretRef v1.SecretKeySelector `json:"privateKeySecretRef" tf:"-"`
}

type WireguardObservation struct {
	Configuration *ConfigurationObservation `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// DNS servers for the WireGuard interface. Required for manual mode. Must specify 1-2 DNS server addresses.
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// WAN interface to use for the VPN connection (e.g., `wan`, `wan2`).
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	Peer *PeerObservation `json:"peer,omitempty" tf:"peer,omitempty"`

	// Specifies whether to use a preshared key for additional security.
	PresharedKeyEnabled *bool `json:"presharedKeyEnabled,omitempty" tf:"preshared_key_enabled,omitempty"`
}

type WireguardParameters struct {

	// +kubebuilder:validation:Optional
	Configuration *ConfigurationParameters `json:"configuration,omitempty" tf:"configuration,omitempty"`

	// DNS servers for the WireGuard interface. Required for manual mode. Must specify 1-2 DNS server addresses.
	// +kubebuilder:validation:Optional
	DNSServers []*string `json:"dnsServers,omitempty" tf:"dns_servers,omitempty"`

	// WAN interface to use for the VPN connection (e.g., `wan`, `wan2`).
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// +kubebuilder:validation:Optional
	Peer *PeerParameters `json:"peer,omitempty" tf:"peer,omitempty"`

	// Specifies whether to use a preshared key for additional security.
	// +kubebuilder:validation:Optional
	PresharedKeyEnabled *bool `json:"presharedKeyEnabled,omitempty" tf:"preshared_key_enabled,omitempty"`

	// WireGuard preshared key. Required when preshared_key_enabled is true.
	// +kubebuilder:validation:Optional
	PresharedKeySecretRef *v1.SecretKeySelector `json:"presharedKeySecretRef,omitempty" tf:"-"`

	// WireGuard private key for this client.
	// +kubebuilder:validation:Optional
	PrivateKeySecretRef v1.SecretKeySelector `json:"privateKeySecretRef" tf:"-"`
}

// ClientSpec defines the desired state of Client
type ClientSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ClientParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ClientInitParameters `json:"initProvider,omitempty"`
}

// ClientStatus defines the observed state of Client.
type ClientStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ClientObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Client is the Schema for the Clients API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,unifi}
type Client struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subnet) || (has(self.initProvider) && has(self.initProvider.subnet))",message="spec.forProvider.subnet is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.wireguard) || (has(self.initProvider) && has(self.initProvider.wireguard))",message="spec.forProvider.wireguard is a required parameter"
	Spec   ClientSpec   `json:"spec"`
	Status ClientStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ClientList contains a list of Clients
type ClientList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Client `json:"items"`
}

// Repository type metadata.
var (
	Client_Kind             = "Client"
	Client_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Client_Kind}.String()
	Client_KindAPIVersion   = Client_Kind + "." + CRDGroupVersion.String()
	Client_GroupVersionKind = CRDGroupVersion.WithKind(Client_Kind)
)

func init() {
	SchemeBuilder.Register(&Client{}, &ClientList{})
}
