// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type ToSiteVPNInitParameters struct {

	// Whether IPsec dynamic routing is enabled.
	DynamicRouting *bool `json:"dynamicRouting,omitempty" tf:"dynamic_routing,omitempty"`

	// Whether the tunnel is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// ESP (phase 2) Diffie-Hellman group (PFS). Only used when `profile = customized`.
	EspDhGroup *float64 `json:"espDhGroup,omitempty" tf:"esp_dh_group,omitempty"`

	// ESP (phase 2) encryption. Only used when `profile = customized`.
	EspEncryption *string `json:"espEncryption,omitempty" tf:"esp_encryption,omitempty"`

	// ESP (phase 2) hash. Only used when `profile = customized`.
	EspHash *string `json:"espHash,omitempty" tf:"esp_hash,omitempty"`

	// ESP (phase 2) security-association lifetime, as a Go duration string (e.g. `1h`, `3600s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
	EspLifetime *string `json:"espLifetime,omitempty" tf:"esp_lifetime,omitempty"`

	// IKE (phase 1) Diffie-Hellman group. Only used when `profile = customized`.
	IkeDhGroup *float64 `json:"ikeDhGroup,omitempty" tf:"ike_dh_group,omitempty"`

	// IKE (phase 1) encryption. Only used when `profile = customized`.
	IkeEncryption *string `json:"ikeEncryption,omitempty" tf:"ike_encryption,omitempty"`

	// IKE (phase 1) hash. Only used when `profile = customized`.
	IkeHash *string `json:"ikeHash,omitempty" tf:"ike_hash,omitempty"`

	// IKE (phase 1) security-association lifetime, as a Go duration string (e.g. `8h`, `28800s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
	IkeLifetime *string `json:"ikeLifetime,omitempty" tf:"ike_lifetime,omitempty"`

	// The local WAN interface the tunnel binds to (e.g. `wan`, `wan2`).
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// IKE key-exchange version. One of `ikev1` or `ikev2`.
	KeyExchange *string `json:"keyExchange,omitempty" tf:"key_exchange,omitempty"`

	// The local IP used for the tunnel. Defaults to the WAN address when omitted.
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// The name of the site-to-site VPN.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The public IP address of the remote VPN gateway (peer).
	PeerIP *string `json:"peerIp,omitempty" tf:"peer_ip,omitempty"`

	// Whether Perfect Forward Secrecy is enabled.
	Pfs *bool `json:"pfs,omitempty" tf:"pfs,omitempty"`

	// The IPsec pre-shared key. Stored in state — use `pre_shared_key_wo` to avoid persisting the secret.
	PreSharedKeySecretRef *v1.SecretKeySelector `json:"preSharedKeySecretRef,omitempty" tf:"-"`

	// 11+). Used at apply time but never written to state, so it can be sourced from an ephemeral resource (e.g. a Vault secret). Mutually exclusive with `pre_shared_key`.
	PreSharedKeyWoSecretRef *v1.SecretKeySelector `json:"preSharedKeyWoSecretRef,omitempty" tf:"-"`

	// IPsec profile. One of `customized`, `azure_dynamic`, or `azure_static`. Set to `customized` to tune the IKE/ESP attributes below; the controller may derive the ESP values from the IKE ones.
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// The remote site's subnets reachable through the tunnel (CIDR).
	RemoteSubnets []*string `json:"remoteSubnets,omitempty" tf:"remote_subnets,omitempty"`

	// The route distance (administrative metric) for tunnel routes (1-255).
	RouteDistance *float64 `json:"routeDistance,omitempty" tf:"route_distance,omitempty"`

	// The name of the site to associate the VPN with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Timeouts *TimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type ToSiteVPNObservation struct {

	// Whether IPsec dynamic routing is enabled.
	DynamicRouting *bool `json:"dynamicRouting,omitempty" tf:"dynamic_routing,omitempty"`

	// Whether the tunnel is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// ESP (phase 2) Diffie-Hellman group (PFS). Only used when `profile = customized`.
	EspDhGroup *float64 `json:"espDhGroup,omitempty" tf:"esp_dh_group,omitempty"`

	// ESP (phase 2) encryption. Only used when `profile = customized`.
	EspEncryption *string `json:"espEncryption,omitempty" tf:"esp_encryption,omitempty"`

	// ESP (phase 2) hash. Only used when `profile = customized`.
	EspHash *string `json:"espHash,omitempty" tf:"esp_hash,omitempty"`

	// ESP (phase 2) security-association lifetime, as a Go duration string (e.g. `1h`, `3600s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
	EspLifetime *string `json:"espLifetime,omitempty" tf:"esp_lifetime,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IKE (phase 1) Diffie-Hellman group. Only used when `profile = customized`.
	IkeDhGroup *float64 `json:"ikeDhGroup,omitempty" tf:"ike_dh_group,omitempty"`

	// IKE (phase 1) encryption. Only used when `profile = customized`.
	IkeEncryption *string `json:"ikeEncryption,omitempty" tf:"ike_encryption,omitempty"`

	// IKE (phase 1) hash. Only used when `profile = customized`.
	IkeHash *string `json:"ikeHash,omitempty" tf:"ike_hash,omitempty"`

	// IKE (phase 1) security-association lifetime, as a Go duration string (e.g. `8h`, `28800s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
	IkeLifetime *string `json:"ikeLifetime,omitempty" tf:"ike_lifetime,omitempty"`

	// The local WAN interface the tunnel binds to (e.g. `wan`, `wan2`).
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// IKE key-exchange version. One of `ikev1` or `ikev2`.
	KeyExchange *string `json:"keyExchange,omitempty" tf:"key_exchange,omitempty"`

	// The local IP used for the tunnel. Defaults to the WAN address when omitted.
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// The name of the site-to-site VPN.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The public IP address of the remote VPN gateway (peer).
	PeerIP *string `json:"peerIp,omitempty" tf:"peer_ip,omitempty"`

	// Whether Perfect Forward Secrecy is enabled.
	Pfs *bool `json:"pfs,omitempty" tf:"pfs,omitempty"`

	// IPsec profile. One of `customized`, `azure_dynamic`, or `azure_static`. Set to `customized` to tune the IKE/ESP attributes below; the controller may derive the ESP values from the IKE ones.
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// The remote site's subnets reachable through the tunnel (CIDR).
	RemoteSubnets []*string `json:"remoteSubnets,omitempty" tf:"remote_subnets,omitempty"`

	// The route distance (administrative metric) for tunnel routes (1-255).
	RouteDistance *float64 `json:"routeDistance,omitempty" tf:"route_distance,omitempty"`

	// The name of the site to associate the VPN with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Timeouts *TimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type ToSiteVPNParameters struct {

	// Whether IPsec dynamic routing is enabled.
	// +kubebuilder:validation:Optional
	DynamicRouting *bool `json:"dynamicRouting,omitempty" tf:"dynamic_routing,omitempty"`

	// Whether the tunnel is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// ESP (phase 2) Diffie-Hellman group (PFS). Only used when `profile = customized`.
	// +kubebuilder:validation:Optional
	EspDhGroup *float64 `json:"espDhGroup,omitempty" tf:"esp_dh_group,omitempty"`

	// ESP (phase 2) encryption. Only used when `profile = customized`.
	// +kubebuilder:validation:Optional
	EspEncryption *string `json:"espEncryption,omitempty" tf:"esp_encryption,omitempty"`

	// ESP (phase 2) hash. Only used when `profile = customized`.
	// +kubebuilder:validation:Optional
	EspHash *string `json:"espHash,omitempty" tf:"esp_hash,omitempty"`

	// ESP (phase 2) security-association lifetime, as a Go duration string (e.g. `1h`, `3600s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
	// +kubebuilder:validation:Optional
	EspLifetime *string `json:"espLifetime,omitempty" tf:"esp_lifetime,omitempty"`

	// IKE (phase 1) Diffie-Hellman group. Only used when `profile = customized`.
	// +kubebuilder:validation:Optional
	IkeDhGroup *float64 `json:"ikeDhGroup,omitempty" tf:"ike_dh_group,omitempty"`

	// IKE (phase 1) encryption. Only used when `profile = customized`.
	// +kubebuilder:validation:Optional
	IkeEncryption *string `json:"ikeEncryption,omitempty" tf:"ike_encryption,omitempty"`

	// IKE (phase 1) hash. Only used when `profile = customized`.
	// +kubebuilder:validation:Optional
	IkeHash *string `json:"ikeHash,omitempty" tf:"ike_hash,omitempty"`

	// IKE (phase 1) security-association lifetime, as a Go duration string (e.g. `8h`, `28800s`). Must be a whole number of seconds between `30s` and `86400s` (24h).
	// +kubebuilder:validation:Optional
	IkeLifetime *string `json:"ikeLifetime,omitempty" tf:"ike_lifetime,omitempty"`

	// The local WAN interface the tunnel binds to (e.g. `wan`, `wan2`).
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// IKE key-exchange version. One of `ikev1` or `ikev2`.
	// +kubebuilder:validation:Optional
	KeyExchange *string `json:"keyExchange,omitempty" tf:"key_exchange,omitempty"`

	// The local IP used for the tunnel. Defaults to the WAN address when omitted.
	// +kubebuilder:validation:Optional
	LocalIP *string `json:"localIp,omitempty" tf:"local_ip,omitempty"`

	// The name of the site-to-site VPN.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The public IP address of the remote VPN gateway (peer).
	// +kubebuilder:validation:Optional
	PeerIP *string `json:"peerIp,omitempty" tf:"peer_ip,omitempty"`

	// Whether Perfect Forward Secrecy is enabled.
	// +kubebuilder:validation:Optional
	Pfs *bool `json:"pfs,omitempty" tf:"pfs,omitempty"`

	// The IPsec pre-shared key. Stored in state — use `pre_shared_key_wo` to avoid persisting the secret.
	// +kubebuilder:validation:Optional
	PreSharedKeySecretRef *v1.SecretKeySelector `json:"preSharedKeySecretRef,omitempty" tf:"-"`

	// 11+). Used at apply time but never written to state, so it can be sourced from an ephemeral resource (e.g. a Vault secret). Mutually exclusive with `pre_shared_key`.
	// +kubebuilder:validation:Optional
	PreSharedKeyWoSecretRef *v1.SecretKeySelector `json:"preSharedKeyWoSecretRef,omitempty" tf:"-"`

	// IPsec profile. One of `customized`, `azure_dynamic`, or `azure_static`. Set to `customized` to tune the IKE/ESP attributes below; the controller may derive the ESP values from the IKE ones.
	// +kubebuilder:validation:Optional
	Profile *string `json:"profile,omitempty" tf:"profile,omitempty"`

	// The remote site's subnets reachable through the tunnel (CIDR).
	// +kubebuilder:validation:Optional
	RemoteSubnets []*string `json:"remoteSubnets,omitempty" tf:"remote_subnets,omitempty"`

	// The route distance (administrative metric) for tunnel routes (1-255).
	// +kubebuilder:validation:Optional
	RouteDistance *float64 `json:"routeDistance,omitempty" tf:"route_distance,omitempty"`

	// The name of the site to associate the VPN with.
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *TimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

// ToSiteVPNSpec defines the desired state of ToSiteVPN
type ToSiteVPNSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ToSiteVPNParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ToSiteVPNInitParameters `json:"initProvider,omitempty"`
}

// ToSiteVPNStatus defines the observed state of ToSiteVPN.
type ToSiteVPNStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ToSiteVPNObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ToSiteVPN is the Schema for the ToSiteVPNs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,unifi}
type ToSiteVPN struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.peerIp) || (has(self.initProvider) && has(self.initProvider.peerIp))",message="spec.forProvider.peerIp is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.remoteSubnets) || (has(self.initProvider) && has(self.initProvider.remoteSubnets))",message="spec.forProvider.remoteSubnets is a required parameter"
	Spec   ToSiteVPNSpec   `json:"spec"`
	Status ToSiteVPNStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ToSiteVPNList contains a list of ToSiteVPNs
type ToSiteVPNList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ToSiteVPN `json:"items"`
}

// Repository type metadata.
var (
	ToSiteVPN_Kind             = "ToSiteVPN"
	ToSiteVPN_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ToSiteVPN_Kind}.String()
	ToSiteVPN_KindAPIVersion   = ToSiteVPN_Kind + "." + CRDGroupVersion.String()
	ToSiteVPN_GroupVersionKind = CRDGroupVersion.WithKind(ToSiteVPN_Kind)
)

func init() {
	SchemeBuilder.Register(&ToSiteVPN{}, &ToSiteVPNList{})
}
