// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/network/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Policy.
func (mg *Policy) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	if mg.Spec.ForProvider.Destination != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Destination.NetworkIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.Destination.NetworkIdsRefs,
			Selector:      mg.Spec.ForProvider.Destination.NetworkIdsSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Destination.NetworkIds")
		}
		mg.Spec.ForProvider.Destination.NetworkIds = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.Destination.NetworkIdsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.ForProvider.Destination != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Destination.ZoneID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Destination.ZoneIDRef,
			Selector:     mg.Spec.ForProvider.Destination.ZoneIDSelector,
			To: reference.To{
				List:    &ZoneList{},
				Managed: &Zone{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Destination.ZoneID")
		}
		mg.Spec.ForProvider.Destination.ZoneID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Destination.ZoneIDRef = rsp.ResolvedReference

	}
	if mg.Spec.ForProvider.Source != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Source.NetworkIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.Source.NetworkIdsRefs,
			Selector:      mg.Spec.ForProvider.Source.NetworkIdsSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Source.NetworkIds")
		}
		mg.Spec.ForProvider.Source.NetworkIds = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.Source.NetworkIdsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.ForProvider.Source != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Source.ZoneID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Source.ZoneIDRef,
			Selector:     mg.Spec.ForProvider.Source.ZoneIDSelector,
			To: reference.To{
				List:    &ZoneList{},
				Managed: &Zone{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Source.ZoneID")
		}
		mg.Spec.ForProvider.Source.ZoneID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Source.ZoneIDRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Destination != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Destination.NetworkIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.Destination.NetworkIdsRefs,
			Selector:      mg.Spec.InitProvider.Destination.NetworkIdsSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Destination.NetworkIds")
		}
		mg.Spec.InitProvider.Destination.NetworkIds = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.Destination.NetworkIdsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.InitProvider.Destination != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Destination.ZoneID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Destination.ZoneIDRef,
			Selector:     mg.Spec.InitProvider.Destination.ZoneIDSelector,
			To: reference.To{
				List:    &ZoneList{},
				Managed: &Zone{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Destination.ZoneID")
		}
		mg.Spec.InitProvider.Destination.ZoneID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Destination.ZoneIDRef = rsp.ResolvedReference

	}
	if mg.Spec.InitProvider.Source != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Source.NetworkIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.Source.NetworkIdsRefs,
			Selector:      mg.Spec.InitProvider.Source.NetworkIdsSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Source.NetworkIds")
		}
		mg.Spec.InitProvider.Source.NetworkIds = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.Source.NetworkIdsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.InitProvider.Source != nil {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Source.ZoneID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Source.ZoneIDRef,
			Selector:     mg.Spec.InitProvider.Source.ZoneIDSelector,
			To: reference.To{
				List:    &ZoneList{},
				Managed: &Zone{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Source.ZoneID")
		}
		mg.Spec.InitProvider.Source.ZoneID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Source.ZoneIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this Rule.
func (mg *Rule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.DstFirewallGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.DstFirewallGroupIdsRefs,
		Selector:      mg.Spec.ForProvider.DstFirewallGroupIdsSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DstFirewallGroupIds")
	}
	mg.Spec.ForProvider.DstFirewallGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.DstFirewallGroupIdsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DstNetworkID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DstNetworkIDRef,
		Selector:     mg.Spec.ForProvider.DstNetworkIDSelector,
		To: reference.To{
			List:    &v1alpha1.NetworkList{},
			Managed: &v1alpha1.Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DstNetworkID")
	}
	mg.Spec.ForProvider.DstNetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DstNetworkIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.SrcFirewallGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.SrcFirewallGroupIdsRefs,
		Selector:      mg.Spec.ForProvider.SrcFirewallGroupIdsSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SrcFirewallGroupIds")
	}
	mg.Spec.ForProvider.SrcFirewallGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.SrcFirewallGroupIdsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SrcNetworkID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SrcNetworkIDRef,
		Selector:     mg.Spec.ForProvider.SrcNetworkIDSelector,
		To: reference.To{
			List:    &v1alpha1.NetworkList{},
			Managed: &v1alpha1.Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SrcNetworkID")
	}
	mg.Spec.ForProvider.SrcNetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SrcNetworkIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.DstFirewallGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.DstFirewallGroupIdsRefs,
		Selector:      mg.Spec.InitProvider.DstFirewallGroupIdsSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DstFirewallGroupIds")
	}
	mg.Spec.InitProvider.DstFirewallGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.DstFirewallGroupIdsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DstNetworkID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DstNetworkIDRef,
		Selector:     mg.Spec.InitProvider.DstNetworkIDSelector,
		To: reference.To{
			List:    &v1alpha1.NetworkList{},
			Managed: &v1alpha1.Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DstNetworkID")
	}
	mg.Spec.InitProvider.DstNetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DstNetworkIDRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.SrcFirewallGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.SrcFirewallGroupIdsRefs,
		Selector:      mg.Spec.InitProvider.SrcFirewallGroupIdsSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SrcFirewallGroupIds")
	}
	mg.Spec.InitProvider.SrcFirewallGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.SrcFirewallGroupIdsRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SrcNetworkID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SrcNetworkIDRef,
		Selector:     mg.Spec.InitProvider.SrcNetworkIDSelector,
		To: reference.To{
			List:    &v1alpha1.NetworkList{},
			Managed: &v1alpha1.Network{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SrcNetworkID")
	}
	mg.Spec.InitProvider.SrcNetworkID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SrcNetworkIDRef = rsp.ResolvedReference

	return nil
}
