// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	v1alpha1 "github.com/devantler-tech/provider-upjet-unifi/apis/cluster/network/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Setting.
func (mg *Setting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	if mg.Spec.ForProvider.IgmpSnooping != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.IgmpSnooping.NetworkIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.ForProvider.IgmpSnooping.NetworkIdsRefs,
			Selector:      mg.Spec.ForProvider.IgmpSnooping.NetworkIdsSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.IgmpSnooping.NetworkIds")
		}
		mg.Spec.ForProvider.IgmpSnooping.NetworkIds = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.ForProvider.IgmpSnooping.NetworkIdsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.ForProvider.Ips != nil {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.Ips.Honeypot); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Ips.Honeypot[i4].NetworkID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.Ips.Honeypot[i4].NetworkIDRef,
				Selector:     mg.Spec.ForProvider.Ips.Honeypot[i4].NetworkIDSelector,
				To: reference.To{
					List:    &v1alpha1.NetworkList{},
					Managed: &v1alpha1.Network{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.Ips.Honeypot[i4].NetworkID")
			}
			mg.Spec.ForProvider.Ips.Honeypot[i4].NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.Ips.Honeypot[i4].NetworkIDRef = rsp.ResolvedReference

		}
	}
	if mg.Spec.InitProvider.IgmpSnooping != nil {
		mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
			CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.IgmpSnooping.NetworkIds),
			Extract:       reference.ExternalName(),
			Namespace:     mg.GetNamespace(),
			References:    mg.Spec.InitProvider.IgmpSnooping.NetworkIdsRefs,
			Selector:      mg.Spec.InitProvider.IgmpSnooping.NetworkIdsSelector,
			To: reference.To{
				List:    &v1alpha1.NetworkList{},
				Managed: &v1alpha1.Network{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.IgmpSnooping.NetworkIds")
		}
		mg.Spec.InitProvider.IgmpSnooping.NetworkIds = reference.ToPtrValues(mrsp.ResolvedValues)
		mg.Spec.InitProvider.IgmpSnooping.NetworkIdsRefs = mrsp.ResolvedReferences

	}
	if mg.Spec.InitProvider.Ips != nil {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.Ips.Honeypot); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Ips.Honeypot[i4].NetworkID),
				Extract:      reference.ExternalName(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.Ips.Honeypot[i4].NetworkIDRef,
				Selector:     mg.Spec.InitProvider.Ips.Honeypot[i4].NetworkIDSelector,
				To: reference.To{
					List:    &v1alpha1.NetworkList{},
					Managed: &v1alpha1.Network{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.Ips.Honeypot[i4].NetworkID")
			}
			mg.Spec.InitProvider.Ips.Honeypot[i4].NetworkID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.Ips.Honeypot[i4].NetworkIDRef = rsp.ResolvedReference

		}
	}

	return nil
}
