// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ConfigNetworkInitParameters struct {

	// Enable network bonding.
	BondingEnabled *bool `json:"bondingEnabled,omitempty" tf:"bonding_enabled,omitempty"`

	// Primary DNS server.
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Secondary DNS server.
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// DNS suffix.
	Dnssuffix *string `json:"dnssuffix,omitempty" tf:"dnssuffix,omitempty"`

	// Gateway address (for static configuration).
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// IP address (for static configuration).
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Network mask (for static configuration).
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// Network configuration type (dhcp or static).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConfigNetworkObservation struct {

	// Enable network bonding.
	BondingEnabled *bool `json:"bondingEnabled,omitempty" tf:"bonding_enabled,omitempty"`

	// Primary DNS server.
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Secondary DNS server.
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// DNS suffix.
	Dnssuffix *string `json:"dnssuffix,omitempty" tf:"dnssuffix,omitempty"`

	// Gateway address (for static configuration).
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// IP address (for static configuration).
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Network mask (for static configuration).
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// Network configuration type (dhcp or static).
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ConfigNetworkParameters struct {

	// Enable network bonding.
	// +kubebuilder:validation:Optional
	BondingEnabled *bool `json:"bondingEnabled,omitempty" tf:"bonding_enabled,omitempty"`

	// Primary DNS server.
	// +kubebuilder:validation:Optional
	Dns1 *string `json:"dns1,omitempty" tf:"dns1,omitempty"`

	// Secondary DNS server.
	// +kubebuilder:validation:Optional
	Dns2 *string `json:"dns2,omitempty" tf:"dns2,omitempty"`

	// DNS suffix.
	// +kubebuilder:validation:Optional
	Dnssuffix *string `json:"dnssuffix,omitempty" tf:"dnssuffix,omitempty"`

	// Gateway address (for static configuration).
	// +kubebuilder:validation:Optional
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// IP address (for static configuration).
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Network mask (for static configuration).
	// +kubebuilder:validation:Optional
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// Network configuration type (dhcp or static).
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DeviceInitParameters struct {

	// Specifies whether this resource should tell the controller to adopt the device on create.
	AllowAdoption *bool `json:"allowAdoption,omitempty" tf:"allow_adoption,omitempty"`

	// Band steering mode; valid values are `off`, `equal`, and `prefer_5g`.
	BandsteeringMode *string `json:"bandsteeringMode,omitempty" tf:"bandsteering_mode,omitempty"`

	ConfigNetwork *ConfigNetworkInitParameters `json:"configNetwork,omitempty" tf:"config_network,omitempty"`

	// Specifies whether this device should be disabled.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Enable flow control.
	FlowctrlEnabled *bool `json:"flowctrlEnabled,omitempty" tf:"flowctrl_enabled,omitempty"`

	// Specifies whether this resource should tell the controller to forget the device on destroy.
	ForgetOnDestroy *bool `json:"forgetOnDestroy,omitempty" tf:"forget_on_destroy,omitempty"`

	// Enable jumbo frames.
	JumboframeEnabled *bool `json:"jumboframeEnabled,omitempty" tf:"jumboframe_enabled,omitempty"`

	// LCM brightness (1-100).
	LcmBrightness *float64 `json:"lcmBrightness,omitempty" tf:"lcm_brightness,omitempty"`

	// Override LCM brightness.
	LcmBrightnessOverride *bool `json:"lcmBrightnessOverride,omitempty" tf:"lcm_brightness_override,omitempty"`

	// LCM idle timeout, as a Go duration string (e.g. `10m`, `600s`).
	LcmIdleTimeout *string `json:"lcmIdleTimeout,omitempty" tf:"lcm_idle_timeout,omitempty"`

	// Override LCM idle timeout.
	LcmIdleTimeoutOverride *bool `json:"lcmIdleTimeoutOverride,omitempty" tf:"lcm_idle_timeout_override,omitempty"`

	// LCM night mode begin time (HH:MM format).
	LcmNightModeBegins *string `json:"lcmNightModeBegins,omitempty" tf:"lcm_night_mode_begins,omitempty"`

	// LCM night mode end time (HH:MM format).
	LcmNightModeEnds *string `json:"lcmNightModeEnds,omitempty" tf:"lcm_night_mode_ends,omitempty"`

	// LED override setting; valid values are `default`, `on`, and `off`.
	LedOverride *string `json:"ledOverride,omitempty" tf:"led_override,omitempty"`

	// LED color override (hex color code).
	LedOverrideColor *string `json:"ledOverrideColor,omitempty" tf:"led_override_color,omitempty"`

	// LED brightness (0-100).
	LedOverrideColorBrightness *float64 `json:"ledOverrideColorBrightness,omitempty" tf:"led_override_color_brightness,omitempty"`

	// Specifies whether the device is locked.
	Locked *bool `json:"locked,omitempty" tf:"locked,omitempty"`

	// The MAC address of the device. This can be specified so that the provider can take control of a device (since devices are created through adoption).
	Mac *string `json:"mac,omitempty" tf:"mac,omitempty"`

	// Management network ID. The network this device uses for its own management traffic (the UI's Network Override). When set, the device tags its management onto this network's VLAN, so that VLAN must already be tagged on the device's upstream switch port(s) before this attribute is applied. Otherwise the device loses its management path, drops off, and the apply fails with an inconsistent-result error. Apply in two steps: tag the VLAN on the uplink (a port_override tagged_networkconf_ids entry) first, then set mgmt_network_id. Leave unset to manage on the uplink's native (untagged) network.
	MgmtNetworkID *string `json:"mgmtNetworkId,omitempty" tf:"mgmt_network_id,omitempty"`

	// The name of the device.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Outdoor mode override; valid values are `default`, `on`, and `off`.
	OutdoorModeOverride *string `json:"outdoorModeOverride,omitempty" tf:"outdoor_mode_override,omitempty"`

	// Enable outlet control.
	OutletEnabled *bool `json:"outletEnabled,omitempty" tf:"outlet_enabled,omitempty"`

	OutletOverrides []OutletOverridesInitParameters `json:"outletOverrides,omitempty" tf:"outlet_overrides,omitempty"`

	// PoE mode; valid values are `auto`, `pasv24`, `passthrough`, and `off`.
	PoeMode *string `json:"poeMode,omitempty" tf:"poe_mode,omitempty"`

	// Per-port settings overrides, applied only to the ports you declare. Ports without a `port_override` block keep their existing controller-side configuration — the provider merges your declared ports (by `index`) into the device's current overrides rather than replacing the whole set. Removing a block stops managing that port but does not reset it; clear a port by overriding it back to the defaults instead.
	PortOverride []PortOverrideInitParameters `json:"portOverride,omitempty" tf:"port_override,omitempty"`

	RadioTable []RadioTableInitParameters `json:"radioTable,omitempty" tf:"radio_table,omitempty"`

	// The name of the site to associate the device with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// STP priority.
	StpPriority *float64 `json:"stpPriority,omitempty" tf:"stp_priority,omitempty"`

	// STP version; valid values are `stp`, `rstp`, and `disabled`.
	StpVersion *string `json:"stpVersion,omitempty" tf:"stp_version,omitempty"`

	// Enable VLAN support on the switch.
	SwitchVlanEnabled *bool `json:"switchVlanEnabled,omitempty" tf:"switch_vlan_enabled,omitempty"`

	Timeouts *DeviceTimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// Volume level (0-100).
	Volume *float64 `json:"volume,omitempty" tf:"volume,omitempty"`

	// Baresip password.
	XBaresipPasswordSecretRef *v1.SecretKeySelector `json:"xBaresipPasswordSecretRef,omitempty" tf:"-"`
}

type DeviceObservation struct {

	// Whether the device is adopted.
	Adopted *bool `json:"adopted,omitempty" tf:"adopted,omitempty"`

	// Specifies whether this resource should tell the controller to adopt the device on create.
	AllowAdoption *bool `json:"allowAdoption,omitempty" tf:"allow_adoption,omitempty"`

	// Band steering mode; valid values are `off`, `equal`, and `prefer_5g`.
	BandsteeringMode *string `json:"bandsteeringMode,omitempty" tf:"bandsteering_mode,omitempty"`

	ConfigNetwork *ConfigNetworkObservation `json:"configNetwork,omitempty" tf:"config_network,omitempty"`

	// Specifies whether this device should be disabled.
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Enable flow control.
	FlowctrlEnabled *bool `json:"flowctrlEnabled,omitempty" tf:"flowctrl_enabled,omitempty"`

	// Specifies whether this resource should tell the controller to forget the device on destroy.
	ForgetOnDestroy *bool `json:"forgetOnDestroy,omitempty" tf:"forget_on_destroy,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Enable jumbo frames.
	JumboframeEnabled *bool `json:"jumboframeEnabled,omitempty" tf:"jumboframe_enabled,omitempty"`

	// LCM brightness (1-100).
	LcmBrightness *float64 `json:"lcmBrightness,omitempty" tf:"lcm_brightness,omitempty"`

	// Override LCM brightness.
	LcmBrightnessOverride *bool `json:"lcmBrightnessOverride,omitempty" tf:"lcm_brightness_override,omitempty"`

	// LCM idle timeout, as a Go duration string (e.g. `10m`, `600s`).
	LcmIdleTimeout *string `json:"lcmIdleTimeout,omitempty" tf:"lcm_idle_timeout,omitempty"`

	// Override LCM idle timeout.
	LcmIdleTimeoutOverride *bool `json:"lcmIdleTimeoutOverride,omitempty" tf:"lcm_idle_timeout_override,omitempty"`

	// LCM night mode begin time (HH:MM format).
	LcmNightModeBegins *string `json:"lcmNightModeBegins,omitempty" tf:"lcm_night_mode_begins,omitempty"`

	// LCM night mode end time (HH:MM format).
	LcmNightModeEnds *string `json:"lcmNightModeEnds,omitempty" tf:"lcm_night_mode_ends,omitempty"`

	// LED override setting; valid values are `default`, `on`, and `off`.
	LedOverride *string `json:"ledOverride,omitempty" tf:"led_override,omitempty"`

	// LED color override (hex color code).
	LedOverrideColor *string `json:"ledOverrideColor,omitempty" tf:"led_override_color,omitempty"`

	// LED brightness (0-100).
	LedOverrideColorBrightness *float64 `json:"ledOverrideColorBrightness,omitempty" tf:"led_override_color_brightness,omitempty"`

	// Specifies whether the device is locked.
	Locked *bool `json:"locked,omitempty" tf:"locked,omitempty"`

	// The MAC address of the device. This can be specified so that the provider can take control of a device (since devices are created through adoption).
	Mac *string `json:"mac,omitempty" tf:"mac,omitempty"`

	// Management network ID. The network this device uses for its own management traffic (the UI's Network Override). When set, the device tags its management onto this network's VLAN, so that VLAN must already be tagged on the device's upstream switch port(s) before this attribute is applied. Otherwise the device loses its management path, drops off, and the apply fails with an inconsistent-result error. Apply in two steps: tag the VLAN on the uplink (a port_override tagged_networkconf_ids entry) first, then set mgmt_network_id. Leave unset to manage on the uplink's native (untagged) network.
	MgmtNetworkID *string `json:"mgmtNetworkId,omitempty" tf:"mgmt_network_id,omitempty"`

	// Device model.
	Model *string `json:"model,omitempty" tf:"model,omitempty"`

	// The name of the device.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Outdoor mode override; valid values are `default`, `on`, and `off`.
	OutdoorModeOverride *string `json:"outdoorModeOverride,omitempty" tf:"outdoor_mode_override,omitempty"`

	// Enable outlet control.
	OutletEnabled *bool `json:"outletEnabled,omitempty" tf:"outlet_enabled,omitempty"`

	OutletOverrides []OutletOverridesObservation `json:"outletOverrides,omitempty" tf:"outlet_overrides,omitempty"`

	// PoE mode; valid values are `auto`, `pasv24`, `passthrough`, and `off`.
	PoeMode *string `json:"poeMode,omitempty" tf:"poe_mode,omitempty"`

	// Per-port settings overrides, applied only to the ports you declare. Ports without a `port_override` block keep their existing controller-side configuration — the provider merges your declared ports (by `index`) into the device's current overrides rather than replacing the whole set. Removing a block stops managing that port but does not reset it; clear a port by overriding it back to the defaults instead.
	PortOverride []PortOverrideObservation `json:"portOverride,omitempty" tf:"port_override,omitempty"`

	RadioTable []RadioTableObservation `json:"radioTable,omitempty" tf:"radio_table,omitempty"`

	// The name of the site to associate the device with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// Device state.
	State *float64 `json:"state,omitempty" tf:"state,omitempty"`

	// STP priority.
	StpPriority *float64 `json:"stpPriority,omitempty" tf:"stp_priority,omitempty"`

	// STP version; valid values are `stp`, `rstp`, and `disabled`.
	StpVersion *string `json:"stpVersion,omitempty" tf:"stp_version,omitempty"`

	// Enable VLAN support on the switch.
	SwitchVlanEnabled *bool `json:"switchVlanEnabled,omitempty" tf:"switch_vlan_enabled,omitempty"`

	Timeouts *DeviceTimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// Device type.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Volume level (0-100).
	Volume *float64 `json:"volume,omitempty" tf:"volume,omitempty"`
}

type DeviceParameters struct {

	// Specifies whether this resource should tell the controller to adopt the device on create.
	// +kubebuilder:validation:Optional
	AllowAdoption *bool `json:"allowAdoption,omitempty" tf:"allow_adoption,omitempty"`

	// Band steering mode; valid values are `off`, `equal`, and `prefer_5g`.
	// +kubebuilder:validation:Optional
	BandsteeringMode *string `json:"bandsteeringMode,omitempty" tf:"bandsteering_mode,omitempty"`

	// +kubebuilder:validation:Optional
	ConfigNetwork *ConfigNetworkParameters `json:"configNetwork,omitempty" tf:"config_network,omitempty"`

	// Specifies whether this device should be disabled.
	// +kubebuilder:validation:Optional
	Disabled *bool `json:"disabled,omitempty" tf:"disabled,omitempty"`

	// Enable flow control.
	// +kubebuilder:validation:Optional
	FlowctrlEnabled *bool `json:"flowctrlEnabled,omitempty" tf:"flowctrl_enabled,omitempty"`

	// Specifies whether this resource should tell the controller to forget the device on destroy.
	// +kubebuilder:validation:Optional
	ForgetOnDestroy *bool `json:"forgetOnDestroy,omitempty" tf:"forget_on_destroy,omitempty"`

	// Enable jumbo frames.
	// +kubebuilder:validation:Optional
	JumboframeEnabled *bool `json:"jumboframeEnabled,omitempty" tf:"jumboframe_enabled,omitempty"`

	// LCM brightness (1-100).
	// +kubebuilder:validation:Optional
	LcmBrightness *float64 `json:"lcmBrightness,omitempty" tf:"lcm_brightness,omitempty"`

	// Override LCM brightness.
	// +kubebuilder:validation:Optional
	LcmBrightnessOverride *bool `json:"lcmBrightnessOverride,omitempty" tf:"lcm_brightness_override,omitempty"`

	// LCM idle timeout, as a Go duration string (e.g. `10m`, `600s`).
	// +kubebuilder:validation:Optional
	LcmIdleTimeout *string `json:"lcmIdleTimeout,omitempty" tf:"lcm_idle_timeout,omitempty"`

	// Override LCM idle timeout.
	// +kubebuilder:validation:Optional
	LcmIdleTimeoutOverride *bool `json:"lcmIdleTimeoutOverride,omitempty" tf:"lcm_idle_timeout_override,omitempty"`

	// LCM night mode begin time (HH:MM format).
	// +kubebuilder:validation:Optional
	LcmNightModeBegins *string `json:"lcmNightModeBegins,omitempty" tf:"lcm_night_mode_begins,omitempty"`

	// LCM night mode end time (HH:MM format).
	// +kubebuilder:validation:Optional
	LcmNightModeEnds *string `json:"lcmNightModeEnds,omitempty" tf:"lcm_night_mode_ends,omitempty"`

	// LED override setting; valid values are `default`, `on`, and `off`.
	// +kubebuilder:validation:Optional
	LedOverride *string `json:"ledOverride,omitempty" tf:"led_override,omitempty"`

	// LED color override (hex color code).
	// +kubebuilder:validation:Optional
	LedOverrideColor *string `json:"ledOverrideColor,omitempty" tf:"led_override_color,omitempty"`

	// LED brightness (0-100).
	// +kubebuilder:validation:Optional
	LedOverrideColorBrightness *float64 `json:"ledOverrideColorBrightness,omitempty" tf:"led_override_color_brightness,omitempty"`

	// Specifies whether the device is locked.
	// +kubebuilder:validation:Optional
	Locked *bool `json:"locked,omitempty" tf:"locked,omitempty"`

	// The MAC address of the device. This can be specified so that the provider can take control of a device (since devices are created through adoption).
	// +kubebuilder:validation:Optional
	Mac *string `json:"mac,omitempty" tf:"mac,omitempty"`

	// Management network ID. The network this device uses for its own management traffic (the UI's Network Override). When set, the device tags its management onto this network's VLAN, so that VLAN must already be tagged on the device's upstream switch port(s) before this attribute is applied. Otherwise the device loses its management path, drops off, and the apply fails with an inconsistent-result error. Apply in two steps: tag the VLAN on the uplink (a port_override tagged_networkconf_ids entry) first, then set mgmt_network_id. Leave unset to manage on the uplink's native (untagged) network.
	// +kubebuilder:validation:Optional
	MgmtNetworkID *string `json:"mgmtNetworkId,omitempty" tf:"mgmt_network_id,omitempty"`

	// The name of the device.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Outdoor mode override; valid values are `default`, `on`, and `off`.
	// +kubebuilder:validation:Optional
	OutdoorModeOverride *string `json:"outdoorModeOverride,omitempty" tf:"outdoor_mode_override,omitempty"`

	// Enable outlet control.
	// +kubebuilder:validation:Optional
	OutletEnabled *bool `json:"outletEnabled,omitempty" tf:"outlet_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	OutletOverrides []OutletOverridesParameters `json:"outletOverrides,omitempty" tf:"outlet_overrides,omitempty"`

	// PoE mode; valid values are `auto`, `pasv24`, `passthrough`, and `off`.
	// +kubebuilder:validation:Optional
	PoeMode *string `json:"poeMode,omitempty" tf:"poe_mode,omitempty"`

	// Per-port settings overrides, applied only to the ports you declare. Ports without a `port_override` block keep their existing controller-side configuration — the provider merges your declared ports (by `index`) into the device's current overrides rather than replacing the whole set. Removing a block stops managing that port but does not reset it; clear a port by overriding it back to the defaults instead.
	// +kubebuilder:validation:Optional
	PortOverride []PortOverrideParameters `json:"portOverride,omitempty" tf:"port_override,omitempty"`

	// +kubebuilder:validation:Optional
	RadioTable []RadioTableParameters `json:"radioTable,omitempty" tf:"radio_table,omitempty"`

	// The name of the site to associate the device with.
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// STP priority.
	// +kubebuilder:validation:Optional
	StpPriority *float64 `json:"stpPriority,omitempty" tf:"stp_priority,omitempty"`

	// STP version; valid values are `stp`, `rstp`, and `disabled`.
	// +kubebuilder:validation:Optional
	StpVersion *string `json:"stpVersion,omitempty" tf:"stp_version,omitempty"`

	// Enable VLAN support on the switch.
	// +kubebuilder:validation:Optional
	SwitchVlanEnabled *bool `json:"switchVlanEnabled,omitempty" tf:"switch_vlan_enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *DeviceTimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// Volume level (0-100).
	// +kubebuilder:validation:Optional
	Volume *float64 `json:"volume,omitempty" tf:"volume,omitempty"`

	// Baresip password.
	// +kubebuilder:validation:Optional
	XBaresipPasswordSecretRef *v1.SecretKeySelector `json:"xBaresipPasswordSecretRef,omitempty" tf:"-"`
}

type DeviceTimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type DeviceTimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type DeviceTimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type OutletOverridesInitParameters struct {

	// Enable power cycle.
	CycleEnabled *bool `json:"cycleEnabled,omitempty" tf:"cycle_enabled,omitempty"`

	// Outlet index.
	Index *float64 `json:"index,omitempty" tf:"index,omitempty"`

	// Outlet name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Relay state (on/off).
	RelayState *bool `json:"relayState,omitempty" tf:"relay_state,omitempty"`
}

type OutletOverridesObservation struct {

	// Enable power cycle.
	CycleEnabled *bool `json:"cycleEnabled,omitempty" tf:"cycle_enabled,omitempty"`

	// Outlet index.
	Index *float64 `json:"index,omitempty" tf:"index,omitempty"`

	// Outlet name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Relay state (on/off).
	RelayState *bool `json:"relayState,omitempty" tf:"relay_state,omitempty"`
}

type OutletOverridesParameters struct {

	// Enable power cycle.
	// +kubebuilder:validation:Optional
	CycleEnabled *bool `json:"cycleEnabled,omitempty" tf:"cycle_enabled,omitempty"`

	// Outlet index.
	// +kubebuilder:validation:Optional
	Index *float64 `json:"index" tf:"index,omitempty"`

	// Outlet name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Relay state (on/off).
	// +kubebuilder:validation:Optional
	RelayState *bool `json:"relayState,omitempty" tf:"relay_state,omitempty"`
}

type PortOverrideInitParameters struct {

	// Port indices that make up this link-aggregation (LAG) group. Only takes effect when `op_mode` is `aggregate` on this port.
	AggregateMembers []*float64 `json:"aggregateMembers,omitempty" tf:"aggregate_members,omitempty"`

	// Enable auto-negotiation for port speed.
	Autoneg *bool `json:"autoneg,omitempty" tf:"autoneg,omitempty"`

	// 802.1X control mode.
	Dot1XCtrl *string `json:"dot1xCtrl,omitempty" tf:"dot1x_ctrl,omitempty"`

	// 802.1X idle timeout, as a Go duration string (e.g. `5m`, `300s`).
	Dot1XIdleTimeout *string `json:"dot1xIdleTimeout,omitempty" tf:"dot1x_idle_timeout,omitempty"`

	// Egress rate limit in kbps.
	EgressRateLimitKbps *float64 `json:"egressRateLimitKbps,omitempty" tf:"egress_rate_limit_kbps,omitempty"`

	// Enable egress rate limiting.
	EgressRateLimitKbpsEnabled *bool `json:"egressRateLimitKbpsEnabled,omitempty" tf:"egress_rate_limit_kbps_enabled,omitempty"`

	// List of network IDs to exclude from this port.
	ExcludedNetworkconfIds []*string `json:"excludedNetworkconfIds,omitempty" tf:"excluded_networkconf_ids,omitempty"`

	// Forward Error Correction mode.
	FecMode *string `json:"fecMode,omitempty" tf:"fec_mode,omitempty"`

	// Enable flow control.
	FlowControlEnabled *bool `json:"flowControlEnabled,omitempty" tf:"flow_control_enabled,omitempty"`

	// Forwarding mode.
	Forward *string `json:"forward,omitempty" tf:"forward,omitempty"`

	// Enable full duplex mode.
	FullDuplex *bool `json:"fullDuplex,omitempty" tf:"full_duplex,omitempty"`

	// Switch port index.
	Index *float64 `json:"index,omitempty" tf:"index,omitempty"`

	// Enable port isolation.
	Isolation *bool `json:"isolation,omitempty" tf:"isolation,omitempty"`

	// Enable LLDP-MED.
	LldpmedEnabled *bool `json:"lldpmedEnabled,omitempty" tf:"lldpmed_enabled,omitempty"`

	// Enable LLDP-MED notifications.
	LldpmedNotifyEnabled *bool `json:"lldpmedNotifyEnabled,omitempty" tf:"lldpmed_notify_enabled,omitempty"`

	// Mirror port index.
	MirrorPortIdx *float64 `json:"mirrorPortIdx,omitempty" tf:"mirror_port_idx,omitempty"`

	// List of network IDs for multicast router.
	MulticastRouterNetworkconfIds []*string `json:"multicastRouterNetworkconfIds,omitempty" tf:"multicast_router_networkconf_ids,omitempty"`

	// Human-readable name of the port.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Native network ID (VLAN).
	NativeNetworkconfID *string `json:"nativeNetworkconfId,omitempty" tf:"native_networkconf_id,omitempty"`

	// Operating mode of the port: `switch` (default), `mirror`, or `aggregate`. Set `aggregate` on the lead port of an SFP+/link-aggregation (LAG) group and list the member ports in `aggregate_members`. Only written when not `switch`, as gateway devices (UDM) reject op_mode on update.
	OpMode *string `json:"opMode,omitempty" tf:"op_mode,omitempty"`

	// PoE mode of the port; valid values are `auto`, `pasv24`, `passthrough`, and `off`.
	PoeMode *string `json:"poeMode,omitempty" tf:"poe_mode,omitempty"`

	// Enable port keepalive.
	PortKeepaliveEnabled *bool `json:"portKeepaliveEnabled,omitempty" tf:"port_keepalive_enabled,omitempty"`

	// ID of the Port Profile used on this port.
	PortProfileID *string `json:"portProfileId,omitempty" tf:"port_profile_id,omitempty"`

	// Enable port security.
	PortSecurityEnabled *bool `json:"portSecurityEnabled,omitempty" tf:"port_security_enabled,omitempty"`

	// List of MAC addresses allowed when port security is enabled.
	PortSecurityMacAddress []*string `json:"portSecurityMacAddress,omitempty" tf:"port_security_mac_address,omitempty"`

	// Priority queue 1 level.
	PriorityQueue1Level *float64 `json:"priorityQueue1Level,omitempty" tf:"priority_queue1_level,omitempty"`

	// Priority queue 2 level.
	PriorityQueue2Level *float64 `json:"priorityQueue2Level,omitempty" tf:"priority_queue2_level,omitempty"`

	// Priority queue 3 level.
	PriorityQueue3Level *float64 `json:"priorityQueue3Level,omitempty" tf:"priority_queue3_level,omitempty"`

	// Priority queue 4 level.
	PriorityQueue4Level *float64 `json:"priorityQueue4Level,omitempty" tf:"priority_queue4_level,omitempty"`

	// Setting preference.
	SettingPreference *string `json:"settingPreference,omitempty" tf:"setting_preference,omitempty"`

	// Port speed in Mbps.
	Speed *float64 `json:"speed,omitempty" tf:"speed,omitempty"`

	// Enable broadcast storm control.
	StormctrlBcastEnabled *bool `json:"stormctrlBcastEnabled,omitempty" tf:"stormctrl_bcast_enabled,omitempty"`

	// Broadcast storm control level.
	StormctrlBcastLevel *float64 `json:"stormctrlBcastLevel,omitempty" tf:"stormctrl_bcast_level,omitempty"`

	// Broadcast storm control rate.
	StormctrlBcastRate *float64 `json:"stormctrlBcastRate,omitempty" tf:"stormctrl_bcast_rate,omitempty"`

	// Enable multicast storm control.
	StormctrlMcastEnabled *bool `json:"stormctrlMcastEnabled,omitempty" tf:"stormctrl_mcast_enabled,omitempty"`

	// Multicast storm control level.
	StormctrlMcastLevel *float64 `json:"stormctrlMcastLevel,omitempty" tf:"stormctrl_mcast_level,omitempty"`

	// Multicast storm control rate.
	StormctrlMcastRate *float64 `json:"stormctrlMcastRate,omitempty" tf:"stormctrl_mcast_rate,omitempty"`

	// Storm control type.
	StormctrlType *string `json:"stormctrlType,omitempty" tf:"stormctrl_type,omitempty"`

	// Enable unicast storm control.
	StormctrlUcastEnabled *bool `json:"stormctrlUcastEnabled,omitempty" tf:"stormctrl_ucast_enabled,omitempty"`

	// Unicast storm control level.
	StormctrlUcastLevel *float64 `json:"stormctrlUcastLevel,omitempty" tf:"stormctrl_ucast_level,omitempty"`

	// Unicast storm control rate.
	StormctrlUcastRate *float64 `json:"stormctrlUcastRate,omitempty" tf:"stormctrl_ucast_rate,omitempty"`

	// STP port mode.
	StpPortMode *bool `json:"stpPortMode,omitempty" tf:"stp_port_mode,omitempty"`

	// List of network IDs to tag on this port.
	TaggedNetworkconfIds []*string `json:"taggedNetworkconfIds,omitempty" tf:"tagged_networkconf_ids,omitempty"`

	// Tagged VLAN management.
	TaggedVlanMgmt *string `json:"taggedVlanMgmt,omitempty" tf:"tagged_vlan_mgmt,omitempty"`

	// Voice network ID.
	VoiceNetworkconfID *string `json:"voiceNetworkconfId,omitempty" tf:"voice_networkconf_id,omitempty"`
}

type PortOverrideObservation struct {

	// Port indices that make up this link-aggregation (LAG) group. Only takes effect when `op_mode` is `aggregate` on this port.
	AggregateMembers []*float64 `json:"aggregateMembers,omitempty" tf:"aggregate_members,omitempty"`

	// Enable auto-negotiation for port speed.
	Autoneg *bool `json:"autoneg,omitempty" tf:"autoneg,omitempty"`

	// 802.1X control mode.
	Dot1XCtrl *string `json:"dot1xCtrl,omitempty" tf:"dot1x_ctrl,omitempty"`

	// 802.1X idle timeout, as a Go duration string (e.g. `5m`, `300s`).
	Dot1XIdleTimeout *string `json:"dot1xIdleTimeout,omitempty" tf:"dot1x_idle_timeout,omitempty"`

	// Egress rate limit in kbps.
	EgressRateLimitKbps *float64 `json:"egressRateLimitKbps,omitempty" tf:"egress_rate_limit_kbps,omitempty"`

	// Enable egress rate limiting.
	EgressRateLimitKbpsEnabled *bool `json:"egressRateLimitKbpsEnabled,omitempty" tf:"egress_rate_limit_kbps_enabled,omitempty"`

	// List of network IDs to exclude from this port.
	ExcludedNetworkconfIds []*string `json:"excludedNetworkconfIds,omitempty" tf:"excluded_networkconf_ids,omitempty"`

	// Forward Error Correction mode.
	FecMode *string `json:"fecMode,omitempty" tf:"fec_mode,omitempty"`

	// Enable flow control.
	FlowControlEnabled *bool `json:"flowControlEnabled,omitempty" tf:"flow_control_enabled,omitempty"`

	// Forwarding mode.
	Forward *string `json:"forward,omitempty" tf:"forward,omitempty"`

	// Enable full duplex mode.
	FullDuplex *bool `json:"fullDuplex,omitempty" tf:"full_duplex,omitempty"`

	// Switch port index.
	Index *float64 `json:"index,omitempty" tf:"index,omitempty"`

	// Enable port isolation.
	Isolation *bool `json:"isolation,omitempty" tf:"isolation,omitempty"`

	// Enable LLDP-MED.
	LldpmedEnabled *bool `json:"lldpmedEnabled,omitempty" tf:"lldpmed_enabled,omitempty"`

	// Enable LLDP-MED notifications.
	LldpmedNotifyEnabled *bool `json:"lldpmedNotifyEnabled,omitempty" tf:"lldpmed_notify_enabled,omitempty"`

	// Mirror port index.
	MirrorPortIdx *float64 `json:"mirrorPortIdx,omitempty" tf:"mirror_port_idx,omitempty"`

	// List of network IDs for multicast router.
	MulticastRouterNetworkconfIds []*string `json:"multicastRouterNetworkconfIds,omitempty" tf:"multicast_router_networkconf_ids,omitempty"`

	// Human-readable name of the port.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Native network ID (VLAN).
	NativeNetworkconfID *string `json:"nativeNetworkconfId,omitempty" tf:"native_networkconf_id,omitempty"`

	// Operating mode of the port: `switch` (default), `mirror`, or `aggregate`. Set `aggregate` on the lead port of an SFP+/link-aggregation (LAG) group and list the member ports in `aggregate_members`. Only written when not `switch`, as gateway devices (UDM) reject op_mode on update.
	OpMode *string `json:"opMode,omitempty" tf:"op_mode,omitempty"`

	// PoE mode of the port; valid values are `auto`, `pasv24`, `passthrough`, and `off`.
	PoeMode *string `json:"poeMode,omitempty" tf:"poe_mode,omitempty"`

	// Enable port keepalive.
	PortKeepaliveEnabled *bool `json:"portKeepaliveEnabled,omitempty" tf:"port_keepalive_enabled,omitempty"`

	// ID of the Port Profile used on this port.
	PortProfileID *string `json:"portProfileId,omitempty" tf:"port_profile_id,omitempty"`

	// Enable port security.
	PortSecurityEnabled *bool `json:"portSecurityEnabled,omitempty" tf:"port_security_enabled,omitempty"`

	// List of MAC addresses allowed when port security is enabled.
	PortSecurityMacAddress []*string `json:"portSecurityMacAddress,omitempty" tf:"port_security_mac_address,omitempty"`

	// Priority queue 1 level.
	PriorityQueue1Level *float64 `json:"priorityQueue1Level,omitempty" tf:"priority_queue1_level,omitempty"`

	// Priority queue 2 level.
	PriorityQueue2Level *float64 `json:"priorityQueue2Level,omitempty" tf:"priority_queue2_level,omitempty"`

	// Priority queue 3 level.
	PriorityQueue3Level *float64 `json:"priorityQueue3Level,omitempty" tf:"priority_queue3_level,omitempty"`

	// Priority queue 4 level.
	PriorityQueue4Level *float64 `json:"priorityQueue4Level,omitempty" tf:"priority_queue4_level,omitempty"`

	// Setting preference.
	SettingPreference *string `json:"settingPreference,omitempty" tf:"setting_preference,omitempty"`

	// Port speed in Mbps.
	Speed *float64 `json:"speed,omitempty" tf:"speed,omitempty"`

	// Enable broadcast storm control.
	StormctrlBcastEnabled *bool `json:"stormctrlBcastEnabled,omitempty" tf:"stormctrl_bcast_enabled,omitempty"`

	// Broadcast storm control level.
	StormctrlBcastLevel *float64 `json:"stormctrlBcastLevel,omitempty" tf:"stormctrl_bcast_level,omitempty"`

	// Broadcast storm control rate.
	StormctrlBcastRate *float64 `json:"stormctrlBcastRate,omitempty" tf:"stormctrl_bcast_rate,omitempty"`

	// Enable multicast storm control.
	StormctrlMcastEnabled *bool `json:"stormctrlMcastEnabled,omitempty" tf:"stormctrl_mcast_enabled,omitempty"`

	// Multicast storm control level.
	StormctrlMcastLevel *float64 `json:"stormctrlMcastLevel,omitempty" tf:"stormctrl_mcast_level,omitempty"`

	// Multicast storm control rate.
	StormctrlMcastRate *float64 `json:"stormctrlMcastRate,omitempty" tf:"stormctrl_mcast_rate,omitempty"`

	// Storm control type.
	StormctrlType *string `json:"stormctrlType,omitempty" tf:"stormctrl_type,omitempty"`

	// Enable unicast storm control.
	StormctrlUcastEnabled *bool `json:"stormctrlUcastEnabled,omitempty" tf:"stormctrl_ucast_enabled,omitempty"`

	// Unicast storm control level.
	StormctrlUcastLevel *float64 `json:"stormctrlUcastLevel,omitempty" tf:"stormctrl_ucast_level,omitempty"`

	// Unicast storm control rate.
	StormctrlUcastRate *float64 `json:"stormctrlUcastRate,omitempty" tf:"stormctrl_ucast_rate,omitempty"`

	// STP port mode.
	StpPortMode *bool `json:"stpPortMode,omitempty" tf:"stp_port_mode,omitempty"`

	// List of network IDs to tag on this port.
	TaggedNetworkconfIds []*string `json:"taggedNetworkconfIds,omitempty" tf:"tagged_networkconf_ids,omitempty"`

	// Tagged VLAN management.
	TaggedVlanMgmt *string `json:"taggedVlanMgmt,omitempty" tf:"tagged_vlan_mgmt,omitempty"`

	// Voice network ID.
	VoiceNetworkconfID *string `json:"voiceNetworkconfId,omitempty" tf:"voice_networkconf_id,omitempty"`
}

type PortOverrideParameters struct {

	// Port indices that make up this link-aggregation (LAG) group. Only takes effect when `op_mode` is `aggregate` on this port.
	// +kubebuilder:validation:Optional
	AggregateMembers []*float64 `json:"aggregateMembers,omitempty" tf:"aggregate_members,omitempty"`

	// Enable auto-negotiation for port speed.
	// +kubebuilder:validation:Optional
	Autoneg *bool `json:"autoneg,omitempty" tf:"autoneg,omitempty"`

	// 802.1X control mode.
	// +kubebuilder:validation:Optional
	Dot1XCtrl *string `json:"dot1xCtrl,omitempty" tf:"dot1x_ctrl,omitempty"`

	// 802.1X idle timeout, as a Go duration string (e.g. `5m`, `300s`).
	// +kubebuilder:validation:Optional
	Dot1XIdleTimeout *string `json:"dot1xIdleTimeout,omitempty" tf:"dot1x_idle_timeout,omitempty"`

	// Egress rate limit in kbps.
	// +kubebuilder:validation:Optional
	EgressRateLimitKbps *float64 `json:"egressRateLimitKbps,omitempty" tf:"egress_rate_limit_kbps,omitempty"`

	// Enable egress rate limiting.
	// +kubebuilder:validation:Optional
	EgressRateLimitKbpsEnabled *bool `json:"egressRateLimitKbpsEnabled,omitempty" tf:"egress_rate_limit_kbps_enabled,omitempty"`

	// List of network IDs to exclude from this port.
	// +kubebuilder:validation:Optional
	ExcludedNetworkconfIds []*string `json:"excludedNetworkconfIds,omitempty" tf:"excluded_networkconf_ids,omitempty"`

	// Forward Error Correction mode.
	// +kubebuilder:validation:Optional
	FecMode *string `json:"fecMode,omitempty" tf:"fec_mode,omitempty"`

	// Enable flow control.
	// +kubebuilder:validation:Optional
	FlowControlEnabled *bool `json:"flowControlEnabled,omitempty" tf:"flow_control_enabled,omitempty"`

	// Forwarding mode.
	// +kubebuilder:validation:Optional
	Forward *string `json:"forward,omitempty" tf:"forward,omitempty"`

	// Enable full duplex mode.
	// +kubebuilder:validation:Optional
	FullDuplex *bool `json:"fullDuplex,omitempty" tf:"full_duplex,omitempty"`

	// Switch port index.
	// +kubebuilder:validation:Optional
	Index *float64 `json:"index" tf:"index,omitempty"`

	// Enable port isolation.
	// +kubebuilder:validation:Optional
	Isolation *bool `json:"isolation,omitempty" tf:"isolation,omitempty"`

	// Enable LLDP-MED.
	// +kubebuilder:validation:Optional
	LldpmedEnabled *bool `json:"lldpmedEnabled,omitempty" tf:"lldpmed_enabled,omitempty"`

	// Enable LLDP-MED notifications.
	// +kubebuilder:validation:Optional
	LldpmedNotifyEnabled *bool `json:"lldpmedNotifyEnabled,omitempty" tf:"lldpmed_notify_enabled,omitempty"`

	// Mirror port index.
	// +kubebuilder:validation:Optional
	MirrorPortIdx *float64 `json:"mirrorPortIdx,omitempty" tf:"mirror_port_idx,omitempty"`

	// List of network IDs for multicast router.
	// +kubebuilder:validation:Optional
	MulticastRouterNetworkconfIds []*string `json:"multicastRouterNetworkconfIds,omitempty" tf:"multicast_router_networkconf_ids,omitempty"`

	// Human-readable name of the port.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Native network ID (VLAN).
	// +kubebuilder:validation:Optional
	NativeNetworkconfID *string `json:"nativeNetworkconfId,omitempty" tf:"native_networkconf_id,omitempty"`

	// Operating mode of the port: `switch` (default), `mirror`, or `aggregate`. Set `aggregate` on the lead port of an SFP+/link-aggregation (LAG) group and list the member ports in `aggregate_members`. Only written when not `switch`, as gateway devices (UDM) reject op_mode on update.
	// +kubebuilder:validation:Optional
	OpMode *string `json:"opMode,omitempty" tf:"op_mode,omitempty"`

	// PoE mode of the port; valid values are `auto`, `pasv24`, `passthrough`, and `off`.
	// +kubebuilder:validation:Optional
	PoeMode *string `json:"poeMode,omitempty" tf:"poe_mode,omitempty"`

	// Enable port keepalive.
	// +kubebuilder:validation:Optional
	PortKeepaliveEnabled *bool `json:"portKeepaliveEnabled,omitempty" tf:"port_keepalive_enabled,omitempty"`

	// ID of the Port Profile used on this port.
	// +kubebuilder:validation:Optional
	PortProfileID *string `json:"portProfileId,omitempty" tf:"port_profile_id,omitempty"`

	// Enable port security.
	// +kubebuilder:validation:Optional
	PortSecurityEnabled *bool `json:"portSecurityEnabled,omitempty" tf:"port_security_enabled,omitempty"`

	// List of MAC addresses allowed when port security is enabled.
	// +kubebuilder:validation:Optional
	PortSecurityMacAddress []*string `json:"portSecurityMacAddress,omitempty" tf:"port_security_mac_address,omitempty"`

	// Priority queue 1 level.
	// +kubebuilder:validation:Optional
	PriorityQueue1Level *float64 `json:"priorityQueue1Level,omitempty" tf:"priority_queue1_level,omitempty"`

	// Priority queue 2 level.
	// +kubebuilder:validation:Optional
	PriorityQueue2Level *float64 `json:"priorityQueue2Level,omitempty" tf:"priority_queue2_level,omitempty"`

	// Priority queue 3 level.
	// +kubebuilder:validation:Optional
	PriorityQueue3Level *float64 `json:"priorityQueue3Level,omitempty" tf:"priority_queue3_level,omitempty"`

	// Priority queue 4 level.
	// +kubebuilder:validation:Optional
	PriorityQueue4Level *float64 `json:"priorityQueue4Level,omitempty" tf:"priority_queue4_level,omitempty"`

	// Setting preference.
	// +kubebuilder:validation:Optional
	SettingPreference *string `json:"settingPreference,omitempty" tf:"setting_preference,omitempty"`

	// Port speed in Mbps.
	// +kubebuilder:validation:Optional
	Speed *float64 `json:"speed,omitempty" tf:"speed,omitempty"`

	// Enable broadcast storm control.
	// +kubebuilder:validation:Optional
	StormctrlBcastEnabled *bool `json:"stormctrlBcastEnabled,omitempty" tf:"stormctrl_bcast_enabled,omitempty"`

	// Broadcast storm control level.
	// +kubebuilder:validation:Optional
	StormctrlBcastLevel *float64 `json:"stormctrlBcastLevel,omitempty" tf:"stormctrl_bcast_level,omitempty"`

	// Broadcast storm control rate.
	// +kubebuilder:validation:Optional
	StormctrlBcastRate *float64 `json:"stormctrlBcastRate,omitempty" tf:"stormctrl_bcast_rate,omitempty"`

	// Enable multicast storm control.
	// +kubebuilder:validation:Optional
	StormctrlMcastEnabled *bool `json:"stormctrlMcastEnabled,omitempty" tf:"stormctrl_mcast_enabled,omitempty"`

	// Multicast storm control level.
	// +kubebuilder:validation:Optional
	StormctrlMcastLevel *float64 `json:"stormctrlMcastLevel,omitempty" tf:"stormctrl_mcast_level,omitempty"`

	// Multicast storm control rate.
	// +kubebuilder:validation:Optional
	StormctrlMcastRate *float64 `json:"stormctrlMcastRate,omitempty" tf:"stormctrl_mcast_rate,omitempty"`

	// Storm control type.
	// +kubebuilder:validation:Optional
	StormctrlType *string `json:"stormctrlType,omitempty" tf:"stormctrl_type,omitempty"`

	// Enable unicast storm control.
	// +kubebuilder:validation:Optional
	StormctrlUcastEnabled *bool `json:"stormctrlUcastEnabled,omitempty" tf:"stormctrl_ucast_enabled,omitempty"`

	// Unicast storm control level.
	// +kubebuilder:validation:Optional
	StormctrlUcastLevel *float64 `json:"stormctrlUcastLevel,omitempty" tf:"stormctrl_ucast_level,omitempty"`

	// Unicast storm control rate.
	// +kubebuilder:validation:Optional
	StormctrlUcastRate *float64 `json:"stormctrlUcastRate,omitempty" tf:"stormctrl_ucast_rate,omitempty"`

	// STP port mode.
	// +kubebuilder:validation:Optional
	StpPortMode *bool `json:"stpPortMode,omitempty" tf:"stp_port_mode,omitempty"`

	// List of network IDs to tag on this port.
	// +kubebuilder:validation:Optional
	TaggedNetworkconfIds []*string `json:"taggedNetworkconfIds,omitempty" tf:"tagged_networkconf_ids,omitempty"`

	// Tagged VLAN management.
	// +kubebuilder:validation:Optional
	TaggedVlanMgmt *string `json:"taggedVlanMgmt,omitempty" tf:"tagged_vlan_mgmt,omitempty"`

	// Voice network ID.
	// +kubebuilder:validation:Optional
	VoiceNetworkconfID *string `json:"voiceNetworkconfId,omitempty" tf:"voice_networkconf_id,omitempty"`
}

type RadioTableInitParameters struct {

	// Antenna gain.
	AntennaGain *float64 `json:"antennaGain,omitempty" tf:"antenna_gain,omitempty"`

	// Antenna ID.
	AntennaID *float64 `json:"antennaId,omitempty" tf:"antenna_id,omitempty"`

	// Enable assisted roaming.
	AssistedRoamingEnabled *bool `json:"assistedRoamingEnabled,omitempty" tf:"assisted_roaming_enabled,omitempty"`

	// Assisted roaming RSSI threshold.
	AssistedRoamingRssi *float64 `json:"assistedRoamingRssi,omitempty" tf:"assisted_roaming_rssi,omitempty"`

	// Channel number or 'auto'.
	Channel *string `json:"channel,omitempty" tf:"channel,omitempty"`

	// Enable DFS (Dynamic Frequency Selection).
	Dfs *bool `json:"dfs,omitempty" tf:"dfs,omitempty"`

	// Enable hard noise floor.
	HardNoiseFloorEnabled *bool `json:"hardNoiseFloorEnabled,omitempty" tf:"hard_noise_floor_enabled,omitempty"`

	// Channel width (20, 40, 80, 160).
	Ht *float64 `json:"ht,omitempty" tf:"ht,omitempty"`

	// Enable load balancing.
	LoadbalanceEnabled *bool `json:"loadbalanceEnabled,omitempty" tf:"loadbalance_enabled,omitempty"`

	// Maximum number of stations.
	Maxsta *float64 `json:"maxsta,omitempty" tf:"maxsta,omitempty"`

	// Minimum RSSI value.
	MinRssi *float64 `json:"minRssi,omitempty" tf:"min_rssi,omitempty"`

	// Enable minimum RSSI.
	MinRssiEnabled *bool `json:"minRssiEnabled,omitempty" tf:"min_rssi_enabled,omitempty"`

	// Radio name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Radio band (ng, na, ad, 6e).
	Radio *string `json:"radio,omitempty" tf:"radio,omitempty"`

	// Sensitivity level.
	SensLevel *float64 `json:"sensLevel,omitempty" tf:"sens_level,omitempty"`

	// Enable sensitivity level.
	SensLevelEnabled *bool `json:"sensLevelEnabled,omitempty" tf:"sens_level_enabled,omitempty"`

	// Transmit power or 'auto'.
	TxPower *string `json:"txPower,omitempty" tf:"tx_power,omitempty"`

	// Transmit power mode (auto, medium, high, low, custom).
	TxPowerMode *string `json:"txPowerMode,omitempty" tf:"tx_power_mode,omitempty"`

	// Enable virtual wire.
	VwireEnabled *bool `json:"vwireEnabled,omitempty" tf:"vwire_enabled,omitempty"`
}

type RadioTableObservation struct {

	// Antenna gain.
	AntennaGain *float64 `json:"antennaGain,omitempty" tf:"antenna_gain,omitempty"`

	// Antenna ID.
	AntennaID *float64 `json:"antennaId,omitempty" tf:"antenna_id,omitempty"`

	// Enable assisted roaming.
	AssistedRoamingEnabled *bool `json:"assistedRoamingEnabled,omitempty" tf:"assisted_roaming_enabled,omitempty"`

	// Assisted roaming RSSI threshold.
	AssistedRoamingRssi *float64 `json:"assistedRoamingRssi,omitempty" tf:"assisted_roaming_rssi,omitempty"`

	// Channel number or 'auto'.
	Channel *string `json:"channel,omitempty" tf:"channel,omitempty"`

	// Enable DFS (Dynamic Frequency Selection).
	Dfs *bool `json:"dfs,omitempty" tf:"dfs,omitempty"`

	// Enable hard noise floor.
	HardNoiseFloorEnabled *bool `json:"hardNoiseFloorEnabled,omitempty" tf:"hard_noise_floor_enabled,omitempty"`

	// Channel width (20, 40, 80, 160).
	Ht *float64 `json:"ht,omitempty" tf:"ht,omitempty"`

	// Enable load balancing.
	LoadbalanceEnabled *bool `json:"loadbalanceEnabled,omitempty" tf:"loadbalance_enabled,omitempty"`

	// Maximum number of stations.
	Maxsta *float64 `json:"maxsta,omitempty" tf:"maxsta,omitempty"`

	// Minimum RSSI value.
	MinRssi *float64 `json:"minRssi,omitempty" tf:"min_rssi,omitempty"`

	// Enable minimum RSSI.
	MinRssiEnabled *bool `json:"minRssiEnabled,omitempty" tf:"min_rssi_enabled,omitempty"`

	// Radio name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Radio band (ng, na, ad, 6e).
	Radio *string `json:"radio,omitempty" tf:"radio,omitempty"`

	// Sensitivity level.
	SensLevel *float64 `json:"sensLevel,omitempty" tf:"sens_level,omitempty"`

	// Enable sensitivity level.
	SensLevelEnabled *bool `json:"sensLevelEnabled,omitempty" tf:"sens_level_enabled,omitempty"`

	// Transmit power or 'auto'.
	TxPower *string `json:"txPower,omitempty" tf:"tx_power,omitempty"`

	// Transmit power mode (auto, medium, high, low, custom).
	TxPowerMode *string `json:"txPowerMode,omitempty" tf:"tx_power_mode,omitempty"`

	// Enable virtual wire.
	VwireEnabled *bool `json:"vwireEnabled,omitempty" tf:"vwire_enabled,omitempty"`
}

type RadioTableParameters struct {

	// Antenna gain.
	// +kubebuilder:validation:Optional
	AntennaGain *float64 `json:"antennaGain,omitempty" tf:"antenna_gain,omitempty"`

	// Antenna ID.
	// +kubebuilder:validation:Optional
	AntennaID *float64 `json:"antennaId,omitempty" tf:"antenna_id,omitempty"`

	// Enable assisted roaming.
	// +kubebuilder:validation:Optional
	AssistedRoamingEnabled *bool `json:"assistedRoamingEnabled,omitempty" tf:"assisted_roaming_enabled,omitempty"`

	// Assisted roaming RSSI threshold.
	// +kubebuilder:validation:Optional
	AssistedRoamingRssi *float64 `json:"assistedRoamingRssi,omitempty" tf:"assisted_roaming_rssi,omitempty"`

	// Channel number or 'auto'.
	// +kubebuilder:validation:Optional
	Channel *string `json:"channel,omitempty" tf:"channel,omitempty"`

	// Enable DFS (Dynamic Frequency Selection).
	// +kubebuilder:validation:Optional
	Dfs *bool `json:"dfs,omitempty" tf:"dfs,omitempty"`

	// Enable hard noise floor.
	// +kubebuilder:validation:Optional
	HardNoiseFloorEnabled *bool `json:"hardNoiseFloorEnabled,omitempty" tf:"hard_noise_floor_enabled,omitempty"`

	// Channel width (20, 40, 80, 160).
	// +kubebuilder:validation:Optional
	Ht *float64 `json:"ht,omitempty" tf:"ht,omitempty"`

	// Enable load balancing.
	// +kubebuilder:validation:Optional
	LoadbalanceEnabled *bool `json:"loadbalanceEnabled,omitempty" tf:"loadbalance_enabled,omitempty"`

	// Maximum number of stations.
	// +kubebuilder:validation:Optional
	Maxsta *float64 `json:"maxsta,omitempty" tf:"maxsta,omitempty"`

	// Minimum RSSI value.
	// +kubebuilder:validation:Optional
	MinRssi *float64 `json:"minRssi,omitempty" tf:"min_rssi,omitempty"`

	// Enable minimum RSSI.
	// +kubebuilder:validation:Optional
	MinRssiEnabled *bool `json:"minRssiEnabled,omitempty" tf:"min_rssi_enabled,omitempty"`

	// Radio name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Radio band (ng, na, ad, 6e).
	// +kubebuilder:validation:Optional
	Radio *string `json:"radio,omitempty" tf:"radio,omitempty"`

	// Sensitivity level.
	// +kubebuilder:validation:Optional
	SensLevel *float64 `json:"sensLevel,omitempty" tf:"sens_level,omitempty"`

	// Enable sensitivity level.
	// +kubebuilder:validation:Optional
	SensLevelEnabled *bool `json:"sensLevelEnabled,omitempty" tf:"sens_level_enabled,omitempty"`

	// Transmit power or 'auto'.
	// +kubebuilder:validation:Optional
	TxPower *string `json:"txPower,omitempty" tf:"tx_power,omitempty"`

	// Transmit power mode (auto, medium, high, low, custom).
	// +kubebuilder:validation:Optional
	TxPowerMode *string `json:"txPowerMode,omitempty" tf:"tx_power_mode,omitempty"`

	// Enable virtual wire.
	// +kubebuilder:validation:Optional
	VwireEnabled *bool `json:"vwireEnabled,omitempty" tf:"vwire_enabled,omitempty"`
}

// DeviceSpec defines the desired state of Device
type DeviceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     DeviceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DeviceInitParameters `json:"initProvider,omitempty"`
}

// DeviceStatus defines the observed state of Device.
type DeviceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DeviceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Device is the Schema for the Devices API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,unifi}
type Device struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DeviceSpec   `json:"spec"`
	Status            DeviceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DeviceList contains a list of Devices
type DeviceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Device `json:"items"`
}

// Repository type metadata.
var (
	Device_Kind             = "Device"
	Device_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Device_Kind}.String()
	Device_KindAPIVersion   = Device_Kind + "." + CRDGroupVersion.String()
	Device_GroupVersionKind = CRDGroupVersion.WithKind(Device_Kind)
)

func init() {
	SchemeBuilder.Register(&Device{}, &DeviceList{})
}
