// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PowerSourcesInitParameters struct {
}

type PowerSourcesObservation struct {

	// Index of the supervised device's PSU.
	ClientPsuIndex *float64 `json:"clientPsuIndex,omitempty" tf:"client_psu_index,omitempty"`

	// Port/outlet index on the upstream source.
	PowerSourceIndex *float64 `json:"powerSourceIndex,omitempty" tf:"power_source_index,omitempty"`

	// MAC of the upstream source (e.g. the PoE switch).
	PowerSourceMac *string `json:"powerSourceMac,omitempty" tf:"power_source_mac,omitempty"`

	// Type of the upstream source (e.g. `poe_port`).
	PowerSourceType *string `json:"powerSourceType,omitempty" tf:"power_source_type,omitempty"`
}

type PowerSourcesParameters struct {
}

type SupervisorInitParameters struct {

	// MAC address of the supervised device (the controller keys supervisors per device). Changing it replaces the supervisor.
	DeviceMac *string `json:"deviceMac,omitempty" tf:"device_mac,omitempty"`

	// Whether supervision is enabled. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// How often the controller probes the device, as a Go duration string (e.g. `60s`, `1m`). Defaults to `1m0s`.
	HeartbeatInterval *string `json:"heartbeatInterval,omitempty" tf:"heartbeat_interval,omitempty"`

	// How long the upstream PoE source stays off during a power-cycle, as a Go duration string (e.g. `2m`). Defaults to `2m0s`.
	PowerOffDuration *string `json:"powerOffDuration,omitempty" tf:"power_off_duration,omitempty"`

	// How long the device may be silent before the controller power-cycles its upstream PoE source, as a Go duration string (e.g. `15m`). Defaults to `15m0s`.
	SilenceThreshold *string `json:"silenceThreshold,omitempty" tf:"silence_threshold,omitempty"`

	// The name of the site the supervisor belongs to.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Timeouts *SupervisorTimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type SupervisorObservation struct {

	// Number of consecutive heartbeat failures observed by the controller (read-only).
	ConsecutiveFailures *float64 `json:"consecutiveFailures,omitempty" tf:"consecutive_failures,omitempty"`

	// MAC address of the supervised device (the controller keys supervisors per device). Changing it replaces the supervisor.
	DeviceMac *string `json:"deviceMac,omitempty" tf:"device_mac,omitempty"`

	// Whether supervision is enabled. Defaults to `true`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// How often the controller probes the device, as a Go duration string (e.g. `60s`, `1m`). Defaults to `1m0s`.
	HeartbeatInterval *string `json:"heartbeatInterval,omitempty" tf:"heartbeat_interval,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// How long the upstream PoE source stays off during a power-cycle, as a Go duration string (e.g. `2m`). Defaults to `2m0s`.
	PowerOffDuration *string `json:"powerOffDuration,omitempty" tf:"power_off_duration,omitempty"`

	PowerSources []PowerSourcesObservation `json:"powerSources,omitempty" tf:"power_sources,omitempty"`

	// How long the device may be silent before the controller power-cycles its upstream PoE source, as a Go duration string (e.g. `15m`). Defaults to `15m0s`.
	SilenceThreshold *string `json:"silenceThreshold,omitempty" tf:"silence_threshold,omitempty"`

	// The name of the site the supervisor belongs to.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Timeouts *SupervisorTimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type SupervisorParameters struct {

	// MAC address of the supervised device (the controller keys supervisors per device). Changing it replaces the supervisor.
	// +kubebuilder:validation:Optional
	DeviceMac *string `json:"deviceMac,omitempty" tf:"device_mac,omitempty"`

	// Whether supervision is enabled. Defaults to `true`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// How often the controller probes the device, as a Go duration string (e.g. `60s`, `1m`). Defaults to `1m0s`.
	// +kubebuilder:validation:Optional
	HeartbeatInterval *string `json:"heartbeatInterval,omitempty" tf:"heartbeat_interval,omitempty"`

	// How long the upstream PoE source stays off during a power-cycle, as a Go duration string (e.g. `2m`). Defaults to `2m0s`.
	// +kubebuilder:validation:Optional
	PowerOffDuration *string `json:"powerOffDuration,omitempty" tf:"power_off_duration,omitempty"`

	// How long the device may be silent before the controller power-cycles its upstream PoE source, as a Go duration string (e.g. `15m`). Defaults to `15m0s`.
	// +kubebuilder:validation:Optional
	SilenceThreshold *string `json:"silenceThreshold,omitempty" tf:"silence_threshold,omitempty"`

	// The name of the site the supervisor belongs to.
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *SupervisorTimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type SupervisorTimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type SupervisorTimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type SupervisorTimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

// SupervisorSpec defines the desired state of Supervisor
type SupervisorSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SupervisorParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SupervisorInitParameters `json:"initProvider,omitempty"`
}

// SupervisorStatus defines the observed state of Supervisor.
type SupervisorStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SupervisorObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Supervisor is the Schema for the Supervisors API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,unifi}
type Supervisor struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.deviceMac) || (has(self.initProvider) && has(self.initProvider.deviceMac))",message="spec.forProvider.deviceMac is a required parameter"
	Spec   SupervisorSpec   `json:"spec"`
	Status SupervisorStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SupervisorList contains a list of Supervisors
type SupervisorList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Supervisor `json:"items"`
}

// Repository type metadata.
var (
	Supervisor_Kind             = "Supervisor"
	Supervisor_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Supervisor_Kind}.String()
	Supervisor_KindAPIVersion   = Supervisor_Kind + "." + CRDGroupVersion.String()
	Supervisor_GroupVersionKind = CRDGroupVersion.WithKind(Supervisor_Kind)
)

func init() {
	SchemeBuilder.Register(&Supervisor{}, &SupervisorList{})
}
