// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClientsInitParameters struct {

	// The MAC address of the client device.
	Mac *string `json:"mac,omitempty" tf:"mac,omitempty"`
}

type ClientsObservation struct {

	// The MAC address of the client device.
	Mac *string `json:"mac,omitempty" tf:"mac,omitempty"`
}

type ClientsParameters struct {

	// The MAC address of the client device.
	// +kubebuilder:validation:Optional
	Mac *string `json:"mac" tf:"mac,omitempty"`
}

type DestinationInitParameters struct {

	// List of domain names to match.
	Domain []*string `json:"domain,omitempty" tf:"domain,omitempty"`

	IP []IPInitParameters `json:"ip,omitempty" tf:"ip,omitempty"`

	// List of regions to match.
	Region []*string `json:"region,omitempty" tf:"region,omitempty"`
}

type DestinationObservation struct {

	// List of domain names to match.
	Domain []*string `json:"domain,omitempty" tf:"domain,omitempty"`

	IP []IPObservation `json:"ip,omitempty" tf:"ip,omitempty"`

	// List of regions to match.
	Region []*string `json:"region,omitempty" tf:"region,omitempty"`
}

type DestinationParameters struct {

	// List of domain names to match.
	// +kubebuilder:validation:Optional
	Domain []*string `json:"domain,omitempty" tf:"domain,omitempty"`

	// +kubebuilder:validation:Optional
	IP []IPParameters `json:"ip,omitempty" tf:"ip,omitempty"`

	// List of regions to match.
	// +kubebuilder:validation:Optional
	Region []*string `json:"region,omitempty" tf:"region,omitempty"`
}

type IPInitParameters struct {

	// An IP address, CIDR subnet, or hyphenated IP range to match.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// List of ports or port ranges to match. Use a single number (e.g. `80`) for individual ports, or a hyphenated range (e.g. `8080-8090`) for port ranges. Only supported for IP addresses and subnets, not IP ranges.
	Ports []*string `json:"ports,omitempty" tf:"ports,omitempty"`
}

type IPObservation struct {

	// An IP address, CIDR subnet, or hyphenated IP range to match.
	Address *string `json:"address,omitempty" tf:"address,omitempty"`

	// List of ports or port ranges to match. Use a single number (e.g. `80`) for individual ports, or a hyphenated range (e.g. `8080-8090`) for port ranges. Only supported for IP addresses and subnets, not IP ranges.
	Ports []*string `json:"ports,omitempty" tf:"ports,omitempty"`
}

type IPParameters struct {

	// An IP address, CIDR subnet, or hyphenated IP range to match.
	// +kubebuilder:validation:Optional
	Address *string `json:"address" tf:"address,omitempty"`

	// List of ports or port ranges to match. Use a single number (e.g. `80`) for individual ports, or a hyphenated range (e.g. `8080-8090`) for port ranges. Only supported for IP addresses and subnets, not IP ranges.
	// +kubebuilder:validation:Optional
	Ports []*string `json:"ports,omitempty" tf:"ports,omitempty"`
}

type NetworksInitParameters struct {

	// The ID of the network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworksObservation struct {

	// The ID of the network.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type NetworksParameters struct {

	// The ID of the network.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type SourceInitParameters struct {
	Clients []ClientsInitParameters `json:"clients,omitempty" tf:"clients,omitempty"`

	Networks []NetworksInitParameters `json:"networks,omitempty" tf:"networks,omitempty"`
}

type SourceObservation struct {
	Clients []ClientsObservation `json:"clients,omitempty" tf:"clients,omitempty"`

	Networks []NetworksObservation `json:"networks,omitempty" tf:"networks,omitempty"`
}

type SourceParameters struct {

	// +kubebuilder:validation:Optional
	Clients []ClientsParameters `json:"clients,omitempty" tf:"clients,omitempty"`

	// +kubebuilder:validation:Optional
	Networks []NetworksParameters `json:"networks,omitempty" tf:"networks,omitempty"`
}

type TrafficRouteInitParameters struct {

	// A description of the traffic route (max 128 characters).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Destination *DestinationInitParameters `json:"destination,omitempty" tf:"destination,omitempty"`

	// Whether the traffic route is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether the kill switch is enabled. When enabled, traffic is blocked if the target network/VPN is unavailable.
	KillSwitchEnabled *bool `json:"killSwitchEnabled,omitempty" tf:"kill_switch_enabled,omitempty"`

	// The ID of the network or VPN to route matching traffic through. Defaults to the primary WAN network.
	// +crossplane:generate:reference:type=github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/vpn/v1alpha1.Client
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Client in vpn to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Client in vpn to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// The next hop for the traffic route.
	NextHop *string `json:"nextHop,omitempty" tf:"next_hop,omitempty"`

	// The name of the site to associate the traffic route with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Source *SourceInitParameters `json:"source,omitempty" tf:"source,omitempty"`

	Timeouts *TrafficRouteTimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type TrafficRouteObservation struct {

	// A description of the traffic route (max 128 characters).
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	Destination *DestinationObservation `json:"destination,omitempty" tf:"destination,omitempty"`

	// Whether the traffic route is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether the kill switch is enabled. When enabled, traffic is blocked if the target network/VPN is unavailable.
	KillSwitchEnabled *bool `json:"killSwitchEnabled,omitempty" tf:"kill_switch_enabled,omitempty"`

	// The ID of the network or VPN to route matching traffic through. Defaults to the primary WAN network.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// The next hop for the traffic route.
	NextHop *string `json:"nextHop,omitempty" tf:"next_hop,omitempty"`

	// The name of the site to associate the traffic route with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Source *SourceObservation `json:"source,omitempty" tf:"source,omitempty"`

	Timeouts *TrafficRouteTimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type TrafficRouteParameters struct {

	// A description of the traffic route (max 128 characters).
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// +kubebuilder:validation:Optional
	Destination *DestinationParameters `json:"destination,omitempty" tf:"destination,omitempty"`

	// Whether the traffic route is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether the kill switch is enabled. When enabled, traffic is blocked if the target network/VPN is unavailable.
	// +kubebuilder:validation:Optional
	KillSwitchEnabled *bool `json:"killSwitchEnabled,omitempty" tf:"kill_switch_enabled,omitempty"`

	// The ID of the network or VPN to route matching traffic through. Defaults to the primary WAN network.
	// +crossplane:generate:reference:type=github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/vpn/v1alpha1.Client
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Client in vpn to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Client in vpn to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// The next hop for the traffic route.
	// +kubebuilder:validation:Optional
	NextHop *string `json:"nextHop,omitempty" tf:"next_hop,omitempty"`

	// The name of the site to associate the traffic route with.
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// +kubebuilder:validation:Optional
	Source *SourceParameters `json:"source,omitempty" tf:"source,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *TrafficRouteTimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`
}

type TrafficRouteTimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TrafficRouteTimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TrafficRouteTimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

// TrafficRouteSpec defines the desired state of TrafficRoute
type TrafficRouteSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TrafficRouteParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TrafficRouteInitParameters `json:"initProvider,omitempty"`
}

// TrafficRouteStatus defines the observed state of TrafficRoute.
type TrafficRouteStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TrafficRouteObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TrafficRoute is the Schema for the TrafficRoutes API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,unifi}
type TrafficRoute struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TrafficRouteSpec   `json:"spec"`
	Status            TrafficRouteStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TrafficRouteList contains a list of TrafficRoutes
type TrafficRouteList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TrafficRoute `json:"items"`
}

// Repository type metadata.
var (
	TrafficRoute_Kind             = "TrafficRoute"
	TrafficRoute_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TrafficRoute_Kind}.String()
	TrafficRoute_KindAPIVersion   = TrafficRoute_Kind + "." + CRDGroupVersion.String()
	TrafficRoute_GroupVersionKind = CRDGroupVersion.WithKind(TrafficRoute_Kind)
)

func init() {
	SchemeBuilder.Register(&TrafficRoute{}, &TrafficRouteList{})
}
