// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Wlan.
func (mg *Wlan) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var mrsp reference.MultiNamespacedResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.ApGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.ApGroupIdsRefs,
		Selector:      mg.Spec.ForProvider.ApGroupIdsSelector,
		To: reference.To{
			List:    &ApGroupList{},
			Managed: &ApGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ApGroupIds")
	}
	mg.Spec.ForProvider.ApGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.ApGroupIdsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiNamespacedResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.ApGroupIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.ApGroupIdsRefs,
		Selector:      mg.Spec.InitProvider.ApGroupIdsSelector,
		To: reference.To{
			List:    &ApGroupList{},
			Managed: &ApGroup{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ApGroupIds")
	}
	mg.Spec.InitProvider.ApGroupIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.ApGroupIdsRefs = mrsp.ResolvedReferences

	return nil
}
