//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacFilterInitParameters) DeepCopyInto(out *MacFilterInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacFilterInitParameters.
func (in *MacFilterInitParameters) DeepCopy() *MacFilterInitParameters {
	if in == nil {
		return nil
	}
	out := new(MacFilterInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacFilterObservation) DeepCopyInto(out *MacFilterObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacFilterObservation.
func (in *MacFilterObservation) DeepCopy() *MacFilterObservation {
	if in == nil {
		return nil
	}
	out := new(MacFilterObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MacFilterParameters) DeepCopyInto(out *MacFilterParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.List != nil {
		in, out := &in.List, &out.List
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MacFilterParameters.
func (in *MacFilterParameters) DeepCopy() *MacFilterParameters {
	if in == nil {
		return nil
	}
	out := new(MacFilterParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatePresharedKeysInitParameters) DeepCopyInto(out *PrivatePresharedKeysInitParameters) {
	*out = *in
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatePresharedKeysInitParameters.
func (in *PrivatePresharedKeysInitParameters) DeepCopy() *PrivatePresharedKeysInitParameters {
	if in == nil {
		return nil
	}
	out := new(PrivatePresharedKeysInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatePresharedKeysObservation) DeepCopyInto(out *PrivatePresharedKeysObservation) {
	*out = *in
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatePresharedKeysObservation.
func (in *PrivatePresharedKeysObservation) DeepCopy() *PrivatePresharedKeysObservation {
	if in == nil {
		return nil
	}
	out := new(PrivatePresharedKeysObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PrivatePresharedKeysParameters) DeepCopyInto(out *PrivatePresharedKeysParameters) {
	*out = *in
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PrivatePresharedKeysParameters.
func (in *PrivatePresharedKeysParameters) DeepCopy() *PrivatePresharedKeysParameters {
	if in == nil {
		return nil
	}
	out := new(PrivatePresharedKeysParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleInitParameters) DeepCopyInto(out *ScheduleInitParameters) {
	*out = *in
	if in.DayOfWeek != nil {
		in, out := &in.DayOfWeek, &out.DayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StartHour != nil {
		in, out := &in.StartHour, &out.StartHour
		*out = new(float64)
		**out = **in
	}
	if in.StartMinute != nil {
		in, out := &in.StartMinute, &out.StartMinute
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleInitParameters.
func (in *ScheduleInitParameters) DeepCopy() *ScheduleInitParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleObservation) DeepCopyInto(out *ScheduleObservation) {
	*out = *in
	if in.DayOfWeek != nil {
		in, out := &in.DayOfWeek, &out.DayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StartHour != nil {
		in, out := &in.StartHour, &out.StartHour
		*out = new(float64)
		**out = **in
	}
	if in.StartMinute != nil {
		in, out := &in.StartMinute, &out.StartMinute
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleObservation.
func (in *ScheduleObservation) DeepCopy() *ScheduleObservation {
	if in == nil {
		return nil
	}
	out := new(ScheduleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleParameters) DeepCopyInto(out *ScheduleParameters) {
	*out = *in
	if in.DayOfWeek != nil {
		in, out := &in.DayOfWeek, &out.DayOfWeek
		*out = new(string)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.StartHour != nil {
		in, out := &in.StartHour, &out.StartHour
		*out = new(float64)
		**out = **in
	}
	if in.StartMinute != nil {
		in, out := &in.StartMinute, &out.StartMinute
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleParameters.
func (in *ScheduleParameters) DeepCopy() *ScheduleParameters {
	if in == nil {
		return nil
	}
	out := new(ScheduleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsInitParameters) DeepCopyInto(out *TimeoutsInitParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsInitParameters.
func (in *TimeoutsInitParameters) DeepCopy() *TimeoutsInitParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsObservation) DeepCopyInto(out *TimeoutsObservation) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsObservation.
func (in *TimeoutsObservation) DeepCopy() *TimeoutsObservation {
	if in == nil {
		return nil
	}
	out := new(TimeoutsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsParameters) DeepCopyInto(out *TimeoutsParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsParameters.
func (in *TimeoutsParameters) DeepCopy() *TimeoutsParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Wlan) DeepCopyInto(out *Wlan) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Wlan.
func (in *Wlan) DeepCopy() *Wlan {
	if in == nil {
		return nil
	}
	out := new(Wlan)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Wlan) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WlanInitParameters) DeepCopyInto(out *WlanInitParameters) {
	*out = *in
	if in.ApGroupIds != nil {
		in, out := &in.ApGroupIds, &out.ApGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ApGroupMode != nil {
		in, out := &in.ApGroupMode, &out.ApGroupMode
		*out = new(string)
		**out = **in
	}
	if in.BcFilterList != nil {
		in, out := &in.BcFilterList, &out.BcFilterList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BssTransition != nil {
		in, out := &in.BssTransition, &out.BssTransition
		*out = new(bool)
		**out = **in
	}
	if in.Dtim6E != nil {
		in, out := &in.Dtim6E, &out.Dtim6E
		*out = new(float64)
		**out = **in
	}
	if in.DtimMode != nil {
		in, out := &in.DtimMode, &out.DtimMode
		*out = new(string)
		**out = **in
	}
	if in.DtimNa != nil {
		in, out := &in.DtimNa, &out.DtimNa
		*out = new(float64)
		**out = **in
	}
	if in.DtimNg != nil {
		in, out := &in.DtimNg, &out.DtimNg
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnhancedIot != nil {
		in, out := &in.EnhancedIot, &out.EnhancedIot
		*out = new(bool)
		**out = **in
	}
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekey != nil {
		in, out := &in.GroupRekey, &out.GroupRekey
		*out = new(float64)
		**out = **in
	}
	if in.HideSsid != nil {
		in, out := &in.HideSsid, &out.HideSsid
		*out = new(bool)
		**out = **in
	}
	if in.Hotspot2ConfEnabled != nil {
		in, out := &in.Hotspot2ConfEnabled, &out.Hotspot2ConfEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IappEnabled != nil {
		in, out := &in.IappEnabled, &out.IappEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsGuest != nil {
		in, out := &in.IsGuest, &out.IsGuest
		*out = new(bool)
		**out = **in
	}
	if in.L2Isolation != nil {
		in, out := &in.L2Isolation, &out.L2Isolation
		*out = new(bool)
		**out = **in
	}
	if in.MacFilter != nil {
		in, out := &in.MacFilter, &out.MacFilter
		*out = new(MacFilterInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.MinimumDataRate2GKbps != nil {
		in, out := &in.MinimumDataRate2GKbps, &out.MinimumDataRate2GKbps
		*out = new(float64)
		**out = **in
	}
	if in.MinimumDataRate5GKbps != nil {
		in, out := &in.MinimumDataRate5GKbps, &out.MinimumDataRate5GKbps
		*out = new(float64)
		**out = **in
	}
	if in.MinrateSettingPreference != nil {
		in, out := &in.MinrateSettingPreference, &out.MinrateSettingPreference
		*out = new(string)
		**out = **in
	}
	if in.MloEnabled != nil {
		in, out := &in.MloEnabled, &out.MloEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MulticastEnhance != nil {
		in, out := &in.MulticastEnhance, &out.MulticastEnhance
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NasIdentifierType != nil {
		in, out := &in.NasIdentifierType, &out.NasIdentifierType
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.No2GhzOui != nil {
		in, out := &in.No2GhzOui, &out.No2GhzOui
		*out = new(bool)
		**out = **in
	}
	if in.PassphraseSecretRef != nil {
		in, out := &in.PassphraseSecretRef, &out.PassphraseSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.PassphraseWoSecretRef != nil {
		in, out := &in.PassphraseWoSecretRef, &out.PassphraseWoSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.PmfMode != nil {
		in, out := &in.PmfMode, &out.PmfMode
		*out = new(string)
		**out = **in
	}
	if in.PrivatePresharedKeys != nil {
		in, out := &in.PrivatePresharedKeys, &out.PrivatePresharedKeys
		*out = make([]PrivatePresharedKeysInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrivatePresharedKeysEnabled != nil {
		in, out := &in.PrivatePresharedKeysEnabled, &out.PrivatePresharedKeysEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProxyArp != nil {
		in, out := &in.ProxyArp, &out.ProxyArp
		*out = new(bool)
		**out = **in
	}
	if in.RadiusMacAuthEnabled != nil {
		in, out := &in.RadiusMacAuthEnabled, &out.RadiusMacAuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RadiusProfileID != nil {
		in, out := &in.RadiusProfileID, &out.RadiusProfileID
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = make([]ScheduleInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Uapsd != nil {
		in, out := &in.Uapsd, &out.Uapsd
		*out = new(bool)
		**out = **in
	}
	if in.UserGroupID != nil {
		in, out := &in.UserGroupID, &out.UserGroupID
		*out = new(string)
		**out = **in
	}
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(float64)
		**out = **in
	}
	if in.VlanEnabled != nil {
		in, out := &in.VlanEnabled, &out.VlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.WlanBand != nil {
		in, out := &in.WlanBand, &out.WlanBand
		*out = new(string)
		**out = **in
	}
	if in.WlanBands != nil {
		in, out := &in.WlanBands, &out.WlanBands
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Wpa3Enhanced192 != nil {
		in, out := &in.Wpa3Enhanced192, &out.Wpa3Enhanced192
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3FastRoaming != nil {
		in, out := &in.Wpa3FastRoaming, &out.Wpa3FastRoaming
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3Support != nil {
		in, out := &in.Wpa3Support, &out.Wpa3Support
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3Transition != nil {
		in, out := &in.Wpa3Transition, &out.Wpa3Transition
		*out = new(bool)
		**out = **in
	}
	if in.WpaEnc != nil {
		in, out := &in.WpaEnc, &out.WpaEnc
		*out = new(string)
		**out = **in
	}
	if in.WpaMode != nil {
		in, out := &in.WpaMode, &out.WpaMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WlanInitParameters.
func (in *WlanInitParameters) DeepCopy() *WlanInitParameters {
	if in == nil {
		return nil
	}
	out := new(WlanInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WlanList) DeepCopyInto(out *WlanList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Wlan, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WlanList.
func (in *WlanList) DeepCopy() *WlanList {
	if in == nil {
		return nil
	}
	out := new(WlanList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WlanList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WlanObservation) DeepCopyInto(out *WlanObservation) {
	*out = *in
	if in.ApGroupIds != nil {
		in, out := &in.ApGroupIds, &out.ApGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ApGroupMode != nil {
		in, out := &in.ApGroupMode, &out.ApGroupMode
		*out = new(string)
		**out = **in
	}
	if in.BcFilterList != nil {
		in, out := &in.BcFilterList, &out.BcFilterList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BssTransition != nil {
		in, out := &in.BssTransition, &out.BssTransition
		*out = new(bool)
		**out = **in
	}
	if in.Dtim6E != nil {
		in, out := &in.Dtim6E, &out.Dtim6E
		*out = new(float64)
		**out = **in
	}
	if in.DtimMode != nil {
		in, out := &in.DtimMode, &out.DtimMode
		*out = new(string)
		**out = **in
	}
	if in.DtimNa != nil {
		in, out := &in.DtimNa, &out.DtimNa
		*out = new(float64)
		**out = **in
	}
	if in.DtimNg != nil {
		in, out := &in.DtimNg, &out.DtimNg
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnhancedIot != nil {
		in, out := &in.EnhancedIot, &out.EnhancedIot
		*out = new(bool)
		**out = **in
	}
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekey != nil {
		in, out := &in.GroupRekey, &out.GroupRekey
		*out = new(float64)
		**out = **in
	}
	if in.HideSsid != nil {
		in, out := &in.HideSsid, &out.HideSsid
		*out = new(bool)
		**out = **in
	}
	if in.Hotspot2ConfEnabled != nil {
		in, out := &in.Hotspot2ConfEnabled, &out.Hotspot2ConfEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IappEnabled != nil {
		in, out := &in.IappEnabled, &out.IappEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsGuest != nil {
		in, out := &in.IsGuest, &out.IsGuest
		*out = new(bool)
		**out = **in
	}
	if in.L2Isolation != nil {
		in, out := &in.L2Isolation, &out.L2Isolation
		*out = new(bool)
		**out = **in
	}
	if in.MacFilter != nil {
		in, out := &in.MacFilter, &out.MacFilter
		*out = new(MacFilterObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.MinimumDataRate2GKbps != nil {
		in, out := &in.MinimumDataRate2GKbps, &out.MinimumDataRate2GKbps
		*out = new(float64)
		**out = **in
	}
	if in.MinimumDataRate5GKbps != nil {
		in, out := &in.MinimumDataRate5GKbps, &out.MinimumDataRate5GKbps
		*out = new(float64)
		**out = **in
	}
	if in.MinrateSettingPreference != nil {
		in, out := &in.MinrateSettingPreference, &out.MinrateSettingPreference
		*out = new(string)
		**out = **in
	}
	if in.MloEnabled != nil {
		in, out := &in.MloEnabled, &out.MloEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MulticastEnhance != nil {
		in, out := &in.MulticastEnhance, &out.MulticastEnhance
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NasIdentifierType != nil {
		in, out := &in.NasIdentifierType, &out.NasIdentifierType
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.No2GhzOui != nil {
		in, out := &in.No2GhzOui, &out.No2GhzOui
		*out = new(bool)
		**out = **in
	}
	if in.PmfMode != nil {
		in, out := &in.PmfMode, &out.PmfMode
		*out = new(string)
		**out = **in
	}
	if in.PrivatePresharedKeys != nil {
		in, out := &in.PrivatePresharedKeys, &out.PrivatePresharedKeys
		*out = make([]PrivatePresharedKeysObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrivatePresharedKeysEnabled != nil {
		in, out := &in.PrivatePresharedKeysEnabled, &out.PrivatePresharedKeysEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProxyArp != nil {
		in, out := &in.ProxyArp, &out.ProxyArp
		*out = new(bool)
		**out = **in
	}
	if in.RadiusMacAuthEnabled != nil {
		in, out := &in.RadiusMacAuthEnabled, &out.RadiusMacAuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RadiusProfileID != nil {
		in, out := &in.RadiusProfileID, &out.RadiusProfileID
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = make([]ScheduleObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Uapsd != nil {
		in, out := &in.Uapsd, &out.Uapsd
		*out = new(bool)
		**out = **in
	}
	if in.UserGroupID != nil {
		in, out := &in.UserGroupID, &out.UserGroupID
		*out = new(string)
		**out = **in
	}
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(float64)
		**out = **in
	}
	if in.VlanEnabled != nil {
		in, out := &in.VlanEnabled, &out.VlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.WlanBand != nil {
		in, out := &in.WlanBand, &out.WlanBand
		*out = new(string)
		**out = **in
	}
	if in.WlanBands != nil {
		in, out := &in.WlanBands, &out.WlanBands
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Wpa3Enhanced192 != nil {
		in, out := &in.Wpa3Enhanced192, &out.Wpa3Enhanced192
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3FastRoaming != nil {
		in, out := &in.Wpa3FastRoaming, &out.Wpa3FastRoaming
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3Support != nil {
		in, out := &in.Wpa3Support, &out.Wpa3Support
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3Transition != nil {
		in, out := &in.Wpa3Transition, &out.Wpa3Transition
		*out = new(bool)
		**out = **in
	}
	if in.WpaEnc != nil {
		in, out := &in.WpaEnc, &out.WpaEnc
		*out = new(string)
		**out = **in
	}
	if in.WpaMode != nil {
		in, out := &in.WpaMode, &out.WpaMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WlanObservation.
func (in *WlanObservation) DeepCopy() *WlanObservation {
	if in == nil {
		return nil
	}
	out := new(WlanObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WlanParameters) DeepCopyInto(out *WlanParameters) {
	*out = *in
	if in.ApGroupIds != nil {
		in, out := &in.ApGroupIds, &out.ApGroupIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ApGroupMode != nil {
		in, out := &in.ApGroupMode, &out.ApGroupMode
		*out = new(string)
		**out = **in
	}
	if in.BcFilterList != nil {
		in, out := &in.BcFilterList, &out.BcFilterList
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.BssTransition != nil {
		in, out := &in.BssTransition, &out.BssTransition
		*out = new(bool)
		**out = **in
	}
	if in.Dtim6E != nil {
		in, out := &in.Dtim6E, &out.Dtim6E
		*out = new(float64)
		**out = **in
	}
	if in.DtimMode != nil {
		in, out := &in.DtimMode, &out.DtimMode
		*out = new(string)
		**out = **in
	}
	if in.DtimNa != nil {
		in, out := &in.DtimNa, &out.DtimNa
		*out = new(float64)
		**out = **in
	}
	if in.DtimNg != nil {
		in, out := &in.DtimNg, &out.DtimNg
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnhancedIot != nil {
		in, out := &in.EnhancedIot, &out.EnhancedIot
		*out = new(bool)
		**out = **in
	}
	if in.FastRoamingEnabled != nil {
		in, out := &in.FastRoamingEnabled, &out.FastRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupRekey != nil {
		in, out := &in.GroupRekey, &out.GroupRekey
		*out = new(float64)
		**out = **in
	}
	if in.HideSsid != nil {
		in, out := &in.HideSsid, &out.HideSsid
		*out = new(bool)
		**out = **in
	}
	if in.Hotspot2ConfEnabled != nil {
		in, out := &in.Hotspot2ConfEnabled, &out.Hotspot2ConfEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IappEnabled != nil {
		in, out := &in.IappEnabled, &out.IappEnabled
		*out = new(bool)
		**out = **in
	}
	if in.IsGuest != nil {
		in, out := &in.IsGuest, &out.IsGuest
		*out = new(bool)
		**out = **in
	}
	if in.L2Isolation != nil {
		in, out := &in.L2Isolation, &out.L2Isolation
		*out = new(bool)
		**out = **in
	}
	if in.MacFilter != nil {
		in, out := &in.MacFilter, &out.MacFilter
		*out = new(MacFilterParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.MinimumDataRate2GKbps != nil {
		in, out := &in.MinimumDataRate2GKbps, &out.MinimumDataRate2GKbps
		*out = new(float64)
		**out = **in
	}
	if in.MinimumDataRate5GKbps != nil {
		in, out := &in.MinimumDataRate5GKbps, &out.MinimumDataRate5GKbps
		*out = new(float64)
		**out = **in
	}
	if in.MinrateSettingPreference != nil {
		in, out := &in.MinrateSettingPreference, &out.MinrateSettingPreference
		*out = new(string)
		**out = **in
	}
	if in.MloEnabled != nil {
		in, out := &in.MloEnabled, &out.MloEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MulticastEnhance != nil {
		in, out := &in.MulticastEnhance, &out.MulticastEnhance
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NasIdentifierType != nil {
		in, out := &in.NasIdentifierType, &out.NasIdentifierType
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.No2GhzOui != nil {
		in, out := &in.No2GhzOui, &out.No2GhzOui
		*out = new(bool)
		**out = **in
	}
	if in.PassphraseSecretRef != nil {
		in, out := &in.PassphraseSecretRef, &out.PassphraseSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.PassphraseWoSecretRef != nil {
		in, out := &in.PassphraseWoSecretRef, &out.PassphraseWoSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
	if in.PmfMode != nil {
		in, out := &in.PmfMode, &out.PmfMode
		*out = new(string)
		**out = **in
	}
	if in.PrivatePresharedKeys != nil {
		in, out := &in.PrivatePresharedKeys, &out.PrivatePresharedKeys
		*out = make([]PrivatePresharedKeysParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PrivatePresharedKeysEnabled != nil {
		in, out := &in.PrivatePresharedKeysEnabled, &out.PrivatePresharedKeysEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ProxyArp != nil {
		in, out := &in.ProxyArp, &out.ProxyArp
		*out = new(bool)
		**out = **in
	}
	if in.RadiusMacAuthEnabled != nil {
		in, out := &in.RadiusMacAuthEnabled, &out.RadiusMacAuthEnabled
		*out = new(bool)
		**out = **in
	}
	if in.RadiusProfileID != nil {
		in, out := &in.RadiusProfileID, &out.RadiusProfileID
		*out = new(string)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = make([]ScheduleParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Uapsd != nil {
		in, out := &in.Uapsd, &out.Uapsd
		*out = new(bool)
		**out = **in
	}
	if in.UserGroupID != nil {
		in, out := &in.UserGroupID, &out.UserGroupID
		*out = new(string)
		**out = **in
	}
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(float64)
		**out = **in
	}
	if in.VlanEnabled != nil {
		in, out := &in.VlanEnabled, &out.VlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.WlanBand != nil {
		in, out := &in.WlanBand, &out.WlanBand
		*out = new(string)
		**out = **in
	}
	if in.WlanBands != nil {
		in, out := &in.WlanBands, &out.WlanBands
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Wpa3Enhanced192 != nil {
		in, out := &in.Wpa3Enhanced192, &out.Wpa3Enhanced192
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3FastRoaming != nil {
		in, out := &in.Wpa3FastRoaming, &out.Wpa3FastRoaming
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3Support != nil {
		in, out := &in.Wpa3Support, &out.Wpa3Support
		*out = new(bool)
		**out = **in
	}
	if in.Wpa3Transition != nil {
		in, out := &in.Wpa3Transition, &out.Wpa3Transition
		*out = new(bool)
		**out = **in
	}
	if in.WpaEnc != nil {
		in, out := &in.WpaEnc, &out.WpaEnc
		*out = new(string)
		**out = **in
	}
	if in.WpaMode != nil {
		in, out := &in.WpaMode, &out.WpaMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WlanParameters.
func (in *WlanParameters) DeepCopy() *WlanParameters {
	if in == nil {
		return nil
	}
	out := new(WlanParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WlanSpec) DeepCopyInto(out *WlanSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WlanSpec.
func (in *WlanSpec) DeepCopy() *WlanSpec {
	if in == nil {
		return nil
	}
	out := new(WlanSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WlanStatus) DeepCopyInto(out *WlanStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WlanStatus.
func (in *WlanStatus) DeepCopy() *WlanStatus {
	if in == nil {
		return nil
	}
	out := new(WlanStatus)
	in.DeepCopyInto(out)
	return out
}
