//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcctServerInitParameters) DeepCopyInto(out *AcctServerInitParameters) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	in.SecretSecretRef.DeepCopyInto(&out.SecretSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcctServerInitParameters.
func (in *AcctServerInitParameters) DeepCopy() *AcctServerInitParameters {
	if in == nil {
		return nil
	}
	out := new(AcctServerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcctServerObservation) DeepCopyInto(out *AcctServerObservation) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcctServerObservation.
func (in *AcctServerObservation) DeepCopy() *AcctServerObservation {
	if in == nil {
		return nil
	}
	out := new(AcctServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcctServerParameters) DeepCopyInto(out *AcctServerParameters) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	in.SecretSecretRef.DeepCopyInto(&out.SecretSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcctServerParameters.
func (in *AcctServerParameters) DeepCopy() *AcctServerParameters {
	if in == nil {
		return nil
	}
	out := new(AcctServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthServerInitParameters) DeepCopyInto(out *AuthServerInitParameters) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	in.SecretSecretRef.DeepCopyInto(&out.SecretSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthServerInitParameters.
func (in *AuthServerInitParameters) DeepCopy() *AuthServerInitParameters {
	if in == nil {
		return nil
	}
	out := new(AuthServerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthServerObservation) DeepCopyInto(out *AuthServerObservation) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthServerObservation.
func (in *AuthServerObservation) DeepCopy() *AuthServerObservation {
	if in == nil {
		return nil
	}
	out := new(AuthServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthServerParameters) DeepCopyInto(out *AuthServerParameters) {
	*out = *in
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(float64)
		**out = **in
	}
	in.SecretSecretRef.DeepCopyInto(&out.SecretSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthServerParameters.
func (in *AuthServerParameters) DeepCopy() *AuthServerParameters {
	if in == nil {
		return nil
	}
	out := new(AuthServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Profile) DeepCopyInto(out *Profile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Profile.
func (in *Profile) DeepCopy() *Profile {
	if in == nil {
		return nil
	}
	out := new(Profile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Profile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileInitParameters) DeepCopyInto(out *ProfileInitParameters) {
	*out = *in
	if in.AccountingEnabled != nil {
		in, out := &in.AccountingEnabled, &out.AccountingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AcctServer != nil {
		in, out := &in.AcctServer, &out.AcctServer
		*out = make([]AcctServerInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthServer != nil {
		in, out := &in.AuthServer, &out.AuthServer
		*out = make([]AuthServerInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InterimUpdateEnabled != nil {
		in, out := &in.InterimUpdateEnabled, &out.InterimUpdateEnabled
		*out = new(bool)
		**out = **in
	}
	if in.InterimUpdateInterval != nil {
		in, out := &in.InterimUpdateInterval, &out.InterimUpdateInterval
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.UseUsgAcctServer != nil {
		in, out := &in.UseUsgAcctServer, &out.UseUsgAcctServer
		*out = new(bool)
		**out = **in
	}
	if in.UseUsgAuthServer != nil {
		in, out := &in.UseUsgAuthServer, &out.UseUsgAuthServer
		*out = new(bool)
		**out = **in
	}
	if in.VlanEnabled != nil {
		in, out := &in.VlanEnabled, &out.VlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.VlanWlanMode != nil {
		in, out := &in.VlanWlanMode, &out.VlanWlanMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileInitParameters.
func (in *ProfileInitParameters) DeepCopy() *ProfileInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProfileInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileList) DeepCopyInto(out *ProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Profile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileList.
func (in *ProfileList) DeepCopy() *ProfileList {
	if in == nil {
		return nil
	}
	out := new(ProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileObservation) DeepCopyInto(out *ProfileObservation) {
	*out = *in
	if in.AccountingEnabled != nil {
		in, out := &in.AccountingEnabled, &out.AccountingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AcctServer != nil {
		in, out := &in.AcctServer, &out.AcctServer
		*out = make([]AcctServerObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthServer != nil {
		in, out := &in.AuthServer, &out.AuthServer
		*out = make([]AuthServerObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InterimUpdateEnabled != nil {
		in, out := &in.InterimUpdateEnabled, &out.InterimUpdateEnabled
		*out = new(bool)
		**out = **in
	}
	if in.InterimUpdateInterval != nil {
		in, out := &in.InterimUpdateInterval, &out.InterimUpdateInterval
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.UseUsgAcctServer != nil {
		in, out := &in.UseUsgAcctServer, &out.UseUsgAcctServer
		*out = new(bool)
		**out = **in
	}
	if in.UseUsgAuthServer != nil {
		in, out := &in.UseUsgAuthServer, &out.UseUsgAuthServer
		*out = new(bool)
		**out = **in
	}
	if in.VlanEnabled != nil {
		in, out := &in.VlanEnabled, &out.VlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.VlanWlanMode != nil {
		in, out := &in.VlanWlanMode, &out.VlanWlanMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileObservation.
func (in *ProfileObservation) DeepCopy() *ProfileObservation {
	if in == nil {
		return nil
	}
	out := new(ProfileObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileParameters) DeepCopyInto(out *ProfileParameters) {
	*out = *in
	if in.AccountingEnabled != nil {
		in, out := &in.AccountingEnabled, &out.AccountingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AcctServer != nil {
		in, out := &in.AcctServer, &out.AcctServer
		*out = make([]AcctServerParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AuthServer != nil {
		in, out := &in.AuthServer, &out.AuthServer
		*out = make([]AuthServerParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.InterimUpdateEnabled != nil {
		in, out := &in.InterimUpdateEnabled, &out.InterimUpdateEnabled
		*out = new(bool)
		**out = **in
	}
	if in.InterimUpdateInterval != nil {
		in, out := &in.InterimUpdateInterval, &out.InterimUpdateInterval
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.UseUsgAcctServer != nil {
		in, out := &in.UseUsgAcctServer, &out.UseUsgAcctServer
		*out = new(bool)
		**out = **in
	}
	if in.UseUsgAuthServer != nil {
		in, out := &in.UseUsgAuthServer, &out.UseUsgAuthServer
		*out = new(bool)
		**out = **in
	}
	if in.VlanEnabled != nil {
		in, out := &in.VlanEnabled, &out.VlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.VlanWlanMode != nil {
		in, out := &in.VlanWlanMode, &out.VlanWlanMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileParameters.
func (in *ProfileParameters) DeepCopy() *ProfileParameters {
	if in == nil {
		return nil
	}
	out := new(ProfileParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileSpec) DeepCopyInto(out *ProfileSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileSpec.
func (in *ProfileSpec) DeepCopy() *ProfileSpec {
	if in == nil {
		return nil
	}
	out := new(ProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileStatus) DeepCopyInto(out *ProfileStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileStatus.
func (in *ProfileStatus) DeepCopy() *ProfileStatus {
	if in == nil {
		return nil
	}
	out := new(ProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsInitParameters) DeepCopyInto(out *TimeoutsInitParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsInitParameters.
func (in *TimeoutsInitParameters) DeepCopy() *TimeoutsInitParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsObservation) DeepCopyInto(out *TimeoutsObservation) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsObservation.
func (in *TimeoutsObservation) DeepCopy() *TimeoutsObservation {
	if in == nil {
		return nil
	}
	out := new(TimeoutsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsParameters) DeepCopyInto(out *TimeoutsParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsParameters.
func (in *TimeoutsParameters) DeepCopy() *TimeoutsParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *User) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserInitParameters) DeepCopyInto(out *UserInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(UserTimeoutsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelConfigType != nil {
		in, out := &in.TunnelConfigType, &out.TunnelConfigType
		*out = new(string)
		**out = **in
	}
	if in.TunnelMediumType != nil {
		in, out := &in.TunnelMediumType, &out.TunnelMediumType
		*out = new(float64)
		**out = **in
	}
	if in.TunnelType != nil {
		in, out := &in.TunnelType, &out.TunnelType
		*out = new(float64)
		**out = **in
	}
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserInitParameters.
func (in *UserInitParameters) DeepCopy() *UserInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserList) DeepCopyInto(out *UserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserList.
func (in *UserList) DeepCopy() *UserList {
	if in == nil {
		return nil
	}
	out := new(UserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserObservation) DeepCopyInto(out *UserObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(UserTimeoutsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelConfigType != nil {
		in, out := &in.TunnelConfigType, &out.TunnelConfigType
		*out = new(string)
		**out = **in
	}
	if in.TunnelMediumType != nil {
		in, out := &in.TunnelMediumType, &out.TunnelMediumType
		*out = new(float64)
		**out = **in
	}
	if in.TunnelType != nil {
		in, out := &in.TunnelType, &out.TunnelType
		*out = new(float64)
		**out = **in
	}
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserObservation.
func (in *UserObservation) DeepCopy() *UserObservation {
	if in == nil {
		return nil
	}
	out := new(UserObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserParameters) DeepCopyInto(out *UserParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(UserTimeoutsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.TunnelConfigType != nil {
		in, out := &in.TunnelConfigType, &out.TunnelConfigType
		*out = new(string)
		**out = **in
	}
	if in.TunnelMediumType != nil {
		in, out := &in.TunnelMediumType, &out.TunnelMediumType
		*out = new(float64)
		**out = **in
	}
	if in.TunnelType != nil {
		in, out := &in.TunnelType, &out.TunnelType
		*out = new(float64)
		**out = **in
	}
	if in.Vlan != nil {
		in, out := &in.Vlan, &out.Vlan
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserParameters.
func (in *UserParameters) DeepCopy() *UserParameters {
	if in == nil {
		return nil
	}
	out := new(UserParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSpec) DeepCopyInto(out *UserSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSpec.
func (in *UserSpec) DeepCopy() *UserSpec {
	if in == nil {
		return nil
	}
	out := new(UserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserStatus) DeepCopyInto(out *UserStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserStatus.
func (in *UserStatus) DeepCopy() *UserStatus {
	if in == nil {
		return nil
	}
	out := new(UserStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTimeoutsInitParameters) DeepCopyInto(out *UserTimeoutsInitParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTimeoutsInitParameters.
func (in *UserTimeoutsInitParameters) DeepCopy() *UserTimeoutsInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserTimeoutsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTimeoutsObservation) DeepCopyInto(out *UserTimeoutsObservation) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTimeoutsObservation.
func (in *UserTimeoutsObservation) DeepCopy() *UserTimeoutsObservation {
	if in == nil {
		return nil
	}
	out := new(UserTimeoutsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserTimeoutsParameters) DeepCopyInto(out *UserTimeoutsParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserTimeoutsParameters.
func (in *UserTimeoutsParameters) DeepCopy() *UserTimeoutsParameters {
	if in == nil {
		return nil
	}
	out := new(UserTimeoutsParameters)
	in.DeepCopyInto(out)
	return out
}
