// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AcctServerInitParameters struct {

	// IP address of accounting service server.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Port of accounting service.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Shared secret for accounting server.
	SecretSecretRef v1.SecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type AcctServerObservation struct {

	// IP address of accounting service server.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Port of accounting service.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type AcctServerParameters struct {

	// IP address of accounting service server.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip" tf:"ip,omitempty"`

	// Port of accounting service.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Shared secret for accounting server.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.SecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type AuthServerInitParameters struct {

	// IP address of authentication service server.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Port of authentication service.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Shared secret for authentication server.
	SecretSecretRef v1.SecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type AuthServerObservation struct {

	// IP address of authentication service server.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Port of authentication service.
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`
}

type AuthServerParameters struct {

	// IP address of authentication service server.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip" tf:"ip,omitempty"`

	// Port of authentication service.
	// +kubebuilder:validation:Optional
	Port *float64 `json:"port,omitempty" tf:"port,omitempty"`

	// Shared secret for authentication server.
	// +kubebuilder:validation:Optional
	SecretSecretRef v1.SecretKeySelector `json:"secretSecretRef" tf:"-"`
}

type ProfileInitParameters struct {

	// Specifies whether to use RADIUS accounting.
	AccountingEnabled *bool `json:"accountingEnabled,omitempty" tf:"accounting_enabled,omitempty"`

	// RADIUS accounting servers.
	AcctServer []AcctServerInitParameters `json:"acctServer,omitempty" tf:"acct_server,omitempty"`

	// RADIUS authentication servers.
	AuthServer []AuthServerInitParameters `json:"authServer,omitempty" tf:"auth_server,omitempty"`

	// Specifies whether to use interim_update.
	InterimUpdateEnabled *bool `json:"interimUpdateEnabled,omitempty" tf:"interim_update_enabled,omitempty"`

	// Specifies the RADIUS interim update interval, as a Go duration string (e.g. `1h`, `3600s`). Defaults to `1h0m0s`.
	InterimUpdateInterval *string `json:"interimUpdateInterval,omitempty" tf:"interim_update_interval,omitempty"`

	// The name of the profile.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the site to associate the settings with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Timeouts *TimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// Specifies whether to use usg as a RADIUS accounting server.
	UseUsgAcctServer *bool `json:"useUsgAcctServer,omitempty" tf:"use_usg_acct_server,omitempty"`

	// Specifies whether to use usg as a RADIUS authentication server.
	UseUsgAuthServer *bool `json:"useUsgAuthServer,omitempty" tf:"use_usg_auth_server,omitempty"`

	// Specifies whether to use vlan on wired connections.
	VlanEnabled *bool `json:"vlanEnabled,omitempty" tf:"vlan_enabled,omitempty"`

	// Specifies whether to use vlan on wireless connections. Must be one of `disabled`, `optional`, or `required`.
	VlanWlanMode *string `json:"vlanWlanMode,omitempty" tf:"vlan_wlan_mode,omitempty"`
}

type ProfileObservation struct {

	// Specifies whether to use RADIUS accounting.
	AccountingEnabled *bool `json:"accountingEnabled,omitempty" tf:"accounting_enabled,omitempty"`

	// RADIUS accounting servers.
	AcctServer []AcctServerObservation `json:"acctServer,omitempty" tf:"acct_server,omitempty"`

	// RADIUS authentication servers.
	AuthServer []AuthServerObservation `json:"authServer,omitempty" tf:"auth_server,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies whether to use interim_update.
	InterimUpdateEnabled *bool `json:"interimUpdateEnabled,omitempty" tf:"interim_update_enabled,omitempty"`

	// Specifies the RADIUS interim update interval, as a Go duration string (e.g. `1h`, `3600s`). Defaults to `1h0m0s`.
	InterimUpdateInterval *string `json:"interimUpdateInterval,omitempty" tf:"interim_update_interval,omitempty"`

	// The name of the profile.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the site to associate the settings with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Timeouts *TimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// Specifies whether to use usg as a RADIUS accounting server.
	UseUsgAcctServer *bool `json:"useUsgAcctServer,omitempty" tf:"use_usg_acct_server,omitempty"`

	// Specifies whether to use usg as a RADIUS authentication server.
	UseUsgAuthServer *bool `json:"useUsgAuthServer,omitempty" tf:"use_usg_auth_server,omitempty"`

	// Specifies whether to use vlan on wired connections.
	VlanEnabled *bool `json:"vlanEnabled,omitempty" tf:"vlan_enabled,omitempty"`

	// Specifies whether to use vlan on wireless connections. Must be one of `disabled`, `optional`, or `required`.
	VlanWlanMode *string `json:"vlanWlanMode,omitempty" tf:"vlan_wlan_mode,omitempty"`
}

type ProfileParameters struct {

	// Specifies whether to use RADIUS accounting.
	// +kubebuilder:validation:Optional
	AccountingEnabled *bool `json:"accountingEnabled,omitempty" tf:"accounting_enabled,omitempty"`

	// RADIUS accounting servers.
	// +kubebuilder:validation:Optional
	AcctServer []AcctServerParameters `json:"acctServer,omitempty" tf:"acct_server,omitempty"`

	// RADIUS authentication servers.
	// +kubebuilder:validation:Optional
	AuthServer []AuthServerParameters `json:"authServer,omitempty" tf:"auth_server,omitempty"`

	// Specifies whether to use interim_update.
	// +kubebuilder:validation:Optional
	InterimUpdateEnabled *bool `json:"interimUpdateEnabled,omitempty" tf:"interim_update_enabled,omitempty"`

	// Specifies the RADIUS interim update interval, as a Go duration string (e.g. `1h`, `3600s`). Defaults to `1h0m0s`.
	// +kubebuilder:validation:Optional
	InterimUpdateInterval *string `json:"interimUpdateInterval,omitempty" tf:"interim_update_interval,omitempty"`

	// The name of the profile.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The name of the site to associate the settings with.
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *TimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// Specifies whether to use usg as a RADIUS accounting server.
	// +kubebuilder:validation:Optional
	UseUsgAcctServer *bool `json:"useUsgAcctServer,omitempty" tf:"use_usg_acct_server,omitempty"`

	// Specifies whether to use usg as a RADIUS authentication server.
	// +kubebuilder:validation:Optional
	UseUsgAuthServer *bool `json:"useUsgAuthServer,omitempty" tf:"use_usg_auth_server,omitempty"`

	// Specifies whether to use vlan on wired connections.
	// +kubebuilder:validation:Optional
	VlanEnabled *bool `json:"vlanEnabled,omitempty" tf:"vlan_enabled,omitempty"`

	// Specifies whether to use vlan on wireless connections. Must be one of `disabled`, `optional`, or `required`.
	// +kubebuilder:validation:Optional
	VlanWlanMode *string `json:"vlanWlanMode,omitempty" tf:"vlan_wlan_mode,omitempty"`
}

type TimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

// ProfileSpec defines the desired state of Profile
type ProfileSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProfileParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProfileInitParameters `json:"initProvider,omitempty"`
}

// ProfileStatus defines the observed state of Profile.
type ProfileStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProfileObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Profile is the Schema for the Profiles API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,unifi}
type Profile struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProfileSpec   `json:"spec"`
	Status ProfileStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProfileList contains a list of Profiles
type ProfileList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Profile `json:"items"`
}

// Repository type metadata.
var (
	Profile_Kind             = "Profile"
	Profile_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Profile_Kind}.String()
	Profile_KindAPIVersion   = Profile_Kind + "." + CRDGroupVersion.String()
	Profile_GroupVersionKind = CRDGroupVersion.WithKind(Profile_Kind)
)

func init() {
	SchemeBuilder.Register(&Profile{}, &ProfileList{})
}
