// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

// Package namespaced contains Kubernetes API for the provider.
package namespaced

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/account/v1alpha1"
	v1alpha1device "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/device/v1alpha1"
	v1alpha1dns "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/dns/v1alpha1"
	v1alpha1firewall "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/firewall/v1alpha1"
	v1alpha1network "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/network/v1alpha1"
	v1alpha1port "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/port/v1alpha1"
	v1alpha1radius "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/radius/v1alpha1"
	v1alpha1route "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/route/v1alpha1"
	v1alpha1setting "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/setting/v1alpha1"
	v1alpha1site "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/site/v1alpha1"
	v1alpha1namespaced "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/v1alpha1"
	v1beta1 "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/v1beta1"
	v1alpha1vpn "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/vpn/v1alpha1"
	v1alpha1wlan "github.com/devantler-tech/provider-upjet-unifi/apis/namespaced/wlan/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1device.SchemeBuilder.AddToScheme,
		v1alpha1dns.SchemeBuilder.AddToScheme,
		v1alpha1firewall.SchemeBuilder.AddToScheme,
		v1alpha1network.SchemeBuilder.AddToScheme,
		v1alpha1port.SchemeBuilder.AddToScheme,
		v1alpha1radius.SchemeBuilder.AddToScheme,
		v1alpha1route.SchemeBuilder.AddToScheme,
		v1alpha1setting.SchemeBuilder.AddToScheme,
		v1alpha1site.SchemeBuilder.AddToScheme,
		v1alpha1namespaced.SchemeBuilder.AddToScheme,
		v1beta1.SchemeBuilder.AddToScheme,
		v1alpha1vpn.SchemeBuilder.AddToScheme,
		v1alpha1wlan.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
