//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Client) DeepCopyInto(out *Client) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Client.
func (in *Client) DeepCopy() *Client {
	if in == nil {
		return nil
	}
	out := new(Client)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Client) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientInitParameters) DeepCopyInto(out *ClientInitParameters) {
	*out = *in
	if in.AllowExisting != nil {
		in, out := &in.AllowExisting, &out.AllowExisting
		*out = new(bool)
		**out = **in
	}
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FixedApMac != nil {
		in, out := &in.FixedApMac, &out.FixedApMac
		*out = new(string)
		**out = **in
	}
	if in.FixedIP != nil {
		in, out := &in.FixedIP, &out.FixedIP
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LocalDNSRecord != nil {
		in, out := &in.LocalDNSRecord, &out.LocalDNSRecord
		*out = new(string)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.QosRate != nil {
		in, out := &in.QosRate, &out.QosRate
		*out = new(QosRateInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.SkipForgetOnDestroy != nil {
		in, out := &in.SkipForgetOnDestroy, &out.SkipForgetOnDestroy
		*out = new(bool)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientInitParameters.
func (in *ClientInitParameters) DeepCopy() *ClientInitParameters {
	if in == nil {
		return nil
	}
	out := new(ClientInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientList) DeepCopyInto(out *ClientList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Client, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientList.
func (in *ClientList) DeepCopy() *ClientList {
	if in == nil {
		return nil
	}
	out := new(ClientList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ClientList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientObservation) DeepCopyInto(out *ClientObservation) {
	*out = *in
	if in.AllowExisting != nil {
		in, out := &in.AllowExisting, &out.AllowExisting
		*out = new(bool)
		**out = **in
	}
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FixedApMac != nil {
		in, out := &in.FixedApMac, &out.FixedApMac
		*out = new(string)
		**out = **in
	}
	if in.FixedIP != nil {
		in, out := &in.FixedIP, &out.FixedIP
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LastIP != nil {
		in, out := &in.LastIP, &out.LastIP
		*out = new(string)
		**out = **in
	}
	if in.LocalDNSRecord != nil {
		in, out := &in.LocalDNSRecord, &out.LocalDNSRecord
		*out = new(string)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.QosRate != nil {
		in, out := &in.QosRate, &out.QosRate
		*out = new(QosRateObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.SkipForgetOnDestroy != nil {
		in, out := &in.SkipForgetOnDestroy, &out.SkipForgetOnDestroy
		*out = new(bool)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientObservation.
func (in *ClientObservation) DeepCopy() *ClientObservation {
	if in == nil {
		return nil
	}
	out := new(ClientObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientParameters) DeepCopyInto(out *ClientParameters) {
	*out = *in
	if in.AllowExisting != nil {
		in, out := &in.AllowExisting, &out.AllowExisting
		*out = new(bool)
		**out = **in
	}
	if in.Blocked != nil {
		in, out := &in.Blocked, &out.Blocked
		*out = new(bool)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.FixedApMac != nil {
		in, out := &in.FixedApMac, &out.FixedApMac
		*out = new(string)
		**out = **in
	}
	if in.FixedIP != nil {
		in, out := &in.FixedIP, &out.FixedIP
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.LocalDNSRecord != nil {
		in, out := &in.LocalDNSRecord, &out.LocalDNSRecord
		*out = new(string)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NetworkID != nil {
		in, out := &in.NetworkID, &out.NetworkID
		*out = new(string)
		**out = **in
	}
	if in.Note != nil {
		in, out := &in.Note, &out.Note
		*out = new(string)
		**out = **in
	}
	if in.QosRate != nil {
		in, out := &in.QosRate, &out.QosRate
		*out = new(QosRateParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.SkipForgetOnDestroy != nil {
		in, out := &in.SkipForgetOnDestroy, &out.SkipForgetOnDestroy
		*out = new(bool)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(TimeoutsParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientParameters.
func (in *ClientParameters) DeepCopy() *ClientParameters {
	if in == nil {
		return nil
	}
	out := new(ClientParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientSpec) DeepCopyInto(out *ClientSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientSpec.
func (in *ClientSpec) DeepCopy() *ClientSpec {
	if in == nil {
		return nil
	}
	out := new(ClientSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClientStatus) DeepCopyInto(out *ClientStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClientStatus.
func (in *ClientStatus) DeepCopy() *ClientStatus {
	if in == nil {
		return nil
	}
	out := new(ClientStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigNetworkInitParameters) DeepCopyInto(out *ConfigNetworkInitParameters) {
	*out = *in
	if in.BondingEnabled != nil {
		in, out := &in.BondingEnabled, &out.BondingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Dns1 != nil {
		in, out := &in.Dns1, &out.Dns1
		*out = new(string)
		**out = **in
	}
	if in.Dns2 != nil {
		in, out := &in.Dns2, &out.Dns2
		*out = new(string)
		**out = **in
	}
	if in.Dnssuffix != nil {
		in, out := &in.Dnssuffix, &out.Dnssuffix
		*out = new(string)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Netmask != nil {
		in, out := &in.Netmask, &out.Netmask
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigNetworkInitParameters.
func (in *ConfigNetworkInitParameters) DeepCopy() *ConfigNetworkInitParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigNetworkInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigNetworkObservation) DeepCopyInto(out *ConfigNetworkObservation) {
	*out = *in
	if in.BondingEnabled != nil {
		in, out := &in.BondingEnabled, &out.BondingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Dns1 != nil {
		in, out := &in.Dns1, &out.Dns1
		*out = new(string)
		**out = **in
	}
	if in.Dns2 != nil {
		in, out := &in.Dns2, &out.Dns2
		*out = new(string)
		**out = **in
	}
	if in.Dnssuffix != nil {
		in, out := &in.Dnssuffix, &out.Dnssuffix
		*out = new(string)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Netmask != nil {
		in, out := &in.Netmask, &out.Netmask
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigNetworkObservation.
func (in *ConfigNetworkObservation) DeepCopy() *ConfigNetworkObservation {
	if in == nil {
		return nil
	}
	out := new(ConfigNetworkObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigNetworkParameters) DeepCopyInto(out *ConfigNetworkParameters) {
	*out = *in
	if in.BondingEnabled != nil {
		in, out := &in.BondingEnabled, &out.BondingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Dns1 != nil {
		in, out := &in.Dns1, &out.Dns1
		*out = new(string)
		**out = **in
	}
	if in.Dns2 != nil {
		in, out := &in.Dns2, &out.Dns2
		*out = new(string)
		**out = **in
	}
	if in.Dnssuffix != nil {
		in, out := &in.Dnssuffix, &out.Dnssuffix
		*out = new(string)
		**out = **in
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.Netmask != nil {
		in, out := &in.Netmask, &out.Netmask
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigNetworkParameters.
func (in *ConfigNetworkParameters) DeepCopy() *ConfigNetworkParameters {
	if in == nil {
		return nil
	}
	out := new(ConfigNetworkParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Device) DeepCopyInto(out *Device) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Device.
func (in *Device) DeepCopy() *Device {
	if in == nil {
		return nil
	}
	out := new(Device)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Device) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceInitParameters) DeepCopyInto(out *DeviceInitParameters) {
	*out = *in
	if in.AllowAdoption != nil {
		in, out := &in.AllowAdoption, &out.AllowAdoption
		*out = new(bool)
		**out = **in
	}
	if in.BandsteeringMode != nil {
		in, out := &in.BandsteeringMode, &out.BandsteeringMode
		*out = new(string)
		**out = **in
	}
	if in.ConfigNetwork != nil {
		in, out := &in.ConfigNetwork, &out.ConfigNetwork
		*out = new(ConfigNetworkInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.FlowctrlEnabled != nil {
		in, out := &in.FlowctrlEnabled, &out.FlowctrlEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ForgetOnDestroy != nil {
		in, out := &in.ForgetOnDestroy, &out.ForgetOnDestroy
		*out = new(bool)
		**out = **in
	}
	if in.JumboframeEnabled != nil {
		in, out := &in.JumboframeEnabled, &out.JumboframeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LcmBrightness != nil {
		in, out := &in.LcmBrightness, &out.LcmBrightness
		*out = new(float64)
		**out = **in
	}
	if in.LcmBrightnessOverride != nil {
		in, out := &in.LcmBrightnessOverride, &out.LcmBrightnessOverride
		*out = new(bool)
		**out = **in
	}
	if in.LcmIdleTimeout != nil {
		in, out := &in.LcmIdleTimeout, &out.LcmIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.LcmIdleTimeoutOverride != nil {
		in, out := &in.LcmIdleTimeoutOverride, &out.LcmIdleTimeoutOverride
		*out = new(bool)
		**out = **in
	}
	if in.LcmNightModeBegins != nil {
		in, out := &in.LcmNightModeBegins, &out.LcmNightModeBegins
		*out = new(string)
		**out = **in
	}
	if in.LcmNightModeEnds != nil {
		in, out := &in.LcmNightModeEnds, &out.LcmNightModeEnds
		*out = new(string)
		**out = **in
	}
	if in.LedOverride != nil {
		in, out := &in.LedOverride, &out.LedOverride
		*out = new(string)
		**out = **in
	}
	if in.LedOverrideColor != nil {
		in, out := &in.LedOverrideColor, &out.LedOverrideColor
		*out = new(string)
		**out = **in
	}
	if in.LedOverrideColorBrightness != nil {
		in, out := &in.LedOverrideColorBrightness, &out.LedOverrideColorBrightness
		*out = new(float64)
		**out = **in
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.MgmtNetworkID != nil {
		in, out := &in.MgmtNetworkID, &out.MgmtNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutdoorModeOverride != nil {
		in, out := &in.OutdoorModeOverride, &out.OutdoorModeOverride
		*out = new(string)
		**out = **in
	}
	if in.OutletEnabled != nil {
		in, out := &in.OutletEnabled, &out.OutletEnabled
		*out = new(bool)
		**out = **in
	}
	if in.OutletOverrides != nil {
		in, out := &in.OutletOverrides, &out.OutletOverrides
		*out = make([]OutletOverridesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PoeMode != nil {
		in, out := &in.PoeMode, &out.PoeMode
		*out = new(string)
		**out = **in
	}
	if in.PortOverride != nil {
		in, out := &in.PortOverride, &out.PortOverride
		*out = make([]PortOverrideInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RadioTable != nil {
		in, out := &in.RadioTable, &out.RadioTable
		*out = make([]RadioTableInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.StpPriority != nil {
		in, out := &in.StpPriority, &out.StpPriority
		*out = new(float64)
		**out = **in
	}
	if in.StpVersion != nil {
		in, out := &in.StpVersion, &out.StpVersion
		*out = new(string)
		**out = **in
	}
	if in.SwitchVlanEnabled != nil {
		in, out := &in.SwitchVlanEnabled, &out.SwitchVlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(DeviceTimeoutsInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Volume != nil {
		in, out := &in.Volume, &out.Volume
		*out = new(float64)
		**out = **in
	}
	if in.XBaresipPasswordSecretRef != nil {
		in, out := &in.XBaresipPasswordSecretRef, &out.XBaresipPasswordSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceInitParameters.
func (in *DeviceInitParameters) DeepCopy() *DeviceInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeviceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceList) DeepCopyInto(out *DeviceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Device, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceList.
func (in *DeviceList) DeepCopy() *DeviceList {
	if in == nil {
		return nil
	}
	out := new(DeviceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DeviceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceObservation) DeepCopyInto(out *DeviceObservation) {
	*out = *in
	if in.Adopted != nil {
		in, out := &in.Adopted, &out.Adopted
		*out = new(bool)
		**out = **in
	}
	if in.AllowAdoption != nil {
		in, out := &in.AllowAdoption, &out.AllowAdoption
		*out = new(bool)
		**out = **in
	}
	if in.BandsteeringMode != nil {
		in, out := &in.BandsteeringMode, &out.BandsteeringMode
		*out = new(string)
		**out = **in
	}
	if in.ConfigNetwork != nil {
		in, out := &in.ConfigNetwork, &out.ConfigNetwork
		*out = new(ConfigNetworkObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.FlowctrlEnabled != nil {
		in, out := &in.FlowctrlEnabled, &out.FlowctrlEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ForgetOnDestroy != nil {
		in, out := &in.ForgetOnDestroy, &out.ForgetOnDestroy
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.JumboframeEnabled != nil {
		in, out := &in.JumboframeEnabled, &out.JumboframeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LcmBrightness != nil {
		in, out := &in.LcmBrightness, &out.LcmBrightness
		*out = new(float64)
		**out = **in
	}
	if in.LcmBrightnessOverride != nil {
		in, out := &in.LcmBrightnessOverride, &out.LcmBrightnessOverride
		*out = new(bool)
		**out = **in
	}
	if in.LcmIdleTimeout != nil {
		in, out := &in.LcmIdleTimeout, &out.LcmIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.LcmIdleTimeoutOverride != nil {
		in, out := &in.LcmIdleTimeoutOverride, &out.LcmIdleTimeoutOverride
		*out = new(bool)
		**out = **in
	}
	if in.LcmNightModeBegins != nil {
		in, out := &in.LcmNightModeBegins, &out.LcmNightModeBegins
		*out = new(string)
		**out = **in
	}
	if in.LcmNightModeEnds != nil {
		in, out := &in.LcmNightModeEnds, &out.LcmNightModeEnds
		*out = new(string)
		**out = **in
	}
	if in.LedOverride != nil {
		in, out := &in.LedOverride, &out.LedOverride
		*out = new(string)
		**out = **in
	}
	if in.LedOverrideColor != nil {
		in, out := &in.LedOverrideColor, &out.LedOverrideColor
		*out = new(string)
		**out = **in
	}
	if in.LedOverrideColorBrightness != nil {
		in, out := &in.LedOverrideColorBrightness, &out.LedOverrideColorBrightness
		*out = new(float64)
		**out = **in
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.MgmtNetworkID != nil {
		in, out := &in.MgmtNetworkID, &out.MgmtNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutdoorModeOverride != nil {
		in, out := &in.OutdoorModeOverride, &out.OutdoorModeOverride
		*out = new(string)
		**out = **in
	}
	if in.OutletEnabled != nil {
		in, out := &in.OutletEnabled, &out.OutletEnabled
		*out = new(bool)
		**out = **in
	}
	if in.OutletOverrides != nil {
		in, out := &in.OutletOverrides, &out.OutletOverrides
		*out = make([]OutletOverridesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PoeMode != nil {
		in, out := &in.PoeMode, &out.PoeMode
		*out = new(string)
		**out = **in
	}
	if in.PortOverride != nil {
		in, out := &in.PortOverride, &out.PortOverride
		*out = make([]PortOverrideObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RadioTable != nil {
		in, out := &in.RadioTable, &out.RadioTable
		*out = make([]RadioTableObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.State != nil {
		in, out := &in.State, &out.State
		*out = new(float64)
		**out = **in
	}
	if in.StpPriority != nil {
		in, out := &in.StpPriority, &out.StpPriority
		*out = new(float64)
		**out = **in
	}
	if in.StpVersion != nil {
		in, out := &in.StpVersion, &out.StpVersion
		*out = new(string)
		**out = **in
	}
	if in.SwitchVlanEnabled != nil {
		in, out := &in.SwitchVlanEnabled, &out.SwitchVlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(DeviceTimeoutsObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Volume != nil {
		in, out := &in.Volume, &out.Volume
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceObservation.
func (in *DeviceObservation) DeepCopy() *DeviceObservation {
	if in == nil {
		return nil
	}
	out := new(DeviceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceParameters) DeepCopyInto(out *DeviceParameters) {
	*out = *in
	if in.AllowAdoption != nil {
		in, out := &in.AllowAdoption, &out.AllowAdoption
		*out = new(bool)
		**out = **in
	}
	if in.BandsteeringMode != nil {
		in, out := &in.BandsteeringMode, &out.BandsteeringMode
		*out = new(string)
		**out = **in
	}
	if in.ConfigNetwork != nil {
		in, out := &in.ConfigNetwork, &out.ConfigNetwork
		*out = new(ConfigNetworkParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Disabled != nil {
		in, out := &in.Disabled, &out.Disabled
		*out = new(bool)
		**out = **in
	}
	if in.FlowctrlEnabled != nil {
		in, out := &in.FlowctrlEnabled, &out.FlowctrlEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ForgetOnDestroy != nil {
		in, out := &in.ForgetOnDestroy, &out.ForgetOnDestroy
		*out = new(bool)
		**out = **in
	}
	if in.JumboframeEnabled != nil {
		in, out := &in.JumboframeEnabled, &out.JumboframeEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LcmBrightness != nil {
		in, out := &in.LcmBrightness, &out.LcmBrightness
		*out = new(float64)
		**out = **in
	}
	if in.LcmBrightnessOverride != nil {
		in, out := &in.LcmBrightnessOverride, &out.LcmBrightnessOverride
		*out = new(bool)
		**out = **in
	}
	if in.LcmIdleTimeout != nil {
		in, out := &in.LcmIdleTimeout, &out.LcmIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.LcmIdleTimeoutOverride != nil {
		in, out := &in.LcmIdleTimeoutOverride, &out.LcmIdleTimeoutOverride
		*out = new(bool)
		**out = **in
	}
	if in.LcmNightModeBegins != nil {
		in, out := &in.LcmNightModeBegins, &out.LcmNightModeBegins
		*out = new(string)
		**out = **in
	}
	if in.LcmNightModeEnds != nil {
		in, out := &in.LcmNightModeEnds, &out.LcmNightModeEnds
		*out = new(string)
		**out = **in
	}
	if in.LedOverride != nil {
		in, out := &in.LedOverride, &out.LedOverride
		*out = new(string)
		**out = **in
	}
	if in.LedOverrideColor != nil {
		in, out := &in.LedOverrideColor, &out.LedOverrideColor
		*out = new(string)
		**out = **in
	}
	if in.LedOverrideColorBrightness != nil {
		in, out := &in.LedOverrideColorBrightness, &out.LedOverrideColorBrightness
		*out = new(float64)
		**out = **in
	}
	if in.Locked != nil {
		in, out := &in.Locked, &out.Locked
		*out = new(bool)
		**out = **in
	}
	if in.Mac != nil {
		in, out := &in.Mac, &out.Mac
		*out = new(string)
		**out = **in
	}
	if in.MgmtNetworkID != nil {
		in, out := &in.MgmtNetworkID, &out.MgmtNetworkID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OutdoorModeOverride != nil {
		in, out := &in.OutdoorModeOverride, &out.OutdoorModeOverride
		*out = new(string)
		**out = **in
	}
	if in.OutletEnabled != nil {
		in, out := &in.OutletEnabled, &out.OutletEnabled
		*out = new(bool)
		**out = **in
	}
	if in.OutletOverrides != nil {
		in, out := &in.OutletOverrides, &out.OutletOverrides
		*out = make([]OutletOverridesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PoeMode != nil {
		in, out := &in.PoeMode, &out.PoeMode
		*out = new(string)
		**out = **in
	}
	if in.PortOverride != nil {
		in, out := &in.PortOverride, &out.PortOverride
		*out = make([]PortOverrideParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.RadioTable != nil {
		in, out := &in.RadioTable, &out.RadioTable
		*out = make([]RadioTableParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.StpPriority != nil {
		in, out := &in.StpPriority, &out.StpPriority
		*out = new(float64)
		**out = **in
	}
	if in.StpVersion != nil {
		in, out := &in.StpVersion, &out.StpVersion
		*out = new(string)
		**out = **in
	}
	if in.SwitchVlanEnabled != nil {
		in, out := &in.SwitchVlanEnabled, &out.SwitchVlanEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(DeviceTimeoutsParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Volume != nil {
		in, out := &in.Volume, &out.Volume
		*out = new(float64)
		**out = **in
	}
	if in.XBaresipPasswordSecretRef != nil {
		in, out := &in.XBaresipPasswordSecretRef, &out.XBaresipPasswordSecretRef
		*out = new(v1.LocalSecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceParameters.
func (in *DeviceParameters) DeepCopy() *DeviceParameters {
	if in == nil {
		return nil
	}
	out := new(DeviceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceSpec) DeepCopyInto(out *DeviceSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceSpec.
func (in *DeviceSpec) DeepCopy() *DeviceSpec {
	if in == nil {
		return nil
	}
	out := new(DeviceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceStatus) DeepCopyInto(out *DeviceStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceStatus.
func (in *DeviceStatus) DeepCopy() *DeviceStatus {
	if in == nil {
		return nil
	}
	out := new(DeviceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceTimeoutsInitParameters) DeepCopyInto(out *DeviceTimeoutsInitParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceTimeoutsInitParameters.
func (in *DeviceTimeoutsInitParameters) DeepCopy() *DeviceTimeoutsInitParameters {
	if in == nil {
		return nil
	}
	out := new(DeviceTimeoutsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceTimeoutsObservation) DeepCopyInto(out *DeviceTimeoutsObservation) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceTimeoutsObservation.
func (in *DeviceTimeoutsObservation) DeepCopy() *DeviceTimeoutsObservation {
	if in == nil {
		return nil
	}
	out := new(DeviceTimeoutsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeviceTimeoutsParameters) DeepCopyInto(out *DeviceTimeoutsParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeviceTimeoutsParameters.
func (in *DeviceTimeoutsParameters) DeepCopy() *DeviceTimeoutsParameters {
	if in == nil {
		return nil
	}
	out := new(DeviceTimeoutsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutletOverridesInitParameters) DeepCopyInto(out *OutletOverridesInitParameters) {
	*out = *in
	if in.CycleEnabled != nil {
		in, out := &in.CycleEnabled, &out.CycleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RelayState != nil {
		in, out := &in.RelayState, &out.RelayState
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutletOverridesInitParameters.
func (in *OutletOverridesInitParameters) DeepCopy() *OutletOverridesInitParameters {
	if in == nil {
		return nil
	}
	out := new(OutletOverridesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutletOverridesObservation) DeepCopyInto(out *OutletOverridesObservation) {
	*out = *in
	if in.CycleEnabled != nil {
		in, out := &in.CycleEnabled, &out.CycleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RelayState != nil {
		in, out := &in.RelayState, &out.RelayState
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutletOverridesObservation.
func (in *OutletOverridesObservation) DeepCopy() *OutletOverridesObservation {
	if in == nil {
		return nil
	}
	out := new(OutletOverridesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OutletOverridesParameters) DeepCopyInto(out *OutletOverridesParameters) {
	*out = *in
	if in.CycleEnabled != nil {
		in, out := &in.CycleEnabled, &out.CycleEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.RelayState != nil {
		in, out := &in.RelayState, &out.RelayState
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OutletOverridesParameters.
func (in *OutletOverridesParameters) DeepCopy() *OutletOverridesParameters {
	if in == nil {
		return nil
	}
	out := new(OutletOverridesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortOverrideInitParameters) DeepCopyInto(out *PortOverrideInitParameters) {
	*out = *in
	if in.AggregateMembers != nil {
		in, out := &in.AggregateMembers, &out.AggregateMembers
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Autoneg != nil {
		in, out := &in.Autoneg, &out.Autoneg
		*out = new(bool)
		**out = **in
	}
	if in.Dot1XCtrl != nil {
		in, out := &in.Dot1XCtrl, &out.Dot1XCtrl
		*out = new(string)
		**out = **in
	}
	if in.Dot1XIdleTimeout != nil {
		in, out := &in.Dot1XIdleTimeout, &out.Dot1XIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.EgressRateLimitKbps != nil {
		in, out := &in.EgressRateLimitKbps, &out.EgressRateLimitKbps
		*out = new(float64)
		**out = **in
	}
	if in.EgressRateLimitKbpsEnabled != nil {
		in, out := &in.EgressRateLimitKbpsEnabled, &out.EgressRateLimitKbpsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ExcludedNetworkconfIds != nil {
		in, out := &in.ExcludedNetworkconfIds, &out.ExcludedNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FecMode != nil {
		in, out := &in.FecMode, &out.FecMode
		*out = new(string)
		**out = **in
	}
	if in.FlowControlEnabled != nil {
		in, out := &in.FlowControlEnabled, &out.FlowControlEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Forward != nil {
		in, out := &in.Forward, &out.Forward
		*out = new(string)
		**out = **in
	}
	if in.FullDuplex != nil {
		in, out := &in.FullDuplex, &out.FullDuplex
		*out = new(bool)
		**out = **in
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(float64)
		**out = **in
	}
	if in.Isolation != nil {
		in, out := &in.Isolation, &out.Isolation
		*out = new(bool)
		**out = **in
	}
	if in.LldpmedEnabled != nil {
		in, out := &in.LldpmedEnabled, &out.LldpmedEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LldpmedNotifyEnabled != nil {
		in, out := &in.LldpmedNotifyEnabled, &out.LldpmedNotifyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MirrorPortIdx != nil {
		in, out := &in.MirrorPortIdx, &out.MirrorPortIdx
		*out = new(float64)
		**out = **in
	}
	if in.MulticastRouterNetworkconfIds != nil {
		in, out := &in.MulticastRouterNetworkconfIds, &out.MulticastRouterNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NativeNetworkconfID != nil {
		in, out := &in.NativeNetworkconfID, &out.NativeNetworkconfID
		*out = new(string)
		**out = **in
	}
	if in.OpMode != nil {
		in, out := &in.OpMode, &out.OpMode
		*out = new(string)
		**out = **in
	}
	if in.PoeMode != nil {
		in, out := &in.PoeMode, &out.PoeMode
		*out = new(string)
		**out = **in
	}
	if in.PortKeepaliveEnabled != nil {
		in, out := &in.PortKeepaliveEnabled, &out.PortKeepaliveEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PortProfileID != nil {
		in, out := &in.PortProfileID, &out.PortProfileID
		*out = new(string)
		**out = **in
	}
	if in.PortSecurityEnabled != nil {
		in, out := &in.PortSecurityEnabled, &out.PortSecurityEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PortSecurityMacAddress != nil {
		in, out := &in.PortSecurityMacAddress, &out.PortSecurityMacAddress
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PriorityQueue1Level != nil {
		in, out := &in.PriorityQueue1Level, &out.PriorityQueue1Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue2Level != nil {
		in, out := &in.PriorityQueue2Level, &out.PriorityQueue2Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue3Level != nil {
		in, out := &in.PriorityQueue3Level, &out.PriorityQueue3Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue4Level != nil {
		in, out := &in.PriorityQueue4Level, &out.PriorityQueue4Level
		*out = new(float64)
		**out = **in
	}
	if in.SettingPreference != nil {
		in, out := &in.SettingPreference, &out.SettingPreference
		*out = new(string)
		**out = **in
	}
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlBcastEnabled != nil {
		in, out := &in.StormctrlBcastEnabled, &out.StormctrlBcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlBcastLevel != nil {
		in, out := &in.StormctrlBcastLevel, &out.StormctrlBcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlBcastRate != nil {
		in, out := &in.StormctrlBcastRate, &out.StormctrlBcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlMcastEnabled != nil {
		in, out := &in.StormctrlMcastEnabled, &out.StormctrlMcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlMcastLevel != nil {
		in, out := &in.StormctrlMcastLevel, &out.StormctrlMcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlMcastRate != nil {
		in, out := &in.StormctrlMcastRate, &out.StormctrlMcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlType != nil {
		in, out := &in.StormctrlType, &out.StormctrlType
		*out = new(string)
		**out = **in
	}
	if in.StormctrlUcastEnabled != nil {
		in, out := &in.StormctrlUcastEnabled, &out.StormctrlUcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlUcastLevel != nil {
		in, out := &in.StormctrlUcastLevel, &out.StormctrlUcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlUcastRate != nil {
		in, out := &in.StormctrlUcastRate, &out.StormctrlUcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StpPortMode != nil {
		in, out := &in.StpPortMode, &out.StpPortMode
		*out = new(bool)
		**out = **in
	}
	if in.TaggedNetworkconfIds != nil {
		in, out := &in.TaggedNetworkconfIds, &out.TaggedNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TaggedVlanMgmt != nil {
		in, out := &in.TaggedVlanMgmt, &out.TaggedVlanMgmt
		*out = new(string)
		**out = **in
	}
	if in.VoiceNetworkconfID != nil {
		in, out := &in.VoiceNetworkconfID, &out.VoiceNetworkconfID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortOverrideInitParameters.
func (in *PortOverrideInitParameters) DeepCopy() *PortOverrideInitParameters {
	if in == nil {
		return nil
	}
	out := new(PortOverrideInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortOverrideObservation) DeepCopyInto(out *PortOverrideObservation) {
	*out = *in
	if in.AggregateMembers != nil {
		in, out := &in.AggregateMembers, &out.AggregateMembers
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Autoneg != nil {
		in, out := &in.Autoneg, &out.Autoneg
		*out = new(bool)
		**out = **in
	}
	if in.Dot1XCtrl != nil {
		in, out := &in.Dot1XCtrl, &out.Dot1XCtrl
		*out = new(string)
		**out = **in
	}
	if in.Dot1XIdleTimeout != nil {
		in, out := &in.Dot1XIdleTimeout, &out.Dot1XIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.EgressRateLimitKbps != nil {
		in, out := &in.EgressRateLimitKbps, &out.EgressRateLimitKbps
		*out = new(float64)
		**out = **in
	}
	if in.EgressRateLimitKbpsEnabled != nil {
		in, out := &in.EgressRateLimitKbpsEnabled, &out.EgressRateLimitKbpsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ExcludedNetworkconfIds != nil {
		in, out := &in.ExcludedNetworkconfIds, &out.ExcludedNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FecMode != nil {
		in, out := &in.FecMode, &out.FecMode
		*out = new(string)
		**out = **in
	}
	if in.FlowControlEnabled != nil {
		in, out := &in.FlowControlEnabled, &out.FlowControlEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Forward != nil {
		in, out := &in.Forward, &out.Forward
		*out = new(string)
		**out = **in
	}
	if in.FullDuplex != nil {
		in, out := &in.FullDuplex, &out.FullDuplex
		*out = new(bool)
		**out = **in
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(float64)
		**out = **in
	}
	if in.Isolation != nil {
		in, out := &in.Isolation, &out.Isolation
		*out = new(bool)
		**out = **in
	}
	if in.LldpmedEnabled != nil {
		in, out := &in.LldpmedEnabled, &out.LldpmedEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LldpmedNotifyEnabled != nil {
		in, out := &in.LldpmedNotifyEnabled, &out.LldpmedNotifyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MirrorPortIdx != nil {
		in, out := &in.MirrorPortIdx, &out.MirrorPortIdx
		*out = new(float64)
		**out = **in
	}
	if in.MulticastRouterNetworkconfIds != nil {
		in, out := &in.MulticastRouterNetworkconfIds, &out.MulticastRouterNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NativeNetworkconfID != nil {
		in, out := &in.NativeNetworkconfID, &out.NativeNetworkconfID
		*out = new(string)
		**out = **in
	}
	if in.OpMode != nil {
		in, out := &in.OpMode, &out.OpMode
		*out = new(string)
		**out = **in
	}
	if in.PoeMode != nil {
		in, out := &in.PoeMode, &out.PoeMode
		*out = new(string)
		**out = **in
	}
	if in.PortKeepaliveEnabled != nil {
		in, out := &in.PortKeepaliveEnabled, &out.PortKeepaliveEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PortProfileID != nil {
		in, out := &in.PortProfileID, &out.PortProfileID
		*out = new(string)
		**out = **in
	}
	if in.PortSecurityEnabled != nil {
		in, out := &in.PortSecurityEnabled, &out.PortSecurityEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PortSecurityMacAddress != nil {
		in, out := &in.PortSecurityMacAddress, &out.PortSecurityMacAddress
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PriorityQueue1Level != nil {
		in, out := &in.PriorityQueue1Level, &out.PriorityQueue1Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue2Level != nil {
		in, out := &in.PriorityQueue2Level, &out.PriorityQueue2Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue3Level != nil {
		in, out := &in.PriorityQueue3Level, &out.PriorityQueue3Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue4Level != nil {
		in, out := &in.PriorityQueue4Level, &out.PriorityQueue4Level
		*out = new(float64)
		**out = **in
	}
	if in.SettingPreference != nil {
		in, out := &in.SettingPreference, &out.SettingPreference
		*out = new(string)
		**out = **in
	}
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlBcastEnabled != nil {
		in, out := &in.StormctrlBcastEnabled, &out.StormctrlBcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlBcastLevel != nil {
		in, out := &in.StormctrlBcastLevel, &out.StormctrlBcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlBcastRate != nil {
		in, out := &in.StormctrlBcastRate, &out.StormctrlBcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlMcastEnabled != nil {
		in, out := &in.StormctrlMcastEnabled, &out.StormctrlMcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlMcastLevel != nil {
		in, out := &in.StormctrlMcastLevel, &out.StormctrlMcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlMcastRate != nil {
		in, out := &in.StormctrlMcastRate, &out.StormctrlMcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlType != nil {
		in, out := &in.StormctrlType, &out.StormctrlType
		*out = new(string)
		**out = **in
	}
	if in.StormctrlUcastEnabled != nil {
		in, out := &in.StormctrlUcastEnabled, &out.StormctrlUcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlUcastLevel != nil {
		in, out := &in.StormctrlUcastLevel, &out.StormctrlUcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlUcastRate != nil {
		in, out := &in.StormctrlUcastRate, &out.StormctrlUcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StpPortMode != nil {
		in, out := &in.StpPortMode, &out.StpPortMode
		*out = new(bool)
		**out = **in
	}
	if in.TaggedNetworkconfIds != nil {
		in, out := &in.TaggedNetworkconfIds, &out.TaggedNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TaggedVlanMgmt != nil {
		in, out := &in.TaggedVlanMgmt, &out.TaggedVlanMgmt
		*out = new(string)
		**out = **in
	}
	if in.VoiceNetworkconfID != nil {
		in, out := &in.VoiceNetworkconfID, &out.VoiceNetworkconfID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortOverrideObservation.
func (in *PortOverrideObservation) DeepCopy() *PortOverrideObservation {
	if in == nil {
		return nil
	}
	out := new(PortOverrideObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PortOverrideParameters) DeepCopyInto(out *PortOverrideParameters) {
	*out = *in
	if in.AggregateMembers != nil {
		in, out := &in.AggregateMembers, &out.AggregateMembers
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.Autoneg != nil {
		in, out := &in.Autoneg, &out.Autoneg
		*out = new(bool)
		**out = **in
	}
	if in.Dot1XCtrl != nil {
		in, out := &in.Dot1XCtrl, &out.Dot1XCtrl
		*out = new(string)
		**out = **in
	}
	if in.Dot1XIdleTimeout != nil {
		in, out := &in.Dot1XIdleTimeout, &out.Dot1XIdleTimeout
		*out = new(string)
		**out = **in
	}
	if in.EgressRateLimitKbps != nil {
		in, out := &in.EgressRateLimitKbps, &out.EgressRateLimitKbps
		*out = new(float64)
		**out = **in
	}
	if in.EgressRateLimitKbpsEnabled != nil {
		in, out := &in.EgressRateLimitKbpsEnabled, &out.EgressRateLimitKbpsEnabled
		*out = new(bool)
		**out = **in
	}
	if in.ExcludedNetworkconfIds != nil {
		in, out := &in.ExcludedNetworkconfIds, &out.ExcludedNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FecMode != nil {
		in, out := &in.FecMode, &out.FecMode
		*out = new(string)
		**out = **in
	}
	if in.FlowControlEnabled != nil {
		in, out := &in.FlowControlEnabled, &out.FlowControlEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Forward != nil {
		in, out := &in.Forward, &out.Forward
		*out = new(string)
		**out = **in
	}
	if in.FullDuplex != nil {
		in, out := &in.FullDuplex, &out.FullDuplex
		*out = new(bool)
		**out = **in
	}
	if in.Index != nil {
		in, out := &in.Index, &out.Index
		*out = new(float64)
		**out = **in
	}
	if in.Isolation != nil {
		in, out := &in.Isolation, &out.Isolation
		*out = new(bool)
		**out = **in
	}
	if in.LldpmedEnabled != nil {
		in, out := &in.LldpmedEnabled, &out.LldpmedEnabled
		*out = new(bool)
		**out = **in
	}
	if in.LldpmedNotifyEnabled != nil {
		in, out := &in.LldpmedNotifyEnabled, &out.LldpmedNotifyEnabled
		*out = new(bool)
		**out = **in
	}
	if in.MirrorPortIdx != nil {
		in, out := &in.MirrorPortIdx, &out.MirrorPortIdx
		*out = new(float64)
		**out = **in
	}
	if in.MulticastRouterNetworkconfIds != nil {
		in, out := &in.MulticastRouterNetworkconfIds, &out.MulticastRouterNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NativeNetworkconfID != nil {
		in, out := &in.NativeNetworkconfID, &out.NativeNetworkconfID
		*out = new(string)
		**out = **in
	}
	if in.OpMode != nil {
		in, out := &in.OpMode, &out.OpMode
		*out = new(string)
		**out = **in
	}
	if in.PoeMode != nil {
		in, out := &in.PoeMode, &out.PoeMode
		*out = new(string)
		**out = **in
	}
	if in.PortKeepaliveEnabled != nil {
		in, out := &in.PortKeepaliveEnabled, &out.PortKeepaliveEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PortProfileID != nil {
		in, out := &in.PortProfileID, &out.PortProfileID
		*out = new(string)
		**out = **in
	}
	if in.PortSecurityEnabled != nil {
		in, out := &in.PortSecurityEnabled, &out.PortSecurityEnabled
		*out = new(bool)
		**out = **in
	}
	if in.PortSecurityMacAddress != nil {
		in, out := &in.PortSecurityMacAddress, &out.PortSecurityMacAddress
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PriorityQueue1Level != nil {
		in, out := &in.PriorityQueue1Level, &out.PriorityQueue1Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue2Level != nil {
		in, out := &in.PriorityQueue2Level, &out.PriorityQueue2Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue3Level != nil {
		in, out := &in.PriorityQueue3Level, &out.PriorityQueue3Level
		*out = new(float64)
		**out = **in
	}
	if in.PriorityQueue4Level != nil {
		in, out := &in.PriorityQueue4Level, &out.PriorityQueue4Level
		*out = new(float64)
		**out = **in
	}
	if in.SettingPreference != nil {
		in, out := &in.SettingPreference, &out.SettingPreference
		*out = new(string)
		**out = **in
	}
	if in.Speed != nil {
		in, out := &in.Speed, &out.Speed
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlBcastEnabled != nil {
		in, out := &in.StormctrlBcastEnabled, &out.StormctrlBcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlBcastLevel != nil {
		in, out := &in.StormctrlBcastLevel, &out.StormctrlBcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlBcastRate != nil {
		in, out := &in.StormctrlBcastRate, &out.StormctrlBcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlMcastEnabled != nil {
		in, out := &in.StormctrlMcastEnabled, &out.StormctrlMcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlMcastLevel != nil {
		in, out := &in.StormctrlMcastLevel, &out.StormctrlMcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlMcastRate != nil {
		in, out := &in.StormctrlMcastRate, &out.StormctrlMcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlType != nil {
		in, out := &in.StormctrlType, &out.StormctrlType
		*out = new(string)
		**out = **in
	}
	if in.StormctrlUcastEnabled != nil {
		in, out := &in.StormctrlUcastEnabled, &out.StormctrlUcastEnabled
		*out = new(bool)
		**out = **in
	}
	if in.StormctrlUcastLevel != nil {
		in, out := &in.StormctrlUcastLevel, &out.StormctrlUcastLevel
		*out = new(float64)
		**out = **in
	}
	if in.StormctrlUcastRate != nil {
		in, out := &in.StormctrlUcastRate, &out.StormctrlUcastRate
		*out = new(float64)
		**out = **in
	}
	if in.StpPortMode != nil {
		in, out := &in.StpPortMode, &out.StpPortMode
		*out = new(bool)
		**out = **in
	}
	if in.TaggedNetworkconfIds != nil {
		in, out := &in.TaggedNetworkconfIds, &out.TaggedNetworkconfIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.TaggedVlanMgmt != nil {
		in, out := &in.TaggedVlanMgmt, &out.TaggedVlanMgmt
		*out = new(string)
		**out = **in
	}
	if in.VoiceNetworkconfID != nil {
		in, out := &in.VoiceNetworkconfID, &out.VoiceNetworkconfID
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PortOverrideParameters.
func (in *PortOverrideParameters) DeepCopy() *PortOverrideParameters {
	if in == nil {
		return nil
	}
	out := new(PortOverrideParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerSourcesInitParameters) DeepCopyInto(out *PowerSourcesInitParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerSourcesInitParameters.
func (in *PowerSourcesInitParameters) DeepCopy() *PowerSourcesInitParameters {
	if in == nil {
		return nil
	}
	out := new(PowerSourcesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerSourcesObservation) DeepCopyInto(out *PowerSourcesObservation) {
	*out = *in
	if in.ClientPsuIndex != nil {
		in, out := &in.ClientPsuIndex, &out.ClientPsuIndex
		*out = new(float64)
		**out = **in
	}
	if in.PowerSourceIndex != nil {
		in, out := &in.PowerSourceIndex, &out.PowerSourceIndex
		*out = new(float64)
		**out = **in
	}
	if in.PowerSourceMac != nil {
		in, out := &in.PowerSourceMac, &out.PowerSourceMac
		*out = new(string)
		**out = **in
	}
	if in.PowerSourceType != nil {
		in, out := &in.PowerSourceType, &out.PowerSourceType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerSourcesObservation.
func (in *PowerSourcesObservation) DeepCopy() *PowerSourcesObservation {
	if in == nil {
		return nil
	}
	out := new(PowerSourcesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PowerSourcesParameters) DeepCopyInto(out *PowerSourcesParameters) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PowerSourcesParameters.
func (in *PowerSourcesParameters) DeepCopy() *PowerSourcesParameters {
	if in == nil {
		return nil
	}
	out := new(PowerSourcesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRate) DeepCopyInto(out *QosRate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRate.
func (in *QosRate) DeepCopy() *QosRate {
	if in == nil {
		return nil
	}
	out := new(QosRate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QosRate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateInitParameters) DeepCopyInto(out *QosRateInitParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxDown != nil {
		in, out := &in.MaxDown, &out.MaxDown
		*out = new(float64)
		**out = **in
	}
	if in.MaxUp != nil {
		in, out := &in.MaxUp, &out.MaxUp
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateInitParameters.
func (in *QosRateInitParameters) DeepCopy() *QosRateInitParameters {
	if in == nil {
		return nil
	}
	out := new(QosRateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateInitParameters_2) DeepCopyInto(out *QosRateInitParameters_2) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.QosRateMaxDown != nil {
		in, out := &in.QosRateMaxDown, &out.QosRateMaxDown
		*out = new(float64)
		**out = **in
	}
	if in.QosRateMaxUp != nil {
		in, out := &in.QosRateMaxUp, &out.QosRateMaxUp
		*out = new(float64)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(QosRateTimeoutsInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateInitParameters_2.
func (in *QosRateInitParameters_2) DeepCopy() *QosRateInitParameters_2 {
	if in == nil {
		return nil
	}
	out := new(QosRateInitParameters_2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateList) DeepCopyInto(out *QosRateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]QosRate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateList.
func (in *QosRateList) DeepCopy() *QosRateList {
	if in == nil {
		return nil
	}
	out := new(QosRateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *QosRateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateObservation) DeepCopyInto(out *QosRateObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxDown != nil {
		in, out := &in.MaxDown, &out.MaxDown
		*out = new(float64)
		**out = **in
	}
	if in.MaxUp != nil {
		in, out := &in.MaxUp, &out.MaxUp
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateObservation.
func (in *QosRateObservation) DeepCopy() *QosRateObservation {
	if in == nil {
		return nil
	}
	out := new(QosRateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateObservation_2) DeepCopyInto(out *QosRateObservation_2) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.QosRateMaxDown != nil {
		in, out := &in.QosRateMaxDown, &out.QosRateMaxDown
		*out = new(float64)
		**out = **in
	}
	if in.QosRateMaxUp != nil {
		in, out := &in.QosRateMaxUp, &out.QosRateMaxUp
		*out = new(float64)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(QosRateTimeoutsObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateObservation_2.
func (in *QosRateObservation_2) DeepCopy() *QosRateObservation_2 {
	if in == nil {
		return nil
	}
	out := new(QosRateObservation_2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateParameters) DeepCopyInto(out *QosRateParameters) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.MaxDown != nil {
		in, out := &in.MaxDown, &out.MaxDown
		*out = new(float64)
		**out = **in
	}
	if in.MaxUp != nil {
		in, out := &in.MaxUp, &out.MaxUp
		*out = new(float64)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateParameters.
func (in *QosRateParameters) DeepCopy() *QosRateParameters {
	if in == nil {
		return nil
	}
	out := new(QosRateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateParameters_2) DeepCopyInto(out *QosRateParameters_2) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.QosRateMaxDown != nil {
		in, out := &in.QosRateMaxDown, &out.QosRateMaxDown
		*out = new(float64)
		**out = **in
	}
	if in.QosRateMaxUp != nil {
		in, out := &in.QosRateMaxUp, &out.QosRateMaxUp
		*out = new(float64)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(QosRateTimeoutsParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateParameters_2.
func (in *QosRateParameters_2) DeepCopy() *QosRateParameters_2 {
	if in == nil {
		return nil
	}
	out := new(QosRateParameters_2)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateSpec) DeepCopyInto(out *QosRateSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateSpec.
func (in *QosRateSpec) DeepCopy() *QosRateSpec {
	if in == nil {
		return nil
	}
	out := new(QosRateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateStatus) DeepCopyInto(out *QosRateStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateStatus.
func (in *QosRateStatus) DeepCopy() *QosRateStatus {
	if in == nil {
		return nil
	}
	out := new(QosRateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateTimeoutsInitParameters) DeepCopyInto(out *QosRateTimeoutsInitParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateTimeoutsInitParameters.
func (in *QosRateTimeoutsInitParameters) DeepCopy() *QosRateTimeoutsInitParameters {
	if in == nil {
		return nil
	}
	out := new(QosRateTimeoutsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateTimeoutsObservation) DeepCopyInto(out *QosRateTimeoutsObservation) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateTimeoutsObservation.
func (in *QosRateTimeoutsObservation) DeepCopy() *QosRateTimeoutsObservation {
	if in == nil {
		return nil
	}
	out := new(QosRateTimeoutsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QosRateTimeoutsParameters) DeepCopyInto(out *QosRateTimeoutsParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QosRateTimeoutsParameters.
func (in *QosRateTimeoutsParameters) DeepCopy() *QosRateTimeoutsParameters {
	if in == nil {
		return nil
	}
	out := new(QosRateTimeoutsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadioTableInitParameters) DeepCopyInto(out *RadioTableInitParameters) {
	*out = *in
	if in.AntennaGain != nil {
		in, out := &in.AntennaGain, &out.AntennaGain
		*out = new(float64)
		**out = **in
	}
	if in.AntennaID != nil {
		in, out := &in.AntennaID, &out.AntennaID
		*out = new(float64)
		**out = **in
	}
	if in.AssistedRoamingEnabled != nil {
		in, out := &in.AssistedRoamingEnabled, &out.AssistedRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AssistedRoamingRssi != nil {
		in, out := &in.AssistedRoamingRssi, &out.AssistedRoamingRssi
		*out = new(float64)
		**out = **in
	}
	if in.Channel != nil {
		in, out := &in.Channel, &out.Channel
		*out = new(string)
		**out = **in
	}
	if in.Dfs != nil {
		in, out := &in.Dfs, &out.Dfs
		*out = new(bool)
		**out = **in
	}
	if in.HardNoiseFloorEnabled != nil {
		in, out := &in.HardNoiseFloorEnabled, &out.HardNoiseFloorEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Ht != nil {
		in, out := &in.Ht, &out.Ht
		*out = new(float64)
		**out = **in
	}
	if in.LoadbalanceEnabled != nil {
		in, out := &in.LoadbalanceEnabled, &out.LoadbalanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Maxsta != nil {
		in, out := &in.Maxsta, &out.Maxsta
		*out = new(float64)
		**out = **in
	}
	if in.MinRssi != nil {
		in, out := &in.MinRssi, &out.MinRssi
		*out = new(float64)
		**out = **in
	}
	if in.MinRssiEnabled != nil {
		in, out := &in.MinRssiEnabled, &out.MinRssiEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Radio != nil {
		in, out := &in.Radio, &out.Radio
		*out = new(string)
		**out = **in
	}
	if in.SensLevel != nil {
		in, out := &in.SensLevel, &out.SensLevel
		*out = new(float64)
		**out = **in
	}
	if in.SensLevelEnabled != nil {
		in, out := &in.SensLevelEnabled, &out.SensLevelEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TxPower != nil {
		in, out := &in.TxPower, &out.TxPower
		*out = new(string)
		**out = **in
	}
	if in.TxPowerMode != nil {
		in, out := &in.TxPowerMode, &out.TxPowerMode
		*out = new(string)
		**out = **in
	}
	if in.VwireEnabled != nil {
		in, out := &in.VwireEnabled, &out.VwireEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadioTableInitParameters.
func (in *RadioTableInitParameters) DeepCopy() *RadioTableInitParameters {
	if in == nil {
		return nil
	}
	out := new(RadioTableInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadioTableObservation) DeepCopyInto(out *RadioTableObservation) {
	*out = *in
	if in.AntennaGain != nil {
		in, out := &in.AntennaGain, &out.AntennaGain
		*out = new(float64)
		**out = **in
	}
	if in.AntennaID != nil {
		in, out := &in.AntennaID, &out.AntennaID
		*out = new(float64)
		**out = **in
	}
	if in.AssistedRoamingEnabled != nil {
		in, out := &in.AssistedRoamingEnabled, &out.AssistedRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AssistedRoamingRssi != nil {
		in, out := &in.AssistedRoamingRssi, &out.AssistedRoamingRssi
		*out = new(float64)
		**out = **in
	}
	if in.Channel != nil {
		in, out := &in.Channel, &out.Channel
		*out = new(string)
		**out = **in
	}
	if in.Dfs != nil {
		in, out := &in.Dfs, &out.Dfs
		*out = new(bool)
		**out = **in
	}
	if in.HardNoiseFloorEnabled != nil {
		in, out := &in.HardNoiseFloorEnabled, &out.HardNoiseFloorEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Ht != nil {
		in, out := &in.Ht, &out.Ht
		*out = new(float64)
		**out = **in
	}
	if in.LoadbalanceEnabled != nil {
		in, out := &in.LoadbalanceEnabled, &out.LoadbalanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Maxsta != nil {
		in, out := &in.Maxsta, &out.Maxsta
		*out = new(float64)
		**out = **in
	}
	if in.MinRssi != nil {
		in, out := &in.MinRssi, &out.MinRssi
		*out = new(float64)
		**out = **in
	}
	if in.MinRssiEnabled != nil {
		in, out := &in.MinRssiEnabled, &out.MinRssiEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Radio != nil {
		in, out := &in.Radio, &out.Radio
		*out = new(string)
		**out = **in
	}
	if in.SensLevel != nil {
		in, out := &in.SensLevel, &out.SensLevel
		*out = new(float64)
		**out = **in
	}
	if in.SensLevelEnabled != nil {
		in, out := &in.SensLevelEnabled, &out.SensLevelEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TxPower != nil {
		in, out := &in.TxPower, &out.TxPower
		*out = new(string)
		**out = **in
	}
	if in.TxPowerMode != nil {
		in, out := &in.TxPowerMode, &out.TxPowerMode
		*out = new(string)
		**out = **in
	}
	if in.VwireEnabled != nil {
		in, out := &in.VwireEnabled, &out.VwireEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadioTableObservation.
func (in *RadioTableObservation) DeepCopy() *RadioTableObservation {
	if in == nil {
		return nil
	}
	out := new(RadioTableObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RadioTableParameters) DeepCopyInto(out *RadioTableParameters) {
	*out = *in
	if in.AntennaGain != nil {
		in, out := &in.AntennaGain, &out.AntennaGain
		*out = new(float64)
		**out = **in
	}
	if in.AntennaID != nil {
		in, out := &in.AntennaID, &out.AntennaID
		*out = new(float64)
		**out = **in
	}
	if in.AssistedRoamingEnabled != nil {
		in, out := &in.AssistedRoamingEnabled, &out.AssistedRoamingEnabled
		*out = new(bool)
		**out = **in
	}
	if in.AssistedRoamingRssi != nil {
		in, out := &in.AssistedRoamingRssi, &out.AssistedRoamingRssi
		*out = new(float64)
		**out = **in
	}
	if in.Channel != nil {
		in, out := &in.Channel, &out.Channel
		*out = new(string)
		**out = **in
	}
	if in.Dfs != nil {
		in, out := &in.Dfs, &out.Dfs
		*out = new(bool)
		**out = **in
	}
	if in.HardNoiseFloorEnabled != nil {
		in, out := &in.HardNoiseFloorEnabled, &out.HardNoiseFloorEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Ht != nil {
		in, out := &in.Ht, &out.Ht
		*out = new(float64)
		**out = **in
	}
	if in.LoadbalanceEnabled != nil {
		in, out := &in.LoadbalanceEnabled, &out.LoadbalanceEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Maxsta != nil {
		in, out := &in.Maxsta, &out.Maxsta
		*out = new(float64)
		**out = **in
	}
	if in.MinRssi != nil {
		in, out := &in.MinRssi, &out.MinRssi
		*out = new(float64)
		**out = **in
	}
	if in.MinRssiEnabled != nil {
		in, out := &in.MinRssiEnabled, &out.MinRssiEnabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Radio != nil {
		in, out := &in.Radio, &out.Radio
		*out = new(string)
		**out = **in
	}
	if in.SensLevel != nil {
		in, out := &in.SensLevel, &out.SensLevel
		*out = new(float64)
		**out = **in
	}
	if in.SensLevelEnabled != nil {
		in, out := &in.SensLevelEnabled, &out.SensLevelEnabled
		*out = new(bool)
		**out = **in
	}
	if in.TxPower != nil {
		in, out := &in.TxPower, &out.TxPower
		*out = new(string)
		**out = **in
	}
	if in.TxPowerMode != nil {
		in, out := &in.TxPowerMode, &out.TxPowerMode
		*out = new(string)
		**out = **in
	}
	if in.VwireEnabled != nil {
		in, out := &in.VwireEnabled, &out.VwireEnabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RadioTableParameters.
func (in *RadioTableParameters) DeepCopy() *RadioTableParameters {
	if in == nil {
		return nil
	}
	out := new(RadioTableParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Supervisor) DeepCopyInto(out *Supervisor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Supervisor.
func (in *Supervisor) DeepCopy() *Supervisor {
	if in == nil {
		return nil
	}
	out := new(Supervisor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Supervisor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorInitParameters) DeepCopyInto(out *SupervisorInitParameters) {
	*out = *in
	if in.DeviceMac != nil {
		in, out := &in.DeviceMac, &out.DeviceMac
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.HeartbeatInterval != nil {
		in, out := &in.HeartbeatInterval, &out.HeartbeatInterval
		*out = new(string)
		**out = **in
	}
	if in.PowerOffDuration != nil {
		in, out := &in.PowerOffDuration, &out.PowerOffDuration
		*out = new(string)
		**out = **in
	}
	if in.SilenceThreshold != nil {
		in, out := &in.SilenceThreshold, &out.SilenceThreshold
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(SupervisorTimeoutsInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorInitParameters.
func (in *SupervisorInitParameters) DeepCopy() *SupervisorInitParameters {
	if in == nil {
		return nil
	}
	out := new(SupervisorInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorList) DeepCopyInto(out *SupervisorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Supervisor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorList.
func (in *SupervisorList) DeepCopy() *SupervisorList {
	if in == nil {
		return nil
	}
	out := new(SupervisorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SupervisorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorObservation) DeepCopyInto(out *SupervisorObservation) {
	*out = *in
	if in.ConsecutiveFailures != nil {
		in, out := &in.ConsecutiveFailures, &out.ConsecutiveFailures
		*out = new(float64)
		**out = **in
	}
	if in.DeviceMac != nil {
		in, out := &in.DeviceMac, &out.DeviceMac
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.HeartbeatInterval != nil {
		in, out := &in.HeartbeatInterval, &out.HeartbeatInterval
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.PowerOffDuration != nil {
		in, out := &in.PowerOffDuration, &out.PowerOffDuration
		*out = new(string)
		**out = **in
	}
	if in.PowerSources != nil {
		in, out := &in.PowerSources, &out.PowerSources
		*out = make([]PowerSourcesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SilenceThreshold != nil {
		in, out := &in.SilenceThreshold, &out.SilenceThreshold
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(SupervisorTimeoutsObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorObservation.
func (in *SupervisorObservation) DeepCopy() *SupervisorObservation {
	if in == nil {
		return nil
	}
	out := new(SupervisorObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorParameters) DeepCopyInto(out *SupervisorParameters) {
	*out = *in
	if in.DeviceMac != nil {
		in, out := &in.DeviceMac, &out.DeviceMac
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.HeartbeatInterval != nil {
		in, out := &in.HeartbeatInterval, &out.HeartbeatInterval
		*out = new(string)
		**out = **in
	}
	if in.PowerOffDuration != nil {
		in, out := &in.PowerOffDuration, &out.PowerOffDuration
		*out = new(string)
		**out = **in
	}
	if in.SilenceThreshold != nil {
		in, out := &in.SilenceThreshold, &out.SilenceThreshold
		*out = new(string)
		**out = **in
	}
	if in.Site != nil {
		in, out := &in.Site, &out.Site
		*out = new(string)
		**out = **in
	}
	if in.Timeouts != nil {
		in, out := &in.Timeouts, &out.Timeouts
		*out = new(SupervisorTimeoutsParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorParameters.
func (in *SupervisorParameters) DeepCopy() *SupervisorParameters {
	if in == nil {
		return nil
	}
	out := new(SupervisorParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorSpec) DeepCopyInto(out *SupervisorSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorSpec.
func (in *SupervisorSpec) DeepCopy() *SupervisorSpec {
	if in == nil {
		return nil
	}
	out := new(SupervisorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorStatus) DeepCopyInto(out *SupervisorStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorStatus.
func (in *SupervisorStatus) DeepCopy() *SupervisorStatus {
	if in == nil {
		return nil
	}
	out := new(SupervisorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorTimeoutsInitParameters) DeepCopyInto(out *SupervisorTimeoutsInitParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorTimeoutsInitParameters.
func (in *SupervisorTimeoutsInitParameters) DeepCopy() *SupervisorTimeoutsInitParameters {
	if in == nil {
		return nil
	}
	out := new(SupervisorTimeoutsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorTimeoutsObservation) DeepCopyInto(out *SupervisorTimeoutsObservation) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorTimeoutsObservation.
func (in *SupervisorTimeoutsObservation) DeepCopy() *SupervisorTimeoutsObservation {
	if in == nil {
		return nil
	}
	out := new(SupervisorTimeoutsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SupervisorTimeoutsParameters) DeepCopyInto(out *SupervisorTimeoutsParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SupervisorTimeoutsParameters.
func (in *SupervisorTimeoutsParameters) DeepCopy() *SupervisorTimeoutsParameters {
	if in == nil {
		return nil
	}
	out := new(SupervisorTimeoutsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsInitParameters) DeepCopyInto(out *TimeoutsInitParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsInitParameters.
func (in *TimeoutsInitParameters) DeepCopy() *TimeoutsInitParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsObservation) DeepCopyInto(out *TimeoutsObservation) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsObservation.
func (in *TimeoutsObservation) DeepCopy() *TimeoutsObservation {
	if in == nil {
		return nil
	}
	out := new(TimeoutsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimeoutsParameters) DeepCopyInto(out *TimeoutsParameters) {
	*out = *in
	if in.Create != nil {
		in, out := &in.Create, &out.Create
		*out = new(string)
		**out = **in
	}
	if in.Delete != nil {
		in, out := &in.Delete, &out.Delete
		*out = new(string)
		**out = **in
	}
	if in.Read != nil {
		in, out := &in.Read, &out.Read
		*out = new(string)
		**out = **in
	}
	if in.Update != nil {
		in, out := &in.Update, &out.Update
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimeoutsParameters.
func (in *TimeoutsParameters) DeepCopy() *TimeoutsParameters {
	if in == nil {
		return nil
	}
	out := new(TimeoutsParameters)
	in.DeepCopyInto(out)
	return out
}
