// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DHCPInitParameters struct {

	// DHCP Class of Service
	Cos *float64 `json:"cos,omitempty" tf:"cos,omitempty"`

	Options []OptionsInitParameters `json:"options,omitempty" tf:"options,omitempty"`
}

type DHCPObservation struct {

	// DHCP Class of Service
	Cos *float64 `json:"cos,omitempty" tf:"cos,omitempty"`

	Options []OptionsObservation `json:"options,omitempty" tf:"options,omitempty"`
}

type DHCPParameters struct {

	// DHCP Class of Service
	// +kubebuilder:validation:Optional
	Cos *float64 `json:"cos,omitempty" tf:"cos,omitempty"`

	// +kubebuilder:validation:Optional
	Options []OptionsParameters `json:"options,omitempty" tf:"options,omitempty"`
}

type DNSInitParameters struct {

	// IPv6 DNS preference (auto, manual)
	IPv6Preference *string `json:"ipv6Preference,omitempty" tf:"ipv6_preference,omitempty"`

	// Primary IPv6 DNS server
	IPv6Primary *string `json:"ipv6Primary,omitempty" tf:"ipv6_primary,omitempty"`

	// Secondary IPv6 DNS server
	IPv6Secondary *string `json:"ipv6Secondary,omitempty" tf:"ipv6_secondary,omitempty"`

	// DNS preference (auto, manual)
	Preference *string `json:"preference,omitempty" tf:"preference,omitempty"`

	// Primary DNS server
	Primary *string `json:"primary,omitempty" tf:"primary,omitempty"`

	// Secondary DNS server
	Secondary *string `json:"secondary,omitempty" tf:"secondary,omitempty"`
}

type DNSObservation struct {

	// IPv6 DNS preference (auto, manual)
	IPv6Preference *string `json:"ipv6Preference,omitempty" tf:"ipv6_preference,omitempty"`

	// Primary IPv6 DNS server
	IPv6Primary *string `json:"ipv6Primary,omitempty" tf:"ipv6_primary,omitempty"`

	// Secondary IPv6 DNS server
	IPv6Secondary *string `json:"ipv6Secondary,omitempty" tf:"ipv6_secondary,omitempty"`

	// DNS preference (auto, manual)
	Preference *string `json:"preference,omitempty" tf:"preference,omitempty"`

	// Primary DNS server
	Primary *string `json:"primary,omitempty" tf:"primary,omitempty"`

	// Secondary DNS server
	Secondary *string `json:"secondary,omitempty" tf:"secondary,omitempty"`
}

type DNSParameters struct {

	// IPv6 DNS preference (auto, manual)
	// +kubebuilder:validation:Optional
	IPv6Preference *string `json:"ipv6Preference,omitempty" tf:"ipv6_preference,omitempty"`

	// Primary IPv6 DNS server
	// +kubebuilder:validation:Optional
	IPv6Primary *string `json:"ipv6Primary,omitempty" tf:"ipv6_primary,omitempty"`

	// Secondary IPv6 DNS server
	// +kubebuilder:validation:Optional
	IPv6Secondary *string `json:"ipv6Secondary,omitempty" tf:"ipv6_secondary,omitempty"`

	// DNS preference (auto, manual)
	// +kubebuilder:validation:Optional
	Preference *string `json:"preference,omitempty" tf:"preference,omitempty"`

	// Primary DNS server
	// +kubebuilder:validation:Optional
	Primary *string `json:"primary,omitempty" tf:"primary,omitempty"`

	// Secondary DNS server
	// +kubebuilder:validation:Optional
	Secondary *string `json:"secondary,omitempty" tf:"secondary,omitempty"`
}

type Dhcpv6InitParameters struct {

	// DHCPv6 Class of Service
	Cos *float64 `json:"cos,omitempty" tf:"cos,omitempty"`

	Options []Dhcpv6OptionsInitParameters `json:"options,omitempty" tf:"options,omitempty"`

	// DHCPv6 prefix delegation size
	PdSize *float64 `json:"pdSize,omitempty" tf:"pd_size,omitempty"`

	// Whether DHCPv6 PD size is automatic
	PdSizeAuto *bool `json:"pdSizeAuto,omitempty" tf:"pd_size_auto,omitempty"`

	// IPv6 WAN delegation type (pd, single_network, none)
	WanDelegationType *string `json:"wanDelegationType,omitempty" tf:"wan_delegation_type,omitempty"`
}

type Dhcpv6Observation struct {

	// DHCPv6 Class of Service
	Cos *float64 `json:"cos,omitempty" tf:"cos,omitempty"`

	Options []Dhcpv6OptionsObservation `json:"options,omitempty" tf:"options,omitempty"`

	// DHCPv6 prefix delegation size
	PdSize *float64 `json:"pdSize,omitempty" tf:"pd_size,omitempty"`

	// Whether DHCPv6 PD size is automatic
	PdSizeAuto *bool `json:"pdSizeAuto,omitempty" tf:"pd_size_auto,omitempty"`

	// IPv6 WAN delegation type (pd, single_network, none)
	WanDelegationType *string `json:"wanDelegationType,omitempty" tf:"wan_delegation_type,omitempty"`
}

type Dhcpv6OptionsInitParameters struct {

	// DHCPv6 option number (1, 11, 15, 16, or 17)
	OptionNumber *float64 `json:"optionNumber,omitempty" tf:"option_number,omitempty"`

	// DHCPv6 option value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type Dhcpv6OptionsObservation struct {

	// DHCPv6 option number (1, 11, 15, 16, or 17)
	OptionNumber *float64 `json:"optionNumber,omitempty" tf:"option_number,omitempty"`

	// DHCPv6 option value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type Dhcpv6OptionsParameters struct {

	// DHCPv6 option number (1, 11, 15, 16, or 17)
	// +kubebuilder:validation:Optional
	OptionNumber *float64 `json:"optionNumber" tf:"option_number,omitempty"`

	// DHCPv6 option value
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type Dhcpv6Parameters struct {

	// DHCPv6 Class of Service
	// +kubebuilder:validation:Optional
	Cos *float64 `json:"cos,omitempty" tf:"cos,omitempty"`

	// +kubebuilder:validation:Optional
	Options []Dhcpv6OptionsParameters `json:"options,omitempty" tf:"options,omitempty"`

	// DHCPv6 prefix delegation size
	// +kubebuilder:validation:Optional
	PdSize *float64 `json:"pdSize,omitempty" tf:"pd_size,omitempty"`

	// Whether DHCPv6 PD size is automatic
	// +kubebuilder:validation:Optional
	PdSizeAuto *bool `json:"pdSizeAuto,omitempty" tf:"pd_size_auto,omitempty"`

	// IPv6 WAN delegation type (pd, single_network, none)
	// +kubebuilder:validation:Optional
	WanDelegationType *string `json:"wanDelegationType,omitempty" tf:"wan_delegation_type,omitempty"`
}

type EgressQosInitParameters struct {

	// Whether egress QoS is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Egress QoS priority
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type EgressQosObservation struct {

	// Whether egress QoS is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Egress QoS priority
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type EgressQosParameters struct {

	// Whether egress QoS is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Egress QoS priority
	// +kubebuilder:validation:Optional
	Priority *float64 `json:"priority,omitempty" tf:"priority,omitempty"`
}

type IgmpProxyInitParameters struct {

	// IGMP proxy downstream target (none, lan, guest)
	Downstream *string `json:"downstream,omitempty" tf:"downstream,omitempty"`

	// Whether IGMP proxy upstream is enabled
	Upstream *bool `json:"upstream,omitempty" tf:"upstream,omitempty"`
}

type IgmpProxyObservation struct {

	// IGMP proxy downstream target (none, lan, guest)
	Downstream *string `json:"downstream,omitempty" tf:"downstream,omitempty"`

	// Whether IGMP proxy upstream is enabled
	Upstream *bool `json:"upstream,omitempty" tf:"upstream,omitempty"`
}

type IgmpProxyParameters struct {

	// IGMP proxy downstream target (none, lan, guest)
	// +kubebuilder:validation:Optional
	Downstream *string `json:"downstream,omitempty" tf:"downstream,omitempty"`

	// Whether IGMP proxy upstream is enabled
	// +kubebuilder:validation:Optional
	Upstream *bool `json:"upstream,omitempty" tf:"upstream,omitempty"`
}

type LoadBalanceInitParameters struct {

	// Failover priority
	FailoverPriority *float64 `json:"failoverPriority,omitempty" tf:"failover_priority,omitempty"`

	// Load balance type (failover-only, weighted)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Load balance weight
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type LoadBalanceObservation struct {

	// Failover priority
	FailoverPriority *float64 `json:"failoverPriority,omitempty" tf:"failover_priority,omitempty"`

	// Load balance type (failover-only, weighted)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Load balance weight
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type LoadBalanceParameters struct {

	// Failover priority
	// +kubebuilder:validation:Optional
	FailoverPriority *float64 `json:"failoverPriority,omitempty" tf:"failover_priority,omitempty"`

	// Load balance type (failover-only, weighted)
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// Load balance weight
	// +kubebuilder:validation:Optional
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type OptionsInitParameters struct {

	// DHCP option number
	OptionNumber *float64 `json:"optionNumber,omitempty" tf:"option_number,omitempty"`

	// DHCP option value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type OptionsObservation struct {

	// DHCP option number
	OptionNumber *float64 `json:"optionNumber,omitempty" tf:"option_number,omitempty"`

	// DHCP option value
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type OptionsParameters struct {

	// DHCP option number
	// +kubebuilder:validation:Optional
	OptionNumber *float64 `json:"optionNumber" tf:"option_number,omitempty"`

	// DHCP option value
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type ProviderCapabilitiesInitParameters struct {

	// Download speed in kilobits per second
	DownloadKilobitsPerSecond *float64 `json:"downloadKilobitsPerSecond,omitempty" tf:"download_kilobits_per_second,omitempty"`

	// Upload speed in kilobits per second
	UploadKilobitsPerSecond *float64 `json:"uploadKilobitsPerSecond,omitempty" tf:"upload_kilobits_per_second,omitempty"`
}

type ProviderCapabilitiesObservation struct {

	// Download speed in kilobits per second
	DownloadKilobitsPerSecond *float64 `json:"downloadKilobitsPerSecond,omitempty" tf:"download_kilobits_per_second,omitempty"`

	// Upload speed in kilobits per second
	UploadKilobitsPerSecond *float64 `json:"uploadKilobitsPerSecond,omitempty" tf:"upload_kilobits_per_second,omitempty"`
}

type ProviderCapabilitiesParameters struct {

	// Download speed in kilobits per second
	// +kubebuilder:validation:Optional
	DownloadKilobitsPerSecond *float64 `json:"downloadKilobitsPerSecond,omitempty" tf:"download_kilobits_per_second,omitempty"`

	// Upload speed in kilobits per second
	// +kubebuilder:validation:Optional
	UploadKilobitsPerSecond *float64 `json:"uploadKilobitsPerSecond,omitempty" tf:"upload_kilobits_per_second,omitempty"`
}

type SmartqInitParameters struct {

	// Smart Queue download rate in kbps
	DownRate *float64 `json:"downRate,omitempty" tf:"down_rate,omitempty"`

	// Whether Smart Queue is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Smart Queue upload rate in kbps
	UpRate *float64 `json:"upRate,omitempty" tf:"up_rate,omitempty"`
}

type SmartqObservation struct {

	// Smart Queue download rate in kbps
	DownRate *float64 `json:"downRate,omitempty" tf:"down_rate,omitempty"`

	// Whether Smart Queue is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Smart Queue upload rate in kbps
	UpRate *float64 `json:"upRate,omitempty" tf:"up_rate,omitempty"`
}

type SmartqParameters struct {

	// Smart Queue download rate in kbps
	// +kubebuilder:validation:Optional
	DownRate *float64 `json:"downRate,omitempty" tf:"down_rate,omitempty"`

	// Whether Smart Queue is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Smart Queue upload rate in kbps
	// +kubebuilder:validation:Optional
	UpRate *float64 `json:"upRate,omitempty" tf:"up_rate,omitempty"`
}

type UpnpInitParameters struct {

	// Whether UPnP is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether UPnP NAT-PMP is enabled
	NATPmpEnabled *bool `json:"natPmpEnabled,omitempty" tf:"nat_pmp_enabled,omitempty"`

	// Whether UPnP secure mode is enabled
	SecureMode *bool `json:"secureMode,omitempty" tf:"secure_mode,omitempty"`

	// UPnP WAN interface
	WanInterface *string `json:"wanInterface,omitempty" tf:"wan_interface,omitempty"`
}

type UpnpObservation struct {

	// Whether UPnP is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether UPnP NAT-PMP is enabled
	NATPmpEnabled *bool `json:"natPmpEnabled,omitempty" tf:"nat_pmp_enabled,omitempty"`

	// Whether UPnP secure mode is enabled
	SecureMode *bool `json:"secureMode,omitempty" tf:"secure_mode,omitempty"`

	// UPnP WAN interface
	WanInterface *string `json:"wanInterface,omitempty" tf:"wan_interface,omitempty"`
}

type UpnpParameters struct {

	// Whether UPnP is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// Whether UPnP NAT-PMP is enabled
	// +kubebuilder:validation:Optional
	NATPmpEnabled *bool `json:"natPmpEnabled,omitempty" tf:"nat_pmp_enabled,omitempty"`

	// Whether UPnP secure mode is enabled
	// +kubebuilder:validation:Optional
	SecureMode *bool `json:"secureMode,omitempty" tf:"secure_mode,omitempty"`

	// UPnP WAN interface
	// +kubebuilder:validation:Optional
	WanInterface *string `json:"wanInterface,omitempty" tf:"wan_interface,omitempty"`
}

type VlanInitParameters struct {

	// Whether VLAN is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The VLAN ID
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type VlanObservation struct {

	// Whether VLAN is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The VLAN ID
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type VlanParameters struct {

	// Whether VLAN is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The VLAN ID
	// +kubebuilder:validation:Optional
	ID *float64 `json:"id,omitempty" tf:"id,omitempty"`
}

type WanInitParameters struct {
	DHCP *DHCPInitParameters `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	DNS *DNSInitParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	Dhcpv6 *Dhcpv6InitParameters `json:"dhcpv6,omitempty" tf:"dhcpv6,omitempty"`

	EgressQos *EgressQosInitParameters `json:"egressQos,omitempty" tf:"egress_qos,omitempty"`

	// Whether the WAN network is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// IP aliases
	IPAliases []*string `json:"ipAliases,omitempty" tf:"ip_aliases,omitempty"`

	// Whether WAN IPv6 settings are managed automatically by the controller or manually. Can be one of `auto` or `manual`.
	IPv6SettingPreference *string `json:"ipv6SettingPreference,omitempty" tf:"ipv6_setting_preference,omitempty"`

	IgmpProxy *IgmpProxyInitParameters `json:"igmpProxy,omitempty" tf:"igmp_proxy,omitempty"`

	LoadBalance *LoadBalanceInitParameters `json:"loadBalance,omitempty" tf:"load_balance,omitempty"`

	// Whether the WAN interface MAC address is overridden.
	MacOverrideEnabled *bool `json:"macOverrideEnabled,omitempty" tf:"mac_override_enabled,omitempty"`

	// The name of the WAN network
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ProviderCapabilities *ProviderCapabilitiesInitParameters `json:"providerCapabilities,omitempty" tf:"provider_capabilities,omitempty"`

	// Whether to report WAN events
	ReportWanEvent *bool `json:"reportWanEvent,omitempty" tf:"report_wan_event,omitempty"`

	// Whether WAN settings are managed automatically by the controller or manually. Can be one of `auto` or `manual`.
	SettingPreference *string `json:"settingPreference,omitempty" tf:"setting_preference,omitempty"`

	// The LAN network used for IPv6 single-network prefix delegation (used when the IPv6 delegation type is `single_network`).
	SingleNetworkLan *string `json:"singleNetworkLan,omitempty" tf:"single_network_lan,omitempty"`

	// The name of the site to associate the WAN network with
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Smartq *SmartqInitParameters `json:"smartq,omitempty" tf:"smartq,omitempty"`

	Timeouts *WanTimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// The WAN type (dhcp, static, pppoe)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The IPv6 WAN type. One of `dhcpv6`, `slaac`, `static`, or `disabled`. Note: the controller requires `slaac` when the IPv6 delegation type is `single_network` (`api.err.SingleNetworkMustBeSLAAC` otherwise) — common with ISPs that deliver IPv6 by Router Advertisement, e.g. Free/Freebox in bridge mode.
	TypeV6 *string `json:"typeV6,omitempty" tf:"type_v6,omitempty"`

	Upnp *UpnpInitParameters `json:"upnp,omitempty" tf:"upnp,omitempty"`

	Vlan *VlanInitParameters `json:"vlan,omitempty" tf:"vlan,omitempty"`

	// The DS-Lite AFTR remote host. Only used when `wan_dslite_remote_host_auto` is disabled.
	WanDsliteRemoteHost *string `json:"wanDsliteRemoteHost,omitempty" tf:"wan_dslite_remote_host,omitempty"`

	// Whether the DS-Lite AFTR remote host is detected automatically.
	WanDsliteRemoteHostAuto *bool `json:"wanDsliteRemoteHostAuto,omitempty" tf:"wan_dslite_remote_host_auto,omitempty"`
}

type WanObservation struct {
	DHCP *DHCPObservation `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	DNS *DNSObservation `json:"dns,omitempty" tf:"dns,omitempty"`

	Dhcpv6 *Dhcpv6Observation `json:"dhcpv6,omitempty" tf:"dhcpv6,omitempty"`

	EgressQos *EgressQosObservation `json:"egressQos,omitempty" tf:"egress_qos,omitempty"`

	// Whether the WAN network is enabled
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// IP aliases
	IPAliases []*string `json:"ipAliases,omitempty" tf:"ip_aliases,omitempty"`

	// Whether WAN IPv6 settings are managed automatically by the controller or manually. Can be one of `auto` or `manual`.
	IPv6SettingPreference *string `json:"ipv6SettingPreference,omitempty" tf:"ipv6_setting_preference,omitempty"`

	IgmpProxy *IgmpProxyObservation `json:"igmpProxy,omitempty" tf:"igmp_proxy,omitempty"`

	LoadBalance *LoadBalanceObservation `json:"loadBalance,omitempty" tf:"load_balance,omitempty"`

	// Whether the WAN interface MAC address is overridden.
	MacOverrideEnabled *bool `json:"macOverrideEnabled,omitempty" tf:"mac_override_enabled,omitempty"`

	// The name of the WAN network
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	ProviderCapabilities *ProviderCapabilitiesObservation `json:"providerCapabilities,omitempty" tf:"provider_capabilities,omitempty"`

	// Whether to report WAN events
	ReportWanEvent *bool `json:"reportWanEvent,omitempty" tf:"report_wan_event,omitempty"`

	// Whether WAN settings are managed automatically by the controller or manually. Can be one of `auto` or `manual`.
	SettingPreference *string `json:"settingPreference,omitempty" tf:"setting_preference,omitempty"`

	// The LAN network used for IPv6 single-network prefix delegation (used when the IPv6 delegation type is `single_network`).
	SingleNetworkLan *string `json:"singleNetworkLan,omitempty" tf:"single_network_lan,omitempty"`

	// The name of the site to associate the WAN network with
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	Smartq *SmartqObservation `json:"smartq,omitempty" tf:"smartq,omitempty"`

	Timeouts *WanTimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// The WAN type (dhcp, static, pppoe)
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The IPv6 WAN type. One of `dhcpv6`, `slaac`, `static`, or `disabled`. Note: the controller requires `slaac` when the IPv6 delegation type is `single_network` (`api.err.SingleNetworkMustBeSLAAC` otherwise) — common with ISPs that deliver IPv6 by Router Advertisement, e.g. Free/Freebox in bridge mode.
	TypeV6 *string `json:"typeV6,omitempty" tf:"type_v6,omitempty"`

	Upnp *UpnpObservation `json:"upnp,omitempty" tf:"upnp,omitempty"`

	Vlan *VlanObservation `json:"vlan,omitempty" tf:"vlan,omitempty"`

	// The DS-Lite AFTR remote host. Only used when `wan_dslite_remote_host_auto` is disabled.
	WanDsliteRemoteHost *string `json:"wanDsliteRemoteHost,omitempty" tf:"wan_dslite_remote_host,omitempty"`

	// Whether the DS-Lite AFTR remote host is detected automatically.
	WanDsliteRemoteHostAuto *bool `json:"wanDsliteRemoteHostAuto,omitempty" tf:"wan_dslite_remote_host_auto,omitempty"`
}

type WanParameters struct {

	// +kubebuilder:validation:Optional
	DHCP *DHCPParameters `json:"dhcp,omitempty" tf:"dhcp,omitempty"`

	// +kubebuilder:validation:Optional
	DNS *DNSParameters `json:"dns,omitempty" tf:"dns,omitempty"`

	// +kubebuilder:validation:Optional
	Dhcpv6 *Dhcpv6Parameters `json:"dhcpv6,omitempty" tf:"dhcpv6,omitempty"`

	// +kubebuilder:validation:Optional
	EgressQos *EgressQosParameters `json:"egressQos,omitempty" tf:"egress_qos,omitempty"`

	// Whether the WAN network is enabled
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// IP aliases
	// +kubebuilder:validation:Optional
	IPAliases []*string `json:"ipAliases,omitempty" tf:"ip_aliases,omitempty"`

	// Whether WAN IPv6 settings are managed automatically by the controller or manually. Can be one of `auto` or `manual`.
	// +kubebuilder:validation:Optional
	IPv6SettingPreference *string `json:"ipv6SettingPreference,omitempty" tf:"ipv6_setting_preference,omitempty"`

	// +kubebuilder:validation:Optional
	IgmpProxy *IgmpProxyParameters `json:"igmpProxy,omitempty" tf:"igmp_proxy,omitempty"`

	// +kubebuilder:validation:Optional
	LoadBalance *LoadBalanceParameters `json:"loadBalance,omitempty" tf:"load_balance,omitempty"`

	// Whether the WAN interface MAC address is overridden.
	// +kubebuilder:validation:Optional
	MacOverrideEnabled *bool `json:"macOverrideEnabled,omitempty" tf:"mac_override_enabled,omitempty"`

	// The name of the WAN network
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	ProviderCapabilities *ProviderCapabilitiesParameters `json:"providerCapabilities,omitempty" tf:"provider_capabilities,omitempty"`

	// Whether to report WAN events
	// +kubebuilder:validation:Optional
	ReportWanEvent *bool `json:"reportWanEvent,omitempty" tf:"report_wan_event,omitempty"`

	// Whether WAN settings are managed automatically by the controller or manually. Can be one of `auto` or `manual`.
	// +kubebuilder:validation:Optional
	SettingPreference *string `json:"settingPreference,omitempty" tf:"setting_preference,omitempty"`

	// The LAN network used for IPv6 single-network prefix delegation (used when the IPv6 delegation type is `single_network`).
	// +kubebuilder:validation:Optional
	SingleNetworkLan *string `json:"singleNetworkLan,omitempty" tf:"single_network_lan,omitempty"`

	// The name of the site to associate the WAN network with
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// +kubebuilder:validation:Optional
	Smartq *SmartqParameters `json:"smartq,omitempty" tf:"smartq,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *WanTimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// The WAN type (dhcp, static, pppoe)
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// The IPv6 WAN type. One of `dhcpv6`, `slaac`, `static`, or `disabled`. Note: the controller requires `slaac` when the IPv6 delegation type is `single_network` (`api.err.SingleNetworkMustBeSLAAC` otherwise) — common with ISPs that deliver IPv6 by Router Advertisement, e.g. Free/Freebox in bridge mode.
	// +kubebuilder:validation:Optional
	TypeV6 *string `json:"typeV6,omitempty" tf:"type_v6,omitempty"`

	// +kubebuilder:validation:Optional
	Upnp *UpnpParameters `json:"upnp,omitempty" tf:"upnp,omitempty"`

	// +kubebuilder:validation:Optional
	Vlan *VlanParameters `json:"vlan,omitempty" tf:"vlan,omitempty"`

	// The DS-Lite AFTR remote host. Only used when `wan_dslite_remote_host_auto` is disabled.
	// +kubebuilder:validation:Optional
	WanDsliteRemoteHost *string `json:"wanDsliteRemoteHost,omitempty" tf:"wan_dslite_remote_host,omitempty"`

	// Whether the DS-Lite AFTR remote host is detected automatically.
	// +kubebuilder:validation:Optional
	WanDsliteRemoteHostAuto *bool `json:"wanDsliteRemoteHostAuto,omitempty" tf:"wan_dslite_remote_host_auto,omitempty"`
}

type WanTimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type WanTimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type WanTimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

// WanSpec defines the desired state of Wan
type WanSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WanParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WanInitParameters `json:"initProvider,omitempty"`
}

// WanStatus defines the observed state of Wan.
type WanStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WanObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Wan is the Schema for the Wans API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,unifi}
type Wan struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   WanSpec   `json:"spec"`
	Status WanStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WanList contains a list of Wans
type WanList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Wan `json:"items"`
}

// Repository type metadata.
var (
	Wan_Kind             = "Wan"
	Wan_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Wan_Kind}.String()
	Wan_KindAPIVersion   = Wan_Kind + "." + CRDGroupVersion.String()
	Wan_GroupVersionKind = CRDGroupVersion.WithKind(Wan_Kind)
)

func init() {
	SchemeBuilder.Register(&Wan{}, &WanList{})
}
