// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DestinationIpsInitParameters struct {

	// The destination IPv4 address. Use `any` for all addresses.
	DestinationIP *string `json:"destinationIp,omitempty" tf:"destination_ip,omitempty"`

	// The WAN interface for this destination (e.g. `wan`, `wan2`).
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type DestinationIpsObservation struct {

	// The destination IPv4 address. Use `any` for all addresses.
	DestinationIP *string `json:"destinationIp,omitempty" tf:"destination_ip,omitempty"`

	// The WAN interface for this destination (e.g. `wan`, `wan2`).
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type DestinationIpsParameters struct {

	// The destination IPv4 address. Use `any` for all addresses.
	// +kubebuilder:validation:Optional
	DestinationIP *string `json:"destinationIp,omitempty" tf:"destination_ip,omitempty"`

	// The WAN interface for this destination (e.g. `wan`, `wan2`).
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`
}

type ForwardForwardInitParameters struct {

	// The forward IPv4 address to send traffic to.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The forward port or port range (e.g. `1-10,11,12`).
	Port *string `json:"port,omitempty" tf:"port,omitempty"`
}

type ForwardForwardObservation struct {

	// The forward IPv4 address to send traffic to.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The forward port or port range (e.g. `1-10,11,12`).
	Port *string `json:"port,omitempty" tf:"port,omitempty"`
}

type ForwardForwardParameters struct {

	// The forward IPv4 address to send traffic to.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The forward port or port range (e.g. `1-10,11,12`).
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`
}

type ForwardInitParameters struct {
	DestinationIps []DestinationIpsInitParameters `json:"destinationIps,omitempty" tf:"destination_ips,omitempty"`

	// Specifies whether the port forwarding rule is enabled or not.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Forward *ForwardForwardInitParameters `json:"forward,omitempty" tf:"forward,omitempty"`

	// Specifies whether to enable syslog logging for forwarded traffic.
	Logging *bool `json:"logging,omitempty" tf:"logging,omitempty"`

	// The name of the port forwarding rule.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The protocol for the port forwarding rule. Can be `tcp`, `udp`, or `tcp_udp`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The name of the site to associate the port forwarding rule with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	SourceLimiting *SourceLimitingInitParameters `json:"sourceLimiting,omitempty" tf:"source_limiting,omitempty"`

	Timeouts *TimeoutsInitParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	Wan *WanInitParameters `json:"wan,omitempty" tf:"wan,omitempty"`
}

type ForwardObservation struct {
	DestinationIps []DestinationIpsObservation `json:"destinationIps,omitempty" tf:"destination_ips,omitempty"`

	// Specifies whether the port forwarding rule is enabled or not.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	Forward *ForwardForwardObservation `json:"forward,omitempty" tf:"forward,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Specifies whether to enable syslog logging for forwarded traffic.
	Logging *bool `json:"logging,omitempty" tf:"logging,omitempty"`

	// The name of the port forwarding rule.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The protocol for the port forwarding rule. Can be `tcp`, `udp`, or `tcp_udp`.
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The name of the site to associate the port forwarding rule with.
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	SourceLimiting *SourceLimitingObservation `json:"sourceLimiting,omitempty" tf:"source_limiting,omitempty"`

	Timeouts *TimeoutsObservation `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	Wan *WanObservation `json:"wan,omitempty" tf:"wan,omitempty"`
}

type ForwardParameters struct {

	// +kubebuilder:validation:Optional
	DestinationIps []DestinationIpsParameters `json:"destinationIps,omitempty" tf:"destination_ips,omitempty"`

	// Specifies whether the port forwarding rule is enabled or not.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// +kubebuilder:validation:Optional
	Forward *ForwardForwardParameters `json:"forward,omitempty" tf:"forward,omitempty"`

	// Specifies whether to enable syslog logging for forwarded traffic.
	// +kubebuilder:validation:Optional
	Logging *bool `json:"logging,omitempty" tf:"logging,omitempty"`

	// The name of the port forwarding rule.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The protocol for the port forwarding rule. Can be `tcp`, `udp`, or `tcp_udp`.
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The name of the site to associate the port forwarding rule with.
	// +kubebuilder:validation:Optional
	Site *string `json:"site,omitempty" tf:"site,omitempty"`

	// +kubebuilder:validation:Optional
	SourceLimiting *SourceLimitingParameters `json:"sourceLimiting,omitempty" tf:"source_limiting,omitempty"`

	// +kubebuilder:validation:Optional
	Timeouts *TimeoutsParameters `json:"timeouts,omitempty" tf:"timeouts,omitempty"`

	// +kubebuilder:validation:Optional
	Wan *WanParameters `json:"wan,omitempty" tf:"wan,omitempty"`
}

type SourceLimitingInitParameters struct {

	// Specifies whether source limiting is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the firewall group to use for source limiting.
	FirewallGroupID *string `json:"firewallGroupId,omitempty" tf:"firewall_group_id,omitempty"`

	// The source IPv4 address (or CIDR) of the port forwarding rule. For all traffic, specify `any`.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The source limiting type. Can be `ip` or `firewall_group`. Inferred automatically when only one of `ip` or `firewall_group_id` is set.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SourceLimitingObservation struct {

	// Specifies whether source limiting is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the firewall group to use for source limiting.
	FirewallGroupID *string `json:"firewallGroupId,omitempty" tf:"firewall_group_id,omitempty"`

	// The source IPv4 address (or CIDR) of the port forwarding rule. For all traffic, specify `any`.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The source limiting type. Can be `ip` or `firewall_group`. Inferred automatically when only one of `ip` or `firewall_group_id` is set.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type SourceLimitingParameters struct {

	// Specifies whether source limiting is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// The ID of the firewall group to use for source limiting.
	// +kubebuilder:validation:Optional
	FirewallGroupID *string `json:"firewallGroupId,omitempty" tf:"firewall_group_id,omitempty"`

	// The source IPv4 address (or CIDR) of the port forwarding rule. For all traffic, specify `any`.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The source limiting type. Can be `ip` or `firewall_group`. Inferred automatically when only one of `ip` or `firewall_group_id` is set.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TimeoutsInitParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsObservation struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type TimeoutsParameters struct {

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Create *string `json:"create,omitempty" tf:"create,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
	// +kubebuilder:validation:Optional
	Delete *string `json:"delete,omitempty" tf:"delete,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
	// +kubebuilder:validation:Optional
	Read *string `json:"read,omitempty" tf:"read,omitempty"`

	// A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
	// +kubebuilder:validation:Optional
	Update *string `json:"update,omitempty" tf:"update,omitempty"`
}

type WanInitParameters struct {

	// The WAN IP address for the port forwarding rule. Use `any` for all addresses.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// The WAN interface. Can be `wan`, `wan2`, or `both`.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// The WAN port or port range (e.g. `1-10,11,12`).
	Port *string `json:"port,omitempty" tf:"port,omitempty"`
}

type WanObservation struct {

	// The WAN IP address for the port forwarding rule. Use `any` for all addresses.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// The WAN interface. Can be `wan`, `wan2`, or `both`.
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// The WAN port or port range (e.g. `1-10,11,12`).
	Port *string `json:"port,omitempty" tf:"port,omitempty"`
}

type WanParameters struct {

	// The WAN IP address for the port forwarding rule. Use `any` for all addresses.
	// +kubebuilder:validation:Optional
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// The WAN interface. Can be `wan`, `wan2`, or `both`.
	// +kubebuilder:validation:Optional
	Interface *string `json:"interface,omitempty" tf:"interface,omitempty"`

	// The WAN port or port range (e.g. `1-10,11,12`).
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`
}

// ForwardSpec defines the desired state of Forward
type ForwardSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ForwardParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ForwardInitParameters `json:"initProvider,omitempty"`
}

// ForwardStatus defines the observed state of Forward.
type ForwardStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ForwardObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Forward is the Schema for the Forwards API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,unifi}
type Forward struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ForwardSpec   `json:"spec"`
	Status            ForwardStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ForwardList contains a list of Forwards
type ForwardList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Forward `json:"items"`
}

// Repository type metadata.
var (
	Forward_Kind             = "Forward"
	Forward_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Forward_Kind}.String()
	Forward_KindAPIVersion   = Forward_Kind + "." + CRDGroupVersion.String()
	Forward_GroupVersionKind = CRDGroupVersion.WithKind(Forward_Kind)
)

func init() {
	SchemeBuilder.Register(&Forward{}, &ForwardList{})
}
